CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='gcc -E'
CMK_CC='gcc '
CMK_CXX='g++ '
CMK_CXXPP="$CMK_CXX -x c++ -E  "
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt -lelan'
CMK_LD_SHARED="-shared"
#CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"
CMK_QT='generic64'
CMK_XIOPTS=''
CMK_F90LIBS='-lUfor -lfor -lFutil'
CMK_MOD_EXT="mod"
CMK_NO_BUILD_SHARED=true
