CMK_CPP_C='cc -E -I/usr/opt/rms/include '
CMK_CC='cc  -I/usr/opt/rms/include '
CMK_CC_RELIABLE='cc -D_REENTRANT -I/usr/opt/rms/include '
CMK_CC_FASTEST='cc -D_REENTRANT -I/usr/opt/rms/include '
CMK_CXX='cxx -D_REENTRANT -D__USE_STD_IOSTREAM -I/usr/opt/rms/include '
CMK_CXXPP="$CMK_CXX -x c++ -E "
CMK_LD="cc -D_REENTRANT -expect_unresolved '*' -I/usr/opt/rms/include "
CMK_LDXX="$CMK_CXX"
CMK_SEQ_CC='cc'
CMK_SEQ_LD='cc'
CMK_SEQ_CXX="$CMK_CXX"
CMK_SEQ_LDXX="$CMK_CXX"
CMK_CPP_SUFFIX="ii"
CMK_QT='axp-osf1-cc'
