# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex
DEST=jade
LATEX2HTML=$(L2H) -split 4
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/jade">Jade Homepage</a><br>'

include ../Makefile.common

index.tex:
	touch index.tex
