# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex tracing.tex 

DEST=projections
LATEX2HTML=$(L2H) -split 5
DOCTITLE='P<SMALL>ROJECTIONS</SMALL> Manual'

include ../Makefile.common

index.tex:
	touch index.tex
