$(L)/libconv-cplus-n.a: machine.c machine-dgram.c machine-tcp.c machine-eth.c machine-mx.c machine-gm.c machine.h machine-smp.c machine-ammasso.h machine-ammasso.c machine-ibverbs.c machine-pxshm.c machine-sysvshm.c conv-onesided.c immediate.c machine-recover.c machine-commthd-util.c $(CVHEADERS)

charmrun: sockRoutines.c sockRoutines.h ccs-server.c ccs-server.h sockRoutines-seq.o $(L)/libck.a $(CVLIBS)
	if [ ! -f charmrun ]; then \
			(cd charmrun-src ; $(MAKE) OPTS='$(OPTS) -Wno-error' -j1) ; fi
