# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex
DEST=netfem
LATEX2HTML=$(L2H) -split 3
DOCTITLE='NetFEM Manual'
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/fem">FEM Homepage</a><br>'

include ../Makefile.common

index.tex:
	touch index.tex
