#!/bin/bash
#
# Conv-host for MPI:
#  Translates +pN-style conv-host options into
# mpirun -npN options.

export FROM_CHARMRUN='1'

args=""

# Arguments that need to be passed to the charm application, not mpirun (e.g. ++quiet)
charm_args=""
pes=0
nodes=0
ppn=1
QUIET=0
XTERM='xterm'
DEBUG=0
DEBUG_NO_PAUSE=0
DEBUGGER='gdb'

while [ $# -gt 0 ]
do
	case $1 in
	+n|++n|++np)
		nodes=$2
		shift
		;;
	+n[0-9]*)
		nodes="${1#\+n}"
		;;
	++n[0-9]*)
		nodes="${1#\+\+n}"
		;;
	++np[0-9]*)
		nodes="${1#\+\+np}"
		;;
	+ppn|++ppn)
		args=$args" +ppn "$2
		ppn=$2
		shift
		;;
	+ppn[0-9]*)
		args=$args" "$1
		ppn="${1#\+ppn}"
		;;
	++ppn[0-9]*)
		args=$args" "$1
		ppn="${1#\+\+ppn}"
		;;
	+p|++p)
		pes=$2
		shift
		;;
	+p[0-9]*)
		pes="${1#\+p}"
		;;
	++p[0-9]*)
		pes="${1#\+\+p}"
		;;
	+pemap)
	    args=$args" "$1" "$2
	    shift
	    ;;
	-machinefile)
	    args=" $1 $2 $args"
	    shift
	    ;;
	++quiet)
	    QUIET=1
	    ;;
	++no-quiet)
	    QUIET=0
	    ;;
	++local|++no-local)
		# Ignored (unsupported by MPI layer)
		;;
	++xterm)
		XTERM=$2
		shift
		;;
	++debug)
		DEBUG=1
		;;
	++no-debug)
		DEBUG=0
		;;
	++debug-no-pause)
		DEBUG_NO_PAUSE=1
		;;
	++no-debug-no-pause)
		DEBUG_NO_PAUSE=0
		;;
	++debugger)
		DEBUGGER=$2
		shift
		;;
	*)
	    args=$args" "$1
	    ;;
    esac
    shift
done

test $QUIET -eq 1 && charm_args=$charm_args" "++quiet

args=$args" "$charm_args

if [ "$DEBUG" = '1' ] || [ "$DEBUG_NO_PAUSE" = '1' ]
then
  DEBUG_RUN='-ex r'
  DEBUG_POSTFIX='--args'
  if [ "$DEBUGGER" = 'lldb' ]
  then
    DEBUG_RUN='-o r'
    DEBUG_POSTFIX='--'
  fi

  args="$DEBUG_POSTFIX $args"
  [ "$DEBUG_NO_PAUSE" = '1' ] && args="$DEBUG_RUN $args"
  args="$XTERM -e $DEBUGGER $args"
fi

if [[ $nodes = 0 ]]
then
  [[ $pes = 0 ]] && pes=1
  if [[ $(($pes % $ppn)) -ne 0 ]]
  then
    printf "Charmrun> Error: ++ppn $ppn (number of PEs per node) does not divide +p $pes (number of PEs).\n"
    exit 1
  else
    nodes=$(($pes / $ppn))
  fi
elif [[ $pes != 0 && $pes != $(($nodes * $ppn)) ]]
then
  printf "Charmrun> Error: +n/++np $nodes times ++ppn $ppn does not equal +p $pes.\n"
  exit 1
fi

[[ $QUIET -eq 0 ]] && printf "\nRunning as $nodes OS processes: $args\n"


mpiexec_cmd=$(command -v mpiexec 2>/dev/null)
if test -n "$mpiexec_cmd"
then
    [[ $QUIET -eq 0 ]] && echo "charmrun> $mpiexec_cmd -n $nodes $args" && echo
    # shellcheck disable=SC2086
    "$mpiexec_cmd" -n $nodes $args
else
    echo "Don't know how to run MPI program."
    exit 1
fi
