CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='gcc -E'
CMK_CC='gcc '
CMK_CXX='g++'
CMK_CXXPP='g++ -E '
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='true'
CMK_LIBS='-lckqt'
CMK_SEQ_LD='gcc -static '
CMK_SEQ_LDXX='g++ -static '
CMK_XIOPTS=''

