
lib:
	cd searchengineLib; make;

nqueens:
	cd NQueens; make;

UTS:
	cd UnbalancedTreeSearch_SE; make;

clean:
	cd searchengineLib; make clean; cd ../NQueens; make clean;  cd ../UnbalancedTreeSearch_SE; make clean;
