# Makefile fragment for inclusion by lv3d client program.
#  The client doesn't include Charm++, so this isn't everything.
COBJS=ckpointviewable.o ckviewable.o ckviewpoint.o \
	lv3d0.o

CSRC=ckpointviewable.cpp ckviewable.cpp ckviewpoint.cpp lv3d0.C lv3d1.C

makelinks:
	ln -fs \
		$(LV3DIR)/ckpointviewable.cpp \
		$(LV3DIR)/ckviewable.cpp \
		$(LV3DIR)/ckviewpoint.cpp \
		$(LV3DIR)/lv3d0.C \
		$(LV3DIR)/lv3d1.C \
		$(LV3DIR)/*.h \
		.
