# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex overview.tex charm.tex arrays.tex groups.tex messages.tex \
	other.tex install.tex debugging.tex ports.tex converse.tex internals.tex pup.tex
DEST=faq
LATEX2HTML=$(L2H) -split 4
DOCTITLE='Charm++ Frequently Asked Questions'

include ../Makefile.common

index.tex:
	touch index.tex
