# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex overview.tex general.tex charm.tex arrays.tex groups.tex nodegroups.tex messages.tex \
	other.tex install.tex debugging.tex ports.tex converse.tex internals.tex
DEST=faq
LATEX2HTML=$(L2H) -split 2

include ../Makefile.common

index.tex:
	touch index.tex
