#!/bin/bash
CHARMBIN="$(dirname "$0")"

export AMPICC="$(basename "$0")"
export AMPICC_MODE='ampif'

cp -n "$CHARMBIN/../include/mpif.h" .
"$CHARMBIN/ampiCC" "$@"
status=$?
rm -f 'mpif.h'
exit $status
