module MPIINCL
  include 'ampif.h'

  external MPI_Send
  external MPI_Recv
  external MPI_Get_count
  external MPI_Isend
  external MPI_Irecv
  external MPI_Wait
  external MPI_Test
  external MPI_Waitany
  external MPI_Testany
  external MPI_Waitall
  external MPI_Testall
  external MPI_Waitsome
  external MPI_Testsome
  external MPI_Request_free
  external MPI_Cancel
  external MPI_Iprobe
  external MPI_Probe
  external MPI_Send_init
  external MPI_Recv_init
  external MPI_Start
  external MPI_Startall
  external MPI_Sendrecv
  external MPI_Sendrecv_replace
  external MPI_Type_contiguous
  external MPI_Type_vector
  external MPI_Type_hvector
  external MPI_Type_indexed
  external MPI_Type_hindexed
  external MPI_Type_struct
  external MPI_Type_commit
  external MPI_Type_free
  external MPI_Type_extent
  external MPI_Type_size
  external MPI_Type_lb
  external MPI_Type_ub
  external MPI_Address
  external MPI_Get_element
  external MPI_Pack
  external MPI_Unpack
  external MPI_Pack_size

  external MPI_Barrier
  external MPI_Bcast
  external MPI_Gather
  external MPI_Gatherv
  external MPI_Scatter
  external MPI_Scatterv
  external MPI_Allgather
  external MPI_Iallgather
  external MPI_Allgatherv
  external MPI_Alltoall
  external MPI_Ialltoall
  external MPI_Alltoallv
  external MPI_Reduce
  external MPI_Ireduce
  external MPI_Allreduce
  external MPI_Iallreduce
  external MPI_Reduce_scatter
  external MPI_Scan

  external MPI_Group_size
  external MPI_Group_rank
  external MPI_Group_translate_ranks
  external MPI_Group_compare
  external MPI_Comm_group
  external MPI_Group_union
  external MPI_Group_intersection
  external MPI_Group_difference
  external MPI_Group_incl
  external MPI_Group_excl
  external MPI_Group_range_incl
  external MPI_Group_range_excl
  external MPI_Group_free
  external MPI_Comm_create
  external MPI_Comm_size
  external MPI_Comm_rank
  external MPI_Comm_dup
  external MPI_Comm_split
  external MPI_Comm_free
  external MPI_Comm_test_inter
  external MPI_Comm_remote_size
  external MPI_Comm_remote_group
  external MPI_Intercomm_create
  external MPI_Intercomm_merge
  external MPI_Keyval_create
  external MPI_Keyval_free
  external MPI_Attr_put
  external MPI_Attr_get
  external MPI_Attr_delete

  external MPI_Cart_create
  external MPI_Graph_create
  external MPI_Topo_test
  external MPI_Cart_map
  external MPI_Graph_map
  external MPI_Cartdim_get
  external MPI_Cart_get
  external MPI_Cart_rank
  external MPI_Cart_coords
  external MPI_Cart_shift
  external MPI_Graphdims_get
  external MPI_Graph_get
  external MPI_Graph_neighbors_count
  external MPI_Graph_neighbors
  external MPI_Dims_create
  external MPI_Cart_sub

  external MPI_Get_processor_name
  external MPI_Errhandler_create
  external MPI_Errhandler_set
  external MPI_Errhandler_get
  external MPI_Errhandler_free
  external MPI_Error_string
  external MPI_Error_class
  external MPI_Init
  external MPI_Initialized
  external MPI_Init_universe
  external MPI_Finalize
  external MPI_Abort

  external MPI_Yield
  external MPI_Resume
  external MPI_Print
  external MPI_Register_main
  external MPI_Setmigratable
  external MPI_Migrate
  external MPI_Checkpoint
  external MPI_Get_userdata

  external MPI_Type_get_envelope
  external MPI_Type_get_contents

  external MPI_Win_create
  external MPI_Win_free
  external MPI_Win_delete_attr
  external MPI_Win_get_group
  external MPI_Win_set_name
  external MPI_Win_get_name
  external MPI_Win_fence
  external MPI_Win_lock
  external MPI_Win_unlock
  external MPI_Win_post
  external MPI_Win_wait
  external MPI_Win_start
  external MPI_Win_complete
  external  MPI_Alloc_mem
  external MPI_Free_mem
  external MPI_Put
  external MPI_Get
  external MPI_Accumulate

end module MPIINCL
