#!/bin/sh
CHARMBIN=`dirname $0`

while [ ! $# -eq 0 ]
do
  arg="$1"
  case "$arg" in
  -show)
     echo "charmc"
     exit 0
     ;;
  *) break
     ;;
  esac
  shift
done

charmarch=$(cat $CHARMBIN/../tmp/.gdir)

AMPICC_EXTRA_OPTIONS=""

if test "$charmarch" = "mpi"
then
    dirName=ampicc.inc.$$
    mkdir $dirName
    ln $CHARMBIN/../include/mpi.h $dirName/mpi.h   2>/dev/null
    AMPICC_EXTRA_OPTIONS="-I./$dirName"
fi

[ -f $CHARMBIN/../lib/libampiromio.a ] && ROMIO=-lampiromio

$CHARMBIN/charmc -language ampi -default-to-aout $AMPICC_EXTRA_OPTIONS $@ $ROMIO
status=$?

if test "$charmarch" = "mpi"
then
    /bin/rm -f $dirName/mpi.h 2>/dev/null
    rmdir $dirName
fi

# Copy ampirun, but do not overwrite it if it already exists.
cp -n $CHARMBIN/ampirun .

exit $status
