# Stub makefile for LaTeX PPL manual
FILE=manual
TEX= $(FILE).tex cldb.tex   cpm.tex     index.tex   msgmgr.tex  random.tex  \
	cms.tex    ds.tex       ldb.tex   cpath.tex  futures.tex  pthreads.tex
DEST=convext
LATEX2HTML=$(L2H) -split 5
DOCTITLE='Converse Extensions Library Manual'

include ../Makefile.common

index.tex:
	touch index.tex
