#!/bin/csh -f
goto begin
syntax:
  echo ''
  echo 'Usage: SUPER-INSTALL <target> <version> [charmc-options ...]'
  echo ''
  echo 'targets: converse, charm, charm++'
  echo ''
  echo 'versions: ' `( cd src ; ls -1 | egrep -v '^Common' )`
  echo ''
  echo 'example charmc-options: -g -save -verbose'
  echo ''
  echo ''
  echo 'Note: This script is trivial.  It'
  echo ''
  echo ' 1. Creates directories <version> and <version>/tmp'
  echo ' 2. Copies src/Common/scripts/Makefile into <version>/tmp'
  echo ' 3. Does a "make <target> <version> OPTS=<charmc-options>" in <version>/tmp.'
  echo ''
  echo "That's all SUPER_INSTALL does.  The rest is handled by the Makefile."
  echo ''
  exit 1

begin:

  if ($#argv < 2) goto syntax
  set PROGRAM=$1 ; shift
  set VERSION=$1 ; shift

  if ( x$VERSION == x ) goto syntax
  if { ( echo $2 | egrep -s '^Common' ) } goto syntax
  if ( ! -d src/$VERSION ) goto syntax

  echo "Creating directories: $VERSION and $VERSION/tmp"
  if (! -d $VERSION     ) mkdir $VERSION
  if (! -d $VERSION/tmp ) mkdir $VERSION/tmp
  echo "Copying src/Common/scripts/Makefile to $VERSION/tmp"
  rm -f $VERSION/tmp/Makefile
  ln -s ../../src/Common/scripts/Makefile $VERSION/tmp/Makefile
  echo "Performing 'make $PROGRAM OPTS="$*"' in $VERSION/tmp"
  cd $VERSION/tmp ; make $PROGRAM OPTS="$*"

