. $CHARMINC/cc-gcc.sh

#CMK_DEFS="$CMK_DEFS -DHAVE_USR_INCLUDE_MALLOC_H=1 "
CMK_DEFS="$CMK_DEFS -D_REENTRANT"

CMK_XIOPTS=""
CMK_LIBS="-lpthread $CMK_LIBS"
CMK_CXX_OPTIMIZE="-O3"
CMK_NO_PARTITIONS="1"

CMK_QT='generic64-light'

CMK_MULTICORE='1'
