CMK_CPP_CHARM='/usr/lib/cpp '
CMK_CPP_C='gcc -E '
CMK_CC='gcc '
CMK_CXX='g++ '
CMK_CXXPP='g++ -E '
CMK_CF77='f77'
CMK_CF90='f90 '
CMK_RANLIB='true'
CMK_LIBS='-lckqt'
CMK_F90LIBS='-L/usr/lib32 -lfortran -lftn'
CMK_QT='irix5-gcc'
CMK_XIOPTS=''

