$(L)/libconv-machine.a: machine.c machine-dgram.c machine.h machine-smp.c machine-ibverbs.c conv-onesided.c immediate.c machine-recover.c machine-onesided.h machine-onesided.c machine-commthd-util.c $(CVHEADERS)

charmrun: sockRoutines.c sockRoutines.h ccs-server.c ccs-server.h sockRoutines-seq.o $(L)/libck.a $(CVLIBS)
	 cd charmrun-src ; $(MAKE) OPTS='$(OPTS) -Wno-error' -j1 
