
#undef CMK_MACHINE_NAME

#undef CMK_BOOL_DEFINED
#undef CMK_BOOL_UNDEFINED

#undef CMK_EXPLICIT

#undef CMK_SIGNEDCHAR_DIFF_CHAR

#undef CMK_CPP_CAST_LEGAL
#undef CMK_CPP_CAST_ILLEGAL

#undef CMK_TEMPLATE_MEMBERS_BROKEN

#undef CMK_STL_USE_DOT_H
#undef CMK_STL_DONT_USE_DOT_H

#undef CMK_NAMESPACES_BROKEN

#undef CMK_MULTIPLE_DELETE

#undef CMK_USE_POLL

#undef CMK_FORTRAN_USES_ALLCAPS
#undef CMK_FORTRAN_USES_TWOSCORE
#undef CMK_FORTRAN_USES_ONESCORE
#undef CMK_FORTRAN_USES_NOSCORE

