#! /bin/sh
# output from this program is piped to telnet on port 80
echo "GET /distrib/libpthread.uu 1.0"
echo
# exit normally when the telnet session closes.
trap "exit 0" 13
while : ; do
 echo
 sleep 1
done
