#!/bin/bash

CHARMBIN=$(cd "$(dirname "$0")" && pwd)
[[ -f "$CHARMBIN/../include/conv-mach-opt.sh" ]] && . "$CHARMBIN/../include/conv-mach-opt.sh" 2>/dev/null

if [[ "$CMK_RECONVERSE" = "1" ]]
then
  # Reconverse run idiom: no charmrun. Single process is `./pgm +pe N`;
  # multi-process is `lcrun -n <procs> ./pgm +pe <total>` (set TESTRUN_PROCS).
  # Translate the classic conventions used by the tests' Makefiles: +pN or
  # "+p N" becomes +pe N; ++ppn and ++local are meaningless here and dropped.
  p=1; prog=""; args=(); expect_p=0; expect_ppn=0
  for a in "$@"; do
    if [[ $expect_p -eq 1 ]];   then p=$a; expect_p=0; continue; fi
    if [[ $expect_ppn -eq 1 ]]; then expect_ppn=0; continue; fi
    case "$a" in
      +p)        expect_p=1 ;;
      +p[0-9]*)  p=${a#+p} ;;
      ++ppn)     expect_ppn=1 ;;
      ++ppn*)    ;;
      ++local)   ;;
      *) if [[ -z "$prog" && ( "$a" == ./* || -x "$a" ) ]]; then prog="$a"; else args+=("$a"); fi ;;
    esac
  done
  if [[ -z "$prog" ]]; then echo "testrun: no program in args: $*" >&2; exit 1; fi
  procs=${TESTRUN_PROCS:-1}
  # Can't spread fewer PEs than processes; clamp. And reconverse requires
  # PEs divisible by processes -- skip indivisible combinations with a
  # warning (mirrors the classic ppn-divides-p courtesy skip).
  if [[ $procs -gt $p ]]; then procs=$p; fi
  if (( p % procs != 0 )); then
    echo "testrun(reconverse): +pe $p not divisible by $procs processes. Skipping the test."
    exit 0
  fi
  envpfx=(env "DYLD_LIBRARY_PATH=$CHARMBIN/../lib:${DYLD_LIBRARY_PATH}" "LD_LIBRARY_PATH=$CHARMBIN/../lib:${LD_LIBRARY_PATH}")
  if [[ $procs -gt 1 ]]; then
    LCRUN="$CHARMBIN/../_deps/lci-src/lcrun"
    [[ -x "$LCRUN" ]] || LCRUN=lcrun
    cmd=("$LCRUN" -n "$procs" "${envpfx[@]}" "$prog" +pe "$p" "${args[@]}")
  else
    cmd=("${envpfx[@]}" "$prog" +pe "$p" "${args[@]}")
  fi
  echo "testrun(reconverse): ${cmd[*]}"
  time "${cmd[@]}"
  exit $?
fi

#check if ppn divides p
ppn_found=0
ppn=0
#parse the arguments to extract the ppn number
IFS=' ' read -r -a array <<< "$*"
for i in "${array[@]}"
do
  if [[ $ppn_found -eq 1 ]] ; then
    ppn=$i
    #echo "FOUND ppn:" $i
    break
  fi
  if [[ $i == *"ppn"* ]]; then
    ppn=$(echo "$i" | cut -d'n' -f 2)
    if [[ -z "$ppn" ]]
    then
        ppn_found=1
    else
        break
    fi
  fi

done

#now parse the arguments to run to find the p number
p=0
p_found=0
IFS=' ' read -r -a array <<< "$*"
for i in "${array[@]}"
do
  if [[ $p_found -eq 1 ]] ; then
    p=$i
    #echo "FOUND p:" $p
    break
  fi
  if [[ $i == "+p"* ]]; then
    p=$(echo "$i" | cut -d'p' -f 2)
    if [[ -z "$p" ]]
    then
        p_found=1
    else
        break
    fi
  fi
done

#if ppn is zero, don't do division test
if [[ $ppn -eq 0 ]] ; then
    time ./charmrun "$@"
else #division test
    #check if p divides ppn
    m=$((p % ppn))
    if [[ $p -ne 0 && $m -eq 0 ]] ; then
      #if it divides run the test
      time ./charmrun "$@"
    else
      #if it does not divide, give a warning and do not run
      echo "Warning: ppn does not divide p. Skipping the test."
    fi
fi
