#  Bluegene/P specific Make rules



$(L)/libtrace-controlPoints.a : trace-controlPoints-BGP.o


# The BGP performance counter library UPC must be compiled with gcc:
trace-controlPoints-BGP.o : trace-controlPoints-BGP.C
	g++ -c trace-controlPoints-BGP.C -o trace-controlPoints-BGP.o  -I/bgsys/drivers/ppcfloor/arch/include/ $(OPTS) -g
