#!/bin/sh
# A shell script to compare the various load-balancing
# strategies.

stratList="greedy metis random none"

mkdir out
processors=8
lb_arg="1200 32 1 5"

for strategy in `echo $stratList`
do
	echo "---- $strategy:---"
	file1="out/run.$strategy"
	file2="out/time.$strategy"
	mpirun -np $processors lb_test $strategy $lb_arg | tee $file1
	head $file1 > $file2
	grep GREP00 $file1 >> $file2
done

echo "Timings in out/"
