#!/bin/sh
#
# Just executes all its arguments.
# but move ++ options after the program.
PATH=.:$PATH
export PATH

args=""
cmd=""

while [ $# -gt 0 ]
do 
	case $1 in
	+p)
		args=$args" "$1" "$2
		shift
		;;
	+p*)
		args=$args" "$1
		;;
	++*)
		args=$args" "$1
		;;
	*)
		cmd=$cmd" "$1
		;;
	esac
	shift
done

echo "$cmd $args"
$cmd $args
