# Absolute paths to Kokkos build folders should be set here.
KOKKOS_OMP_BUILD_PATH ?= /home/kokkos/build-omp
KOKKOS_CUDA_BUILD_PATH ?= /home/kokkos/build-cuda

KOKKOS_OMP_INC = $(KOKKOS_OMP_BUILD_PATH)/include
KOKKOS_OMP_LIB = $(KOKKOS_OMP_BUILD_PATH)/lib
KOKKOS_CUDA_INC = $(KOKKOS_CUDA_BUILD_PATH)/include
KOKKOS_CUDA_LIB = $(KOKKOS_CUDA_BUILD_PATH)/lib

NVCC_WRAPPER = $(KOKKOS_CUDA_BUILD_PATH)/bin/nvcc_wrapper
NVCC_OPTS = -O3 -fopenmp -Wfatal-errors

CHARMC = ../../../../../bin/charmc $(OPTS)
