CHARMC=../../../bin/charmc $(OPTS)

CHARMBIN=..\..\..\bin
CPP = cl.exe

INC = /I"..\..\..\include"

CPP_PROJ=/nologo /MT /w /O2 /Ox $(INC)\
 /D "WIN32" /D "_DEBUG" /D "_WINDOWS" /YX\
 /Fo /c

LINK=link.exe
LINK_FLAGS = /nologo /LIBPATH:"..\..\..\lib" /nodefaultlib:"libc"
LINK_OTHER = libldb-rand.o libconv-core.a libconv-util.a libtrace-none.a libconv-cplus-y.a ws2_32.lib kernel32.lib

OBJS=commbench.obj overhead.obj timer.obj proc.obj smputil.obj pingpong.obj ctxt.obj

all: pgm

pgm: $(OBJS) link

link:
	$(LINK) $(LINK_FLAGS) $(LINK_OTHER) /out:"pgm.exe" $(OBJS)
	copy $(CHARMBIN)\charmrun.exe .

test: pgm
	./charmrun pgm +p4

commbench.obj: commbench.c
	$(CPP) $(CPP_PROJ) commbench.c

overhead.obj: overhead.c
	$(CPP) $(CPP_PROJ) overhead.c

timer.obj: timer.c
	$(CPP) $(CPP_PROJ)  timer.c

proc.obj: proc.c
	$(CPP) $(CPP_PROJ)  proc.c

smputil.obj: smputil.c
	$(CPP) $(CPP_PROJ)  smputil.c

pingpong.obj: pingpong.c
	$(CPP) $(CPP_PROJ)  pingpong.c

ctxt.obj: ctxt.c
	$(CPP) $(CPP_PROJ)  ctxt.c

clean:
	rm -f core *.cpm.h
	rm -f TAGS *.obj
	rm -f pgm.exe
	rm -f conv-host.exe charmrun.exe
