# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex comm.tex mesh.tex
DEST=parfum
LATEX2HTML=$(L2H) -split 4
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/ParFUM">ParFUM Homepage</a><br>'

include ../Makefile.common
