/*  DUMMY unistd.h for net-win32 build */
/*  
    for example:
    xi-scan.C which is automatically generated by flex needs this header
    file 
*/

#ifdef __cplusplus
extern "C"
#endif
int isatty (int );

