#!/bin/sh
LOADBALANCERS="RandCentLB RecBisectBfLB MetisLB RefineLB CommLB Comm1LB\
           HeapCentLB NeighborLB WSLB GreedyRefLB RandRefLB"

out="Makefile_lb"

echo "# Automatically generated by script Makefile_lb.sh" > $out
echo "#  by" `id` >>$out
echo "#  at" `hostname` >>$out
echo "#  on" `date` >> $out
echo "LOADBALANCERS=\\" >> $out
for bal in $LOADBALANCERS 
do 
	echo "   \$(L)/libmodule$bal.a \\" >> $out 
done

echo >> $out

for bal in $LOADBALANCERS 
do 
	cat >> $out << EOB 
$bal.decl.h: $bal.ci charmxi
	\$(CHARMC) $bal.ci

$bal.o: $bal.C $bal.decl.h \$(CKHEADERS)
	\$(CHARMC) -c $bal.C

\$(L)/libmodule$bal.a: $bal.o
	\$(CHARMC) -o \$(L)/libmodule$bal.a $bal.o

EOB
done
