CMK_CC='xlc_r '
CMK_CXX='xlc++_r -qstaticinline '
CMK_LD="$CMK_CC -brtl "
CMK_LDXX="$CMK_CXX -brtl "
OPTS_CC=
OPTS_CXX=
OPTS_LD=
OPTS_LDXX=
CMK_NATIVE_CC='xlc_r '
CMK_NATIVE_LD='xlc++_r '
CMK_NATIVE_CXX='xlc++_r -qstaticinline '
CMK_NATIVE_LDXX='xlc++_r '
CMK_CF77='xlf_r  '
CMK_CF90='xlf90_r  -qsuffix=f=f90' 
CMK_CF90_FIXED='xlf90_r ' 
CMK_C_OPTIMIZE='-O3 -qstrict -Q  '
CMK_CXX_OPTIMIZE='-O3 -qstrict -Q '
CMK_AR='ar cq'
CMK_NM='nm '
CMK_QT='aix'
