/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 146
#define YY_END_OF_BUFFER 147
static yyconst short int yy_accept[551] =
    {   0,
        0,    0,  147,  146,    2,    4,    3,  105,  146,   93,
      107,  100,  146,   90,   91,  101,  102,   92,  103,   99,
      106,   85,   84,  113,  114,  108,  115,  109,  112,   83,
       83,   83,   83,   83,   97,   98,  110,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   95,  111,
       96,  104,    2,    4,    0,    3,  127,    0,   89,    0,
        0,   94,  142,    0,    0,    0,  132,  128,  137,    0,
        0,  130,  120,  133,  121,  134,  118,  116,    0,   87,
        1,  131,   87,   85,    0,    0,   85,   85,    0,   84,

       84,   84,  117,  122,  124,    0,  126,   14,  125,  123,
       83,   83,   83,    0,    0,   83,   83,  138,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   32,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   43,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,  139,  129,    0,    0,    0,    0,    0,
        0,    0,   88,    0,    0,  119,  140,    0,   87,    1,
        0,   87,   85,   86,   84,  135,   15,  136,   16,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,

       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   41,   83,   83,   83,   83,   83,   83,   83,
       83,   47,   83,   83,   83,   83,   74,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,    0,    0,    0,  141,    0,    0,
        0,    0,    0,    0,    0,   87,   86,   86,   83,   83,
       83,   83,   83,   83,   23,   83,   25,   26,   83,   83,
       83,   83,   83,   83,   83,   34,   35,   83,   83,   37,
       83,   83,   83,   83,   42,   83,   83,   83,   83,   83,

       83,   48,   49,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   80,   83,   83,   83,   83,
       83,   64,   83,   83,   83,   83,    0,    0,    0,  141,
        0,    0,  145,    0,    0,    0,    0,   86,   83,   17,
       83,   83,   83,   83,   24,    5,   69,   27,   83,   83,
       83,   83,   83,   36,   13,   38,   83,   40,   83,   12,
       83,   44,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   54,   83,   83,   83,   83,   83,   83,   61,   62,

       83,   83,   83,   83,   66,   83,    0,    0,  145,    0,
        0,   83,   83,   83,   83,   83,   83,   83,   30,   70,
       33,   39,   71,   11,   45,   83,   72,   83,   83,   83,
       83,   83,   83,   83,   83,   50,   83,   83,   83,   79,
       83,   83,   53,   55,   56,   57,   58,   59,   83,   83,
       83,   83,   83,   83,    0,    0,  144,   83,   18,   83,
       83,   83,   83,   29,   31,   46,   10,   83,   83,   83,
       83,   83,   83,   83,   78,   83,   83,   83,   83,   60,
       83,   81,   83,   67,   83,    0,  144,  144,  144,   83,
       83,   83,   83,   28,   83,   83,   19,   20,   83,   75,

       76,   83,   83,    8,   52,   63,   65,   83,  144,   83,
       83,   68,   83,    7,   83,   83,   77,   51,    9,  144,
       83,   73,   83,   83,   83,  143,   83,    6,   83,   83,
      143,   83,   83,   22,   83,   83,   83,   21,   83,   83,
       83,   83,    0,    0,    0,    0,    0,   82,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    5,    6,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   10,    1,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   32,   34,   35,
       36,   36,   37,   36,   36,   38,   36,   39,   40,   36,
       36,   41,   42,   43,   44,   45,   36,   46,   36,   47,
       48,   49,   50,   51,   52,    1,   53,   54,   55,   56,

       57,   58,   59,   60,   61,   36,   62,   63,   64,   65,
       66,   67,   36,   68,   69,   70,   71,   72,   73,   74,
       75,   76,   77,   78,   79,   80,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[81] =
    {   0,
        1,    2,    3,    1,    1,    1,    2,    1,    4,    1,
        1,    1,    5,    1,    6,    1,    1,    1,    1,    1,
        1,    7,    7,    8,    1,    1,    1,    1,    1,    4,
        9,    9,    9,    9,    9,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   11,   10,    1,    4,    1,
        1,   10,   12,   12,    9,    9,    9,   12,   10,   10,
       10,   10,   10,   10,   13,   10,   10,   13,   10,   13,
       10,   13,   10,   13,   10,   10,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[568] =
    {   0,
        0,    0,  968,  969,   79,  969,   85,  939,   84,   92,
      938,   83,  916,  969,  969,  936,   79,  969,   81,   81,
       85,   97,  104,  938,  969,   95,  123,  108,  969,  924,
        0,  926,   99,  929,  969,  969,  931,  906,   63,  889,
      103,   83,  109,  110,   78,  903,   99,   92,  113,  898,
      113,  116,  897,  121,   72,  888,  127,  135,  969,  134,
      969,  969,  194,  969,  202,  211,  969,  180,  969,  188,
      217,  969,  221,  891,  890,  882,  969,  969,  969,  116,
      198,  969,  969,  969,  969,  969,  933,  969,  928,  213,
        0,  969,  230,  235,  277,  272,  178,  164,    0,  285,

      189,  187,  969,  919,  969,  254,  969,  969,  969,  918,
        0,  907,  873,  183,  894,  909,  900,  969,  165,  885,
      869,  881,  868,  883,  882,  869,  219,  862,  173,  246,
      864,  861,  864,  861,  867,  857,  860,  860,  225,  255,
      859,  858,  853,  856,  847,  862,  861,  260,  849,  862,
      261,  849,  187,  259,  853,  852,  845,  272,  843,  261,
      850,  848,  847,  969,  969,  321,    0,  330,  306,  844,
      841,  852,  969,  323,    0,  969,  969,  330,  969,    0,
      335,  338,  969,  327,  969,  969,  969,  969,    0,  839,
      872,  860,  836,  845,  828,  832,  844,  839,  827,  825,

      197,  225,  836,  838,  833,  833,  828,  820,  823,  820,
      828,  831,    0,  826,  816,  810,  824,  822,  822,  814,
      815,    0,  818,  815,  804,  806,  322,  803,  802,  810,
      796,  797,  810,  802,  808,  802,  791,  793,  795,  802,
      788,  786,  786,  786,  797,  796,  786,  790,  780,  793,
      795,  794,  783,  775,  357,  398,  329,  361,  328,  787,
      786,  783,  369,  444,  365,  381,  296,  331,  786,  802,
      802,  775,  777,  772,    0,  773,    0,  777,  764,  762,
      770,  759,  764,  758,  764,    0,    0,  768,  750,    0,
      756,  755,  752,  756,    0,  753,  756,  760,  760,  745,

      750,    0,    0,  761,  743,  757,  751,  742,  743,  755,
      744,  742,  752,  747,  742,  741,  735,  731,  731,  728,
      740,  730,  734,  739,  738,    0,  736,  733,  725,  730,
      717,    0,  717,  718,  728,  727,  386,    0,  436,  439,
      388,    0,    0,  462,  719,  351,    0,  969,  712,    0,
      734,  719,  726,  699,    0,    0,    0,    0,  704,  705,
      704,  703,  702,    0,    0,    0,  693,    0,  701,    0,
      699,    0,  686,  675,  661,  655,  647,  651,  652,  638,
      637,  627,  630,  629,  608,  622,  614,  616,  592,  582,
      586,    0,  594,  591,  592,  572,  581,  583,    0,    0,

      574,  584,  558,  565,    0,  538,  465,  506,    0,  487,
      542,  533,  559,  527,  523,  527,  518,  518,  531,    0,
        0,    0,    0,    0,    0,  529,    0,  528,  519,  512,
      514,  510,  514,  513,  520,    0,  515,  501,  512,    0,
      506,  511,    0,    0,    0,    0,    0,    0,  500,  500,
      493,  491,  483,  487,  399,  543,  407,  485,    0,  493,
      497,  495,  490,    0,    0,    0,    0,  485,  481,  487,
      476,  472,  468,  479,    0,  477,  480,  452,  458,    0,
      468,    0,  465,    0,  462,  416,    0,  410,  456,  441,
      453,  434,  425,    0,  437,  419,    0,    0,  416,    0,

        0,  425,  403,    0,    0,    0,    0,  415,  414,  431,
      398,    0,  383,    0,  379,  371,    0,    0,    0,  369,
      374,    0,  358,  371,  354,    0,  349,    0,  329,  338,
        0,  278,  238,    0,  260,  217,  208,    0,  190,   88,
       40,  489,  505,  421,  438,  506,  516,  969,  518,  969,
      601,  614,  621,  631,  641,  654,  661,  667,  679,  686,
      696,  703,  715,  728,  741,  753,  765
    } ;

static yyconst short int yy_def[568] =
    {   0,
      550,    1,  550,  550,  550,  550,  550,  550,  551,  550,
      550,  550,  552,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  553,
      553,  553,  553,  553,  550,  550,  550,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  551,  550,  554,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  552,
      555,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      556,  550,  550,  550,  550,  550,  550,  550,  557,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      553,  553,  553,  551,  552,  553,  553,  550,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  550,  550,  551,  558,  550,  559,  550,
      550,  550,  550,  552,  560,  550,  550,  550,  550,  556,
      550,  550,  550,  557,  550,  550,  550,  550,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  551,  551,  559,  550,  561,  550,
      550,  550,  552,  552,  550,  550,  550,  550,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  551,  256,  550,  550,
      559,  562,  563,  550,  550,  552,  264,  550,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  559,  559,  563,  550,
      550,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  559,  408,  564,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  553,  553,  553,  559,  564,  564,  564,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  553,

      553,  553,  553,  553,  553,  553,  553,  553,  564,  553,
      553,  553,  553,  553,  553,  553,  553,  553,  553,  564,
      553,  553,  553,  553,  553,  565,  553,  553,  553,  553,
      565,  553,  553,  553,  553,  553,  553,  553,  553,  553,
      553,  553,  550,  566,  566,  567,  550,  550,  567,    0,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550
    } ;

static yyconst short int yy_nxt[1050] =
    {   0,
        4,    5,    6,    7,    7,    7,    5,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   31,   31,   31,   31,   33,   31,   31,
       31,   31,   31,   31,   34,   31,   31,   35,    4,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   31,   48,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   31,   31,   31,   59,   60,   61,   62,
       63,   64,   65,   65,   65,   63,   65,   64,   66,   66,
       66,   65,   69,   71,   78,   83,   88,  542,   71,   85,

       89,   72,   90,   90,   90,   91,   84,  114,   86,   87,
       79,  115,   92,   73,   73,   73,   93,  120,   94,   94,
       95,  104,  105,   93,  106,  100,  100,  100,  173,  106,
       96,  156,   70,  121,   97,  109,  110,   96,  116,  127,
       98,  101,   99,  136,  541,  137,  157,  102,  128,   74,
      107,  108,  141,   96,   75,  123,  139,  142,   76,   97,
       96,  164,  124,  140,   81,  125,  101,   98,  126,  143,
       99,  129,  133,  130,  102,  134,  131,  135,  144,  146,
      152,  153,  132,  148,  147,  149,  150,  159,   69,  161,
      154,   69,  160,  155,  162,   63,   64,   65,   65,   65,

       63,  183,  163,   65,   64,   65,   65,   65,   65,  166,
      166,  165,   65,   64,   66,   66,   66,   65,   71,  174,
      174,  183,  168,   71,  185,  193,  183,  168,   70,  169,
      540,   70,  185,  205,   90,   90,   90,  194,   73,   73,
       73,  206,   73,   73,   73,  239,  178,  179,  183,  185,
      179,   90,   90,   90,   93,  106,   94,   94,   95,  185,
      106,  167,  240,  178,  179,  280,  281,  179,   96,  178,
      179,  175,   97,  539,   74,  179,  202,  282,   98,   75,
      218,  203,  187,   76,  538,  283,  178,  179,  181,  219,
      181,   96,  179,  182,  182,  182,   93,   97,   95,   95,

       95,  207,  537,  536,   93,   98,  100,  100,  100,  220,
       96,  241,  230,  235,  258,  208,  209,  221,   96,  236,
      231,  250,  101,  251,  222,  232,  242,  246,  102,   69,
      237,  168,  247,   96,  535,  173,  168,  258,  169,  348,
      248,   96,  255,  255,  263,  263,  265,  101,  265,  341,
      341,  266,  266,  266,  259,  102,  182,  182,  182,  182,
      182,  182,  339,  173,  267,   69,  348,  339,  348,   70,
      268,   81,  179,  342,  306,  179,  307,  259,  337,  337,
      308,  173,  340,  340,  340,  309,  266,  266,  266,  267,
      346,  346,  534,  348,   69,  179,  258,  268,  533,   81,

      179,  342,  266,  266,  266,   70,   69,  258,  488,  407,
      407,  488,  532,  488,  530,  179,  488,   81,  179,  338,
      338,  338,  545,  529,  258,  528,  527,  545,  338,  338,
      338,  338,  338,  526,   70,  525,  259,  339,  179,  545,
      339,  524,  339,  179,  545,  339,   70,  259,  523,  522,
      338,  338,  338,  338,  338,  338,  173,  340,  340,  340,
      340,  340,  340,  410,  259,  347,  347,  347,  410,  521,
      520,  519,  518,  258,  347,  347,  347,  347,  347,  489,
      517,  516,  489,   73,   73,   73,  455,  455,  410,  515,
      543,  514,   81,  410,  513,  543,  347,  347,  347,  347,

      347,  347,  544,  512,  511,  510,  543,  547,   73,   73,
       73,  543,  547,  259,  258,  509,  508,  547,  544,  547,
      548,  507,  547,  506,  547,  505,  504,  456,  456,  456,
      548,  503,  548,  502,  501,  500,  456,  456,  456,  456,
      456,  499,  498,  497,  496,  495,  494,  493,  492,  491,
      490,  485,  484,  483,  259,  482,  481,  480,  456,  456,
      456,  456,  456,  456,  486,  486,  486,  479,  478,  477,
      476,  475,  474,  486,  486,  486,  486,  486,  473,  472,
      471,  470,  469,  468,  467,  466,  465,  464,  463,  462,
      461,  460,  459,  458,  457,  486,  486,  486,  486,  486,

      486,   68,   68,  454,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   80,   80,  453,   80,  452,   80,
       80,   80,   80,   80,   80,   80,   80,  111,  111,  111,
      111,  111,  111,  111,   68,   68,  451,   68,  450,  449,
      448,  447,   68,   68,   80,   80,  446,   80,  445,  444,
      443,  442,   80,   80,  180,  180,  441,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  184,  184,  184,
      440,  439,  184,  256,  256,  256,  438,  437,  256,  257,
      257,  436,  257,  257,  257,  257,  257,  257,  257,  257,
      257,  257,  264,  264,  264,  435,  434,  264,  257,  257,

      257,  433,  257,  432,  431,  430,  257,  257,  257,  408,
      408,  408,  429,  428,  408,  409,  409,  427,  409,  409,
      409,  409,  409,  409,  409,  409,  409,  409,  487,  487,
      426,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  531,  531,  425,  531,  531,  531,  531,  531,  531,
      531,  531,  531,  531,  546,  424,  423,  422,  421,  420,
      419,  546,  546,  546,  546,  546,  549,  418,  417,  416,
      549,  549,  549,  549,  549,  549,  549,  549,  415,  414,
      413,  412,  411,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,

      389,  388,  387,  386,  385,  384,  383,  382,  381,  380,
      379,  378,  377,  376,  375,  374,  373,  372,  371,  370,
      369,  368,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  345,  344,  343,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  312,  311,
      310,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  279,  278,  277,  276,  275,  274,  273,

      272,  271,  270,  269,  262,  261,  260,  254,  253,  252,
      249,  245,  244,  243,  238,  234,  233,  229,  228,  227,
      226,  225,  224,  223,  217,  216,  215,  214,  213,  212,
      211,  210,  204,  201,  200,  199,  198,  197,  196,  195,
      192,  191,   81,  190,  189,  188,  186,  177,  176,  172,
      171,  170,  158,  151,  145,  138,  122,  119,  118,  117,
      113,  112,  103,   82,   81,   77,   67,  550,    3,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550
    } ;

static yyconst short int yy_chk[1050] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    7,    7,    7,    7,
        7,    7,    9,   10,   12,   17,   20,  541,   10,   19,

       20,   10,   20,   20,   20,   21,   17,   33,   19,   19,
       12,   33,   21,   10,   10,   10,   22,   39,   22,   22,
       22,   26,   26,   23,   27,   23,   23,   23,   80,   27,
       22,   55,    9,   39,   22,   28,   28,   23,   33,   42,
       22,   23,   22,   45,  540,   45,   55,   23,   42,   10,
       27,   27,   48,   22,   10,   41,   47,   48,   10,   22,
       23,   60,   41,   47,   80,   41,   23,   22,   41,   49,
       22,   43,   44,   43,   23,   44,   43,   44,   49,   51,
       54,   54,   43,   52,   51,   52,   52,   57,   68,   58,
       54,  114,   57,   54,   58,   63,   63,   63,   63,   63,

       63,   98,   58,   65,   65,   65,   65,   65,   65,   70,
       70,   60,   66,   66,   66,   66,   66,   66,   71,   81,
       81,   97,   73,   71,  102,  119,   98,   73,   68,   73,
      539,  114,  101,  129,   90,   90,   90,  119,   71,   71,
       71,  129,   73,   73,   73,  153,   90,   90,   97,  102,
       90,   93,   93,   93,   94,  106,   94,   94,   94,  101,
      106,   70,  153,   93,   93,  201,  201,   93,   94,   90,
       90,   81,   94,  537,   71,   90,  127,  202,   94,   71,
      139,  127,  106,   71,  536,  202,   93,   93,   96,  139,
       96,   94,   93,   96,   96,   96,   95,   94,   95,   95,

       95,  130,  535,  533,  100,   94,  100,  100,  100,  140,
       95,  154,  148,  151,  169,  130,  130,  140,  100,  151,
      148,  160,  100,  160,  140,  148,  154,  158,  100,  166,
      151,  168,  158,   95,  532,  174,  168,  257,  168,  267,
      158,  100,  166,  166,  174,  174,  178,  100,  178,  259,
      259,  178,  178,  178,  169,  100,  181,  181,  181,  182,
      182,  182,  258,  346,  184,  255,  267,  258,  268,  166,
      184,  174,  182,  259,  227,  182,  227,  257,  255,  255,
      227,  263,  258,  258,  258,  227,  265,  265,  265,  184,
      263,  263,  530,  268,  337,  182,  341,  184,  529,  346,

      182,  259,  266,  266,  266,  255,  256,  455,  457,  341,
      341,  488,  527,  457,  525,  266,  488,  263,  266,  256,
      256,  256,  544,  524,  486,  523,  521,  544,  256,  256,
      256,  256,  256,  520,  337,  516,  341,  339,  266,  545,
      340,  515,  339,  266,  545,  340,  256,  455,  513,  511,
      256,  256,  256,  256,  256,  256,  264,  339,  339,  339,
      340,  340,  340,  344,  486,  264,  264,  264,  344,  510,
      509,  508,  503,  407,  264,  264,  264,  264,  264,  457,
      502,  499,  488,  344,  344,  344,  407,  407,  410,  496,
      542,  495,  264,  410,  493,  542,  264,  264,  264,  264,

      264,  264,  542,  492,  491,  490,  543,  546,  410,  410,
      410,  543,  546,  407,  408,  489,  485,  547,  543,  549,
      546,  483,  547,  481,  549,  479,  478,  408,  408,  408,
      547,  477,  549,  476,  474,  473,  408,  408,  408,  408,
      408,  472,  471,  470,  469,  468,  463,  462,  461,  460,
      458,  454,  453,  452,  408,  451,  450,  449,  408,  408,
      408,  408,  408,  408,  456,  456,  456,  442,  441,  439,
      438,  437,  435,  456,  456,  456,  456,  456,  434,  433,
      432,  431,  430,  429,  428,  426,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  456,  456,  456,  456,  456,

      456,  551,  551,  406,  551,  551,  551,  551,  551,  551,
      551,  551,  551,  551,  552,  552,  404,  552,  403,  552,
      552,  552,  552,  552,  552,  552,  552,  553,  553,  553,
      553,  553,  553,  553,  554,  554,  402,  554,  401,  398,
      397,  396,  554,  554,  555,  555,  395,  555,  394,  393,
      391,  390,  555,  555,  556,  556,  389,  556,  556,  556,
      556,  556,  556,  556,  556,  556,  556,  557,  557,  557,
      388,  387,  557,  558,  558,  558,  386,  385,  558,  559,
      559,  384,  559,  559,  559,  559,  559,  559,  559,  559,
      559,  559,  560,  560,  560,  383,  382,  560,  561,  561,

      561,  381,  561,  380,  379,  378,  561,  561,  561,  562,
      562,  562,  377,  376,  562,  563,  563,  375,  563,  563,
      563,  563,  563,  563,  563,  563,  563,  563,  564,  564,
      374,  564,  564,  564,  564,  564,  564,  564,  564,  564,
      564,  565,  565,  373,  565,  565,  565,  565,  565,  565,
      565,  565,  565,  565,  566,  371,  369,  367,  363,  362,
      361,  566,  566,  566,  566,  566,  567,  360,  359,  354,
      567,  567,  567,  567,  567,  567,  567,  567,  353,  352,
      351,  349,  345,  336,  335,  334,  333,  331,  330,  329,
      328,  327,  325,  324,  323,  322,  321,  320,  319,  318,

      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  301,  300,  299,  298,  297,  296,
      294,  293,  292,  291,  289,  288,  285,  284,  283,  282,
      281,  280,  279,  278,  276,  274,  273,  272,  271,  270,
      269,  262,  261,  260,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  226,  225,  224,  223,  221,  220,  219,  218,  217,
      216,  215,  214,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  200,  199,  198,  197,  196,  195,  194,

      193,  192,  191,  190,  172,  171,  170,  163,  162,  161,
      159,  157,  156,  155,  152,  150,  149,  147,  146,  145,
      144,  143,  142,  141,  138,  137,  136,  135,  134,  133,
      132,  131,  128,  126,  125,  124,  123,  122,  121,  120,
      117,  116,  115,  113,  112,  110,  104,   89,   87,   76,
       75,   74,   56,   53,   50,   46,   40,   38,   37,   34,
       32,   30,   24,   16,   13,   11,    8,    3,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,

      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550,  550,
      550,  550,  550,  550,  550,  550,  550,  550,  550
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "xp-lexer.l"
#define INITIAL 0
#line 2 "xp-lexer.l"

/*  Copyright (C) 1989-1991 James A. Roskind, All rights reserved.
    This lexer description was written by James A.  Roskind.  Copying
    of  this  file, as a whole, is permitted providing this notice is
    intact  and  applicable   in   all   complete   copies.    Direct
    translations  as a whole to other lexer generator input languages
    (or lexical description languages)  is  permitted  provided  that
    this  notice  is  intact and applicable in all such copies, along
    with a disclaimer that  the  contents  are  a  translation.   The
    reproduction  of derived files or text, such as modified versions
    of this file, or the output of scanner generators, is  permitted,
    provided   the  resulting  work  includes  the  copyright  notice
    "Portions Copyright (c) 1989, 1990 James  A.   Roskind".  Derived
    products  must  also  provide  the notice "Portions Copyright (c)
    1989, 1990 James A.  Roskind" in  a  manner  appropriate  to  the
    utility,   and  in  keeping  with  copyright  law  (e.g.:  EITHER
    displayed when first invoked/executed; OR displayed  continuously
    on  display terminal; OR via placement in the object code in form
    readable in a printout, with or near the title of the work, or at
    the end of the file).  No royalties, licenses or  commissions  of
    any  kind  are  required  to copy this file, its translations, or
    derivative products, when the copies are made in compliance  with
    this  notice.  Persons  or  corporations  that  do make copies in
    compliance  with  this  notice  may  charge  whatever  price   is
    agreeable  to  a buyer, for such copies or derivative works. THIS
    FILE IS PROVIDED ``AS IS'' AND WITHOUT  ANY  EXPRESS  OR  IMPLIED
    WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES
    OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

    James A. Roskind
    Independent Consultant
    516 Latania Palm Drive
    Indialantic FL, 32903
    (407)729-4348
    jar@hq.ileaf.com
    or ...!uunet!leafusa!jar

    ---end of copyright notice---

*/

/*

Comment  removal  must  be done during the lexing, as context (such as
enclosure in string literals) must be  observed.   For  this  cut-down
lexer,  we  will  assume that comments have been removed (don't assume
this if you are writing a compiler or browser!).


For each IDENTIFIER like string that is found,  there  are  several
distinct interpretations that can be applied:

1)  The  preprocessor  may  interpret  the  string as a "keyword" in a
directive (eg: "pragma" or "include", "defined").

2) The parser may interpret the string as a keyword. (eg: "int").

3) Both parser and preprocessor may interpret the string as a  keyword
(eg: "if").

Since  this  file  is based on source that actually lexically analyses
text for both preprocessing and parsing, macro definitions  were  used
throughout.   The macro definitions supplied here have been customized
to a C++ parse only, and  all  preprocessor  keywords  are  passed  as
IDENTIFIER  or  TYPEDEFname.   Also, since there is no symbol table to
interrogate to decide whether a string  is  a  TYPEDEFname,  I  simply
assume  that  any  identifier beginning with an upper case letter is a
TYPEDEFname.  This hack  should  allow  you  to  check  out  how  code
segments  are  parsed  using my grammar.  Unfortunately, if you really
want to parse major league code, you have to write a symbol table, and
maintain appropriate scoping information.

*/


/* Included code before lex code */
/*************** Includes and Defines *****************************/


char *CurrentIdent, *CurrentConst ;
int FoundLBrace=0, FoundRBrace=0 ;

#define YYSTYPE char *
#include "xp-t.tab.h" /* YACC generated definitions based on C++ grammar */
#include "xp-lexer.h"
#include "xp-extn.h"


#define WHITE_RETURN(x) if ( shouldprint ) strcat(OutBuf,prevtoken) ; \
			strcpy(prevtoken,x);

/*
#define NEW_LINE_RETURN() CurrentLine++; \
			  if ( shouldprint ) strcat(OutBuf,prevtoken); \
			  strcpy(prevtoken,yytext);
*/
			  

#define PA_KEYWORD_RETURN(x)   RETURN_VAL(x)  /* standard C PArser Keyword */
#define CPP_KEYWORD_RETURN(x)  PA_KEYWORD_RETURN(x)  /* C++ keyword */
#define PPPA_KEYWORD_RETURN(x) RETURN_VAL(x)  /* both PreProcessor and PArser keyword */
#define PP_KEYWORD_RETURN(x)   IDENTIFIER_RETURN()

/*
#define IDENTIFIER_RETURN() RETURN_VAL(isaTYPE(yytext)?TYPEDEFname:IDENTIFIER)
*/

#define IDENTIFIER_RETURN() CurrentIdent = (char *)malloc((strlen(yytext)+1)*sizeof(char)); \
		      	    strcpy(CurrentIdent,yytext);  \
			    yylval = CurrentIdent ; \
			    if (shouldprint) strcat(OutBuf,prevtoken); \
			    strcpy(prevtoken,yytext) ; \
			    if ( FoundLBrace ) {PushStack() ;FoundLBrace=0;}\
			    else if ( FoundRBrace ){PopStack();FoundRBrace=0;}\
			    return(isaTYPE(yytext)?TYPEDEFname:IDENTIFIER);

#define PPOP_RETURN(x)       RETURN_VAL((int)*yytext) /* PreProcess and Parser operator */
#define NAMED_PPOP_RETURN(x) /* error: PreProcessor ONLY operator;  Do nothing */
#define ASCIIOP_RETURN(x)    RETURN_VAL((int)*yytext) /* a single character operator */
#define LBRACE_RETURN(x)     CurrentScope++ ; \
			     RETURN_VAL((int)*yytext) ;
#define RBRACE_RETURN(x)     CurrentScope-- ; \
			     RETURN_VAL((int)*yytext) ;

#define NAMEDOP_RETURN(x)    RETURN_VAL(x)            /* a multichar operator, with a name */

/* #define NUMERICAL_RETURN(x) RETURN_VAL(x)         * some sort of constant */

#define NUMERICAL_RETURN(x) CurrentConst = (char *)malloc((strlen(yytext)+1)*sizeof(char)); \
		      	    strcpy(CurrentConst,yytext);  \
			    yylval = CurrentConst ; \
			    if (shouldprint) strcat(OutBuf,prevtoken); \
			    strcpy(prevtoken,yytext) ; \
			    if ( FoundLBrace ) {PushStack() ;FoundLBrace=0;}\
			    else if ( FoundRBrace ){PopStack();FoundRBrace=0;}\
			    return(x);
			    

#define LITERAL_RETURN(x)   RETURN_VAL(x)            /* a string literal */

#define RETURN_VAL(x) 	yylval = yytext; \
			if ( shouldprint ) strcat(OutBuf,prevtoken); \
			strcpy(prevtoken,yytext) ; \
			if ( FoundLBrace ) {PushStack() ;FoundLBrace=0;}\
			else if ( FoundRBrace ){PopStack();FoundRBrace=0;}\
		        if ( prevtoken[0] == '{' ) FoundLBrace=1; \
		        else if ( prevtoken[0] == '}' ) FoundRBrace=1; \
			return(x);

#define RETURN_VAL_NOPRINT(x) 	yylval = yytext; return(x);

#define CHARM_KEYWORD_RETURN(x)	RETURN_VAL_NOPRINT(x)

#ifdef yywrap
#undef yywrap
#endif


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 197 "xp-lexer.l"



	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 551 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 969 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 199 "xp-lexer.l"
{ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 201 "xp-lexer.l"
{
			WHITE_RETURN(" ");
			}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 205 "xp-lexer.l"
{
			WHITE_RETURN(" ");
			}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 210 "xp-lexer.l"
{
			NEW_LINE_RETURN();
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 214 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(CHARE);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 215 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(ACCUMULATOR);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 216 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(MONOTONIC);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 217 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(READONLY);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 218 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(WRITEONCE);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 220 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(MESSAGE);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 221 "xp-lexer.l"
{	if ( CheckCharmName() ) {
				CHARM_KEYWORD_RETURN(HANDLE);
			}
			else {
				IDENTIFIER_RETURN() ;
			}
		    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 228 "xp-lexer.l"
{	if ( CheckCharmName() ) {
				CHARM_KEYWORD_RETURN(GROUP);
				/* handle and group are processed same way */
			}
			else {
				IDENTIFIER_RETURN() ;
			}
		    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 236 "xp-lexer.l"
{if ( shouldprint ) strcat(OutBuf,prevtoken); 
		     strcpy(prevtoken,"public") ;	
		     CHARM_KEYWORD_RETURN(ENTRY);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 239 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(DOUBLEARROW);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 240 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(DOUBLEARROW);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 241 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(ALL_NODES);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 242 "xp-lexer.l"
{CHARM_KEYWORD_RETURN(LOCAL);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 243 "xp-lexer.l"
{ FoundVarSize = TRUE ; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 244 "xp-lexer.l"
{CPP_KEYWORD_RETURN(NEWCHARE);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 245 "xp-lexer.l"
{CPP_KEYWORD_RETURN(NEWGROUP);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 246 "xp-lexer.l"
{CPP_KEYWORD_RETURN(NEW);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 247 "xp-lexer.l"
{CPP_KEYWORD_RETURN(NEW);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 250 "xp-lexer.l"
{PA_KEYWORD_RETURN(AUTO);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 251 "xp-lexer.l"
{PA_KEYWORD_RETURN(BREAK);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 252 "xp-lexer.l"
{PA_KEYWORD_RETURN(CASE);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 253 "xp-lexer.l"
{PA_KEYWORD_RETURN(CHAR);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 254 "xp-lexer.l"
{PA_KEYWORD_RETURN(CONST);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 255 "xp-lexer.l"
{PA_KEYWORD_RETURN(CONTINUE);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 256 "xp-lexer.l"
{PA_KEYWORD_RETURN(DEFAULT);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 257 "xp-lexer.l"
{PP_KEYWORD_RETURN(DEFINE);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 258 "xp-lexer.l"
{PP_KEYWORD_RETURN(OPDEFINED);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 259 "xp-lexer.l"
{PA_KEYWORD_RETURN(DO);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 260 "xp-lexer.l"
{PA_KEYWORD_RETURN(DOUBLE);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 261 "xp-lexer.l"
{PP_KEYWORD_RETURN(ELIF);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 262 "xp-lexer.l"
{PPPA_KEYWORD_RETURN(ELSE);}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 263 "xp-lexer.l"
{PP_KEYWORD_RETURN(ENDIF);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 264 "xp-lexer.l"
{PA_KEYWORD_RETURN(ENUM);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 265 "xp-lexer.l"
{PP_KEYWORD_RETURN(ERROR);}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 266 "xp-lexer.l"
{PA_KEYWORD_RETURN(EXTERN);}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 267 "xp-lexer.l"
{PA_KEYWORD_RETURN(FLOAT);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 268 "xp-lexer.l"
{PA_KEYWORD_RETURN(FOR);}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 269 "xp-lexer.l"
{PA_KEYWORD_RETURN(GOTO);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 270 "xp-lexer.l"
{PPPA_KEYWORD_RETURN(IF);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 271 "xp-lexer.l"
{PP_KEYWORD_RETURN(IFDEF);}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 272 "xp-lexer.l"
{PP_KEYWORD_RETURN(IFNDEF);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 273 "xp-lexer.l"
{PP_KEYWORD_RETURN(INCLUDE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 274 "xp-lexer.l"
{PA_KEYWORD_RETURN(INT);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 275 "xp-lexer.l"
{PP_KEYWORD_RETURN(LINE);}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 276 "xp-lexer.l"
{PA_KEYWORD_RETURN(LONG);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 277 "xp-lexer.l"
{PP_KEYWORD_RETURN(PRAGMA);}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 278 "xp-lexer.l"
{if (ptrdiff_is_predefined)
                       { PA_KEYWORD_RETURN(PTRDIFF_TOKEN); }
                     else { IDENTIFIER_RETURN(); } }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 281 "xp-lexer.l"
{PA_KEYWORD_RETURN(REGISTER);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 282 "xp-lexer.l"
{PA_KEYWORD_RETURN(RETURN);}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 283 "xp-lexer.l"
{PA_KEYWORD_RETURN(SHORT);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 284 "xp-lexer.l"
{PA_KEYWORD_RETURN(SIGNED);}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 285 "xp-lexer.l"
{PA_KEYWORD_RETURN(SIZEOF);}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 286 "xp-lexer.l"
{PA_KEYWORD_RETURN(STATIC);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 287 "xp-lexer.l"
{PA_KEYWORD_RETURN(STRUCT);}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 288 "xp-lexer.l"
{PA_KEYWORD_RETURN(SWITCH);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 289 "xp-lexer.l"
{PA_KEYWORD_RETURN(TYPEDEF);}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 290 "xp-lexer.l"
{PP_KEYWORD_RETURN(UNDEF);}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 291 "xp-lexer.l"
{PA_KEYWORD_RETURN(UNION);}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 292 "xp-lexer.l"
{PA_KEYWORD_RETURN(UNSIGNED);}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 293 "xp-lexer.l"
{PA_KEYWORD_RETURN(VOID);}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 294 "xp-lexer.l"
{PA_KEYWORD_RETURN(VOLATILE);}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 295 "xp-lexer.l"
{PA_KEYWORD_RETURN(WHILE);}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 296 "xp-lexer.l"
{ if (wchar_is_predefined) {
                         PA_KEYWORD_RETURN(WCHAR_TOKEN);
                      } else {
                         IDENTIFIER_RETURN();
                    }}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 301 "xp-lexer.l"
{ PA_KEYWORD_RETURN(__WCHAR_TOKEN); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 303 "xp-lexer.l"
{CPP_KEYWORD_RETURN(CLASS);}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 304 "xp-lexer.l"
{CPP_KEYWORD_RETURN(DELETE);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 305 "xp-lexer.l"
{CPP_KEYWORD_RETURN(FRIEND);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 306 "xp-lexer.l"
{CPP_KEYWORD_RETURN(INLINE);}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 307 "xp-lexer.l"
{CPP_KEYWORD_RETURN(UNDERSCORE_INLINE);}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 308 "xp-lexer.l"
{CPP_KEYWORD_RETURN(NEW);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 309 "xp-lexer.l"
{CPP_KEYWORD_RETURN(OPERATOR);}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 310 "xp-lexer.l"
{CPP_KEYWORD_RETURN(OVERLOAD);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 311 "xp-lexer.l"
{CPP_KEYWORD_RETURN(PROTECTED);}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 312 "xp-lexer.l"
{CPP_KEYWORD_RETURN(PRIVATE);}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 313 "xp-lexer.l"
{CPP_KEYWORD_RETURN(PUBLIC);}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 314 "xp-lexer.l"
{CPP_KEYWORD_RETURN(THIS);}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 315 "xp-lexer.l"
{CPP_KEYWORD_RETURN(VIRTUAL);}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 319 "xp-lexer.l"
{
			/* Find the identifier */
			char str[128] ;
			char *ident = str ;
			char *ptr1 = strchr(yytext,'(') ;
			ptr1++ ;
			while ( *ptr1==' ' || *ptr1=='\t' )
				ptr1++ ;			
			while ( *ptr1!=' ' && *ptr1!='\t' && *ptr1!=')' )
				*(ident++) = *(ptr1++) ;
			*ident = '\0' ;

			strcpy(yytext,"_CK_func_") ;
			strcat(yytext,str) ;

                     	IDENTIFIER_RETURN();
			}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 339 "xp-lexer.l"
{ IDENTIFIER_RETURN(); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 341 "xp-lexer.l"
{NUMERICAL_RETURN(INTEGERconstant);}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 342 "xp-lexer.l"
{NUMERICAL_RETURN(OCTALconstant);}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 343 "xp-lexer.l"
{NUMERICAL_RETURN(HEXconstant);}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 344 "xp-lexer.l"
{NUMERICAL_RETURN(FLOATINGconstant);}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 347 "xp-lexer.l"
{
			NUMERICAL_RETURN(CHARACTERconstant);
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 352 "xp-lexer.l"
{
			LITERAL_RETURN(STRINGliteral);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 358 "xp-lexer.l"
{PPOP_RETURN(LP);}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 359 "xp-lexer.l"
{PPOP_RETURN(RP);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 360 "xp-lexer.l"
{PPOP_RETURN(COMMA);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 361 "xp-lexer.l"
{NAMED_PPOP_RETURN('#') ;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 362 "xp-lexer.l"
{NAMED_PPOP_RETURN(POUNDPOUND);}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 364 "xp-lexer.l"
{ LBRACE_RETURN(LC); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 365 "xp-lexer.l"
{ RBRACE_RETURN(RC); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 367 "xp-lexer.l"
{ASCIIOP_RETURN(LB);}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 368 "xp-lexer.l"
{ASCIIOP_RETURN(RB);}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 369 "xp-lexer.l"
{ASCIIOP_RETURN(DOT);}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 370 "xp-lexer.l"
{ASCIIOP_RETURN(AND);}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 371 "xp-lexer.l"
{ASCIIOP_RETURN(STAR);}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 372 "xp-lexer.l"
{ASCIIOP_RETURN(PLUS);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 373 "xp-lexer.l"
{ASCIIOP_RETURN(MINUS);}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 374 "xp-lexer.l"
{ASCIIOP_RETURN(NEGATE);}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 375 "xp-lexer.l"
{ASCIIOP_RETURN(NOT);}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 376 "xp-lexer.l"
{ASCIIOP_RETURN(DIV);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 377 "xp-lexer.l"
{ASCIIOP_RETURN(MOD);}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 378 "xp-lexer.l"
{ASCIIOP_RETURN(LT);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 379 "xp-lexer.l"
{ASCIIOP_RETURN(GT);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 380 "xp-lexer.l"
{ASCIIOP_RETURN(XOR);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 381 "xp-lexer.l"
{ASCIIOP_RETURN(PIPE);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 382 "xp-lexer.l"
{ASCIIOP_RETURN(QUESTION);}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 383 "xp-lexer.l"
{ASCIIOP_RETURN(COLON);}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 384 "xp-lexer.l"
{ASCIIOP_RETURN(SEMICOLON);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 385 "xp-lexer.l"
{ASCIIOP_RETURN(ASSIGN);}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 387 "xp-lexer.l"
{NAMEDOP_RETURN(DOTstar);}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 388 "xp-lexer.l"
{NAMEDOP_RETURN(CLCL);}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 389 "xp-lexer.l"
{NAMEDOP_RETURN(ARROW);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 390 "xp-lexer.l"
{NAMEDOP_RETURN(ARROWstar);}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 391 "xp-lexer.l"
{NAMEDOP_RETURN(ICR);}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 392 "xp-lexer.l"
{NAMEDOP_RETURN(DECR);}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 393 "xp-lexer.l"
{NAMEDOP_RETURN(LS);}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 394 "xp-lexer.l"
{NAMEDOP_RETURN(RS);}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 395 "xp-lexer.l"
{NAMEDOP_RETURN(LE);}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 396 "xp-lexer.l"
{NAMEDOP_RETURN(GE);}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 397 "xp-lexer.l"
{NAMEDOP_RETURN(EQ);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 398 "xp-lexer.l"
{NAMEDOP_RETURN(NE);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 399 "xp-lexer.l"
{NAMEDOP_RETURN(ANDAND);}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 400 "xp-lexer.l"
{NAMEDOP_RETURN(OROR);}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 401 "xp-lexer.l"
{NAMEDOP_RETURN(MULTassign);}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 402 "xp-lexer.l"
{NAMEDOP_RETURN(DIVassign);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 403 "xp-lexer.l"
{NAMEDOP_RETURN(MODassign);}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 404 "xp-lexer.l"
{NAMEDOP_RETURN(PLUSassign);}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 405 "xp-lexer.l"
{NAMEDOP_RETURN(MINUSassign);}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 406 "xp-lexer.l"
{NAMEDOP_RETURN(LSassign);}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 407 "xp-lexer.l"
{NAMEDOP_RETURN(RSassign);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 408 "xp-lexer.l"
{NAMEDOP_RETURN(ANDassign);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 409 "xp-lexer.l"
{NAMEDOP_RETURN(ERassign);}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 410 "xp-lexer.l"
{NAMEDOP_RETURN(ORassign);}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 411 "xp-lexer.l"
{NAMEDOP_RETURN(ELLIPSIS);}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 413 "xp-lexer.l"
{ int i=0,j=0;
                                                  char temp[MAX_NAME_LENGTH];

						  strcat(OutBuf,prevtoken) ;
						  strcpy(prevtoken,"") ;
						  strcat(OutBuf,yytext) ;
						  FLUSHBUF() ;

                                                  while ((yytext[i]<'0')||
                                                         (yytext[i]>'9'))
                                                        i++;
                                                  while ((yytext[i]>='0') &&
                                                         (yytext[i]<='9'))
                                                        temp[j++]=yytext[i++];
                                                  temp[j]='\0';
                                                  CurrentLine = atoi(temp)-1;
                                                  while (yytext[i]!='\"')
                                                        i++;

					  	  /* remove double quote */
						  j = yyleng-1 ;
						  while ( yytext[j] != '"' )
							j-- ;
                                                  yytext[j]='\0';
                                                  strcpy(CurrentFileName,
                                                                yytext+i+1);
                                                }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 441 "xp-lexer.l"
{ /* #line used by SP */
						
						int i=0,j=0;     
                                                char temp[MAX_NAME_LENGTH];
						
						strcat(OutBuf,prevtoken) ;
						strcpy(prevtoken,"") ;
						strcat(OutBuf,yytext) ;
						FLUSHBUF() ;

						/* Skip to the line number */
						while ((yytext[i]<'0')||
						       (yytext[i]>'9'))
						     i++;
						
						/* Copy the line number */
						while ((yytext[i]>='0') &&
						       (yytext[i]<='9'))
						     temp[j++]=yytext[i++];
						temp[j]='\0';
						
						/* Now place it in 
						   'CurrentLine */
						CurrentLine = atoi(temp)-1;
					   }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 468 "xp-lexer.l"
{ /* #pragma when ... */

		/* This pragma is used to specify dependences between EPs */
		    char * rest ;
		    if ( MakeGraph ) {
			rest = strchr(yytext,'n') ;
			rest++ ;
			fprintf(graphfile,"WHEN %s %s : %s\n",CurrentChare,
						CurrentEP, rest) ;
		    }
		}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 481 "xp-lexer.l"
{ /* #pragma used by G++: copy to output */
					strcat(OutBuf,prevtoken) ;
					strcpy(prevtoken,"") ;
					strcat(OutBuf,yytext) ;
					FLUSHBUF() ;
				}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 488 "xp-lexer.l"
{ /* #file stuff used in nCUBE CC */
					strcat(OutBuf,prevtoken) ;
					strcpy(prevtoken,"") ;
					strcat(OutBuf,yytext) ;
					FLUSHBUF() ;
				}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 495 "xp-lexer.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 551 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 551 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 550);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p = yytext_ptr + offset;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 495 "xp-lexer.l"


yywrap() { return(1); }

/* I won't bother to provide any error recovery. I won't  even  handle
unknown characters */

/*******************************************************************
int isaTYPE(string)
char * string;
{
    *  We  should  really  be  maintaining  a  symbol  table,  and be
    carefully keeping track of what the current scope is  (or  in  the
    case  of  "rescoped"  stuff,  what  scope  to  look in). Since the
    grammar is not annotated with  actions  to  track  transitions  to
    various  scopes,  and  there  is no symbol table, we will supply a
    hack to allow folks to test  the  grammar  out.   THIS  IS  NOT  A
    COMPLETE IMPLEMENTATION!!!! *

    if ( strncmp(string,"NULL",4) == 0 )
	return 0 ;

    return ('A' <= string[0] && 'Z' >= string[0]);
}
********************************************************************/

int isaTYPE(string)
char *string ;
{
	int i ;

	if ( StructScope )
		return FALSE ;

	if ( !FoundGlobalScope || GlobalStack == NULL ) {
		for ( i=TotalSyms-1; i>=0; i-- ) {  /* from inner to outer */
			if ( strcmp(string,SymTable[i].name) == 0 ) {
				strcpy(CurrentTypedef,string) ;
				return TRUE ;
			}
		}
	}
	else {
		for ( i=0; i<GlobalStack->TotalSyms; i++ ) {  
			/* search global state */
			if ( strcmp(string,SymTable[i].name) == 0 ) {
				strcpy(CurrentTypedef,string) ;
				return TRUE ;
			}
		}
                FoundGlobalScope = 0 ;
	}
	strcpy(CurrentTypedef,"") ;
	return FALSE ;
}

NEW_LINE_RETURN() 
{
	CurrentLine++; 
	if ( shouldprint ) strcat(OutBuf,prevtoken); 
	strcpy(prevtoken,yytext);
}


