CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='cc -E'
CMK_CC="cc -Wno-long-double "
CMK_CXX="c++ -Wno-long-double "
CMK_CXXPP='c++ -x c++ -E '
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_QT='generic'
CMK_XIOPTS=''
CMK_F90LIBS='-lvast90 -lg2c'
CMK_MOD_EXT="vo"
CMK_NO_BUILD_SHARED=true
