# Stub makefile for LaTeX PPL manual
FILE=manual
TEX= $(FILE).tex compile.tex  index.tex  install.tex  run.tex
DEST=install
LATEX2HTML=$(L2H) -split 5

include ../Makefile.common

index.tex:
	touch index.tex

