CMK_CPP_C='cc -E -I/usr/opt/rms/include '
CMK_CC='cc -pthread -I/usr/opt/rms/include '
CMK_CC_RELIABLE="$CMK_CC"
CMK_CC_FASTEST="$CMK_CC"
#CMK_CXX='cxx -pthread -D__USE_STD_IOSTREAM -I/usr/opt/rms/include '
CMK_CXX='cxx -pthread -I/usr/opt/rms/include '
CMK_CXXPP="$CMK_CXX -x c++ -E "
CMK_LD="eval $CMK_CC -expect_unresolved '*' "
CMK_LDXX="$CMK_CXX"
CMK_NATIVE_CC="$CMK_CC"
CMK_NATIVE_LD="$CMK_CC"
CMK_NATIVE_CXX="$CMK_CXX"
CMK_NATIVE_LDXX="$CMK_CXX"
CMK_CPP_SUFFIX="ii"
CMK_QT='axp-osf1-cc'
