# Assumes Clang C/C++ compiler:
CMK_CPP_CHARM="cpp -P"
CMK_CPP_C="clang$CMK_COMPILER_SUFFIX"
CMK_CC="clang$CMK_COMPILER_SUFFIX"
CMK_LD="clang$CMK_COMPILER_SUFFIX"
CMK_CXX="clang++$CMK_COMPILER_SUFFIX"
CMK_LDXX="clang++$CMK_COMPILER_SUFFIX"

CMK_CPP_C_FLAGS="-E"

CMK_COMPILER='clang'
CMK_WARNINGS_ARE_ERRORS="-Werror"
