ICC_STATIC=true

ICCOPTS="-static-intel"

CMK_CPP_C='icc -E '
CMK_CC='icc '
CMK_CXX='icpc '
CMK_LD="icc $ICCOPTS"
CMK_LDXX="icpc $ICCOPTS"
CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"

CMK_NATIVE_CC="$CMK_CC"
CMK_NATIVE_CXX="$CMK_CXX"
CMK_NATIVE_LD="$CMK_LD"
CMK_NATIVE_LDXX="$CMK_LDXX"
CMK_NATIVE_F90="$CMK_CF90"

CMK_SEQ_CC="$CMK_NATIVE_CC"
CMK_SEQ_CXX="$CMK_NATIVE_CXX"
CMK_SEQ_LD="$CMK_NATIVE_LD"
CMK_SEQ_LDXX="$CMK_NATIVE_LDXX"

. $CHARMINC/conv-mach-ifort.sh
