CMK_CPP_CHARM='cpp -P'
CMK_CPP_C='mpicc'
CMK_CC='mpicc '
CMK_CXX='mpicxx '

CMK_CPP_C_FLAGS="-E"

CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"

CMK_F90_USE_MODDIR=1
CMK_F90_MODINC='-p'

CMK_COMPILER='mpicc'
