CMK_CC='xlc_r '
CMK_CXX='xlC_r -qstaticinline '
CMK_LD="$CMK_CC -brtl "
CMK_LDXX="$CMK_CXX -brtl "
CMK_SEQ_CC='xlc_r '
CMK_SEQ_LD='xlc_r '
CMK_SEQ_CXX='xlC_r -qstaticinline '
CMK_SEQ_LDXX='xlC_r '
CMK_CF77='xlf_r  '
CMK_CF90='xlf90_r  -qsuffix=f=f90' 
CMK_CF90_FIXED='xlf90_r ' 
CMK_C_OPTIMIZE='-O3 -qstrict -Q  '
CMK_CXX_OPTIMIZE='-O3 -qstrict -Q '
CMK_AR='ar cq'
CMK_QT='aix32-xlc'
CMK_NM='nm '
