BUILD_CUDA=1
CUPTI_LIBDIR=$CUDA_DIR/extras/CUPTI/lib64
CMK_INCDIR="-I$CUDA_DIR/include $CMK_INCDIR "
CMK_LIBDIR="-L$CUDA_DIR/lib64 -L$CUPTI_LIBDIR -Wl,-rpath,$CUPTI_LIBDIR $CMK_LIBDIR "
CMK_LIBS="-lcudahybridapi -lcudart -lcupti $CMK_LIBS "
