#define CMK_OMP 1

#if CMK_THREADS_BUILD_DEFAULT && !CMK_ARM
#undef CMK_THREADS_USE_JCONTEXT
#undef CMK_THREADS_USE_FCONTEXT
#undef CMK_THREADS_USE_CONTEXT
#undef CMK_THREADS_ARE_WIN32_FIBERS
#undef CMK_THREADS_USE_PTHREADS
#define CMK_THREADS_USE_FCONTEXT 1
#endif
#define CMK_NOT_USE_TLS_THREAD   1
