static               insert();
static void          *remove_front();
static               read_parameters();
static int           comm_init();
static REL_TIME      latency();
static REL_TIME      broadcast_effect();
static int           network_ok_l();
static int           network_ok_s();
static int           network_ok_l_g();
static int           network_ok_s_g();
static int           cpu_accepts_l();
static int           cpu_accepts_s();
static int           scp_accepts_l();
static int           scp_accepts_s();
static int           always_accept();
static int           increase_net_load();
static int           decrease_net_load();
static int           ge();
static SIM_TIME      max_time_const;
static void          *create_event_heap();
static MSG           *fifo_dequeue();
static float         ran1();
