#!/bin/sh
#
# Just executes all its arguments.
PATH=.:$PATH
export PATH

args=""
pes=1
while [ $# -gt 0 ]
do
        case $1 in
        +p)
                pes=$2
                shift
                ;;
        +p*)
                pes=`echo $1 | awk '{print substr($1,3)}'`
                ;;
        *)
                args=$args" "$1
                ;;
        esac
        shift
done

$args +p$pes

