
CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='gcc -E'
CMK_CC='gcc '
CMK_CXX='g++ '
CMK_CXXPP='g++ -E '
CMK_LD='g++ '
CMK_LDXX='g++ '

CMK_C_OPTIMIZE='-O3 -g'
CMK_CXX_OPTIMIZE='-O3 -g'

CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt '
CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"

CMK_NATIVE_LIBS=''
CMK_NATIVE_CC='gcc '
CMK_NATIVE_LD='gcc '
CMK_NATIVE_CXX='g++ '
CMK_NATIVE_LDXX='g++ '

CMK_CF77='gfortran'
CMK_CF90='gfortran'
CMK_F90LIBS='-lgfortran'
CMK_MOD_NAME_ALLCAPS=1
CMK_MOD_EXT="mod"
CMK_F90_USE_MODDIR=1
CMK_F90_MODINC="-p"
