/*
  liveVizPoll: application-polling image-assembly interface.

  Original Author: Jonathan A. Booth, jbooth@uiuc.edu
  Latest   Author: Isaac Dooley 08/2005
*/

#include "liveViz.h"
#include "liveViz_impl.h"
#include "ImageData.h"


#undef DEBUG_PRINTS

/*readonly*/ CProxy_liveVizPollArray myGroupProxy;
CkReduction::reducerType poll_image_combine_reducer;
extern CkCallback clientGetImageCallback;

class liveVizPollArray : public Group {
private:
  CkMsgQ<liveVizRequestMsg> requestQueue; // holds client requests which have not been serviced
  CkQ<imageUnit> imageQueue;      // holds images generated by server, but not yet sent to client

  void init(){
	CkAssert(requestQueue.length()==0);	
	CkAssert(imageQueue.length()==0);
  }

public:

  liveVizPollArray() {init();}
  liveVizPollArray(CkMigrateMessage *m) {init();}

  /// Incoming request: handle or queue it up.
  void request(liveVizRequestMsg *msg) {

#ifdef DEBUG_PRINTS
	CkPrintf("begin incoming request: imageQueue length=%d requestsQueue %d\n", imageQueue.length(), requestQueue.length());
#endif

	CkAssert(CkMyPe() == 0);
	 
	if(imageQueue.length()>0){
	  imageUnit image = imageQueue.deq();
	  msg->req.wid = image.wid;
	  msg->req.ht = image.ht;
	  liveViz0Deposit(msg->req, image.imageData);
	  delete msg;
	}
	else {
	  requestQueue.enq(msg);
	}

#ifdef DEBUG_PRINTS
	CkPrintf("end liveVizPoll0Deposit: imageQueue length=%d requestsQueue %d\n", imageQueue.length(), requestQueue.length());
#endif
  
  }
  
  
  void liveVizPoll0Deposit(int wid, int ht, int bpp, byte * imageData) {
#ifdef DEBUG_PRINTS
	CkPrintf("begin liveVizPoll0Deposit: imageQueue length=%d requestsQueue %d\n", imageQueue.length(), requestQueue.length());
#endif

	// if there are pending requests, reply to one of them
	if(requestQueue.length()>0){
	  liveVizRequestMsg *msg = requestQueue.deq();
	  msg->req.wid = wid;
	  msg->req.ht = ht;
	  liveViz0Deposit(msg->req, imageData);
	  
	}
	// else enqueue the server generated image
	else{
	  const imageUnit newimage(bpp,wid,ht,imageData);
	  imageQueue.enq(newimage);
	}
	
#ifdef DEBUG_PRINTS
	CkPrintf("end liveVizPoll0Deposit: imageQueue length=%d requestsQueue %d\n", imageQueue.length(), requestQueue.length());
#endif

  }
  

};




/**
   Called by the reduction manager to combine all the source images
   received on one processor. This function adds all the image on one
   processor to one list of non-overlapping images. 
   
   Then the result is reduced onto processor zero in function
   vizPollReductionHandler()
*/
CkReductionMsg *imagePollCombineReducer(int nMsg,CkReductionMsg **msgs)
{
  if (nMsg==1) { //Don't bother copying if there's only one source
	CkReductionMsg *ret=msgs[0];
	msgs[0]=NULL; //Prevent reduction manager from double-delete
	return ret;
  }
  
  ImageData imageData (lv_config.getBytesPerPixel());
  
  CkReductionMsg* msg = CkReductionMsg::buildNew(imageData.CombineImageDataSize (nMsg,
																				 msgs),
												 NULL, poll_image_combine_reducer);
  
  imageData.CombineImageData(nMsg, msgs, (byte*)(msg->getData()));
  return msg;
}



/*
  Reduction handles an "image" from each processor. The result ends up here.
  Unpacks image, and passes it on to layer 0.
*/
void vizPollReductionHandler(void *r_msg)
{
  CkAssert(CkMyPe()==0);

  CkReductionMsg *msg = (CkReductionMsg*)r_msg;
  imageHeader *hdr=(imageHeader *)msg->getData();
  byte *srcData=sizeof(imageHeader)+(byte *)msg->getData();
  int bpp=lv_config.getBytesPerPixel();
  CkRect destRect(0,0,hdr->req.wid,hdr->req.ht);
  if (destRect==hdr->r) { //Client contributed entire image-- pass along unmodified
	//CkPrintf("case 1\n");
  	myGroupProxy.ckLocalBranch()->liveVizPoll0Deposit(hdr->r.wid(), hdr->r.ht(), bpp, srcData);
  }
  else { //Client didn't quite cover whole image-- have to pad
	//	CkImage src(hdr->r.wid(),hdr->r.ht(),bpp,srcData);
	//	CkAllocImage dest(hdr->req.wid,hdr->req.ht,bpp);
	//	dest.clear();
	//	dest.put(hdr->r.l,hdr->r.t,src);

	//	CkPrintf("case 2\n");

	myGroupProxy.ckLocalBranch()->liveVizPoll0Deposit(hdr->r.wid(), hdr->r.ht(), bpp, srcData);
  }
  delete msg;
}




//Called by server objects to deposit a piece of the final image
void liveVizPollDeposit(ArrayElement *client,
						int startx, int starty, 
						int sizex, int sizey,             // The dimensions of the piece I'm depositing
						int imagewidth, int imageheight,  // The dimensions of the entire image
						const byte * src,
						liveVizCombine_t combine_reducer_type, // a combiner type like "sum_image_data"
						int bytes_per_pixel
						)
{
  
  CkPrintf("%d: liveVizPollDeposit> Deposited image at (%d,%d), (%d x %d) pixels\n",CkMyPe(),startx,starty,sizex,sizey);
  
  ImageData imageData (bytes_per_pixel);
 
  // reduce all images from this processor
  poll_image_combine_reducer=CkReduction::addReducer(imagePollCombineReducer);
  CkReductionMsg* msg = CkReductionMsg::buildNew(imageData.GetBuffSize (startx,
																		starty,
																		sizex,
																		sizey,
																		imagewidth,
																		imageheight,
																		src),
												 NULL, poll_image_combine_reducer);
  imageData.WriteHeader(combine_reducer_type,NULL,(byte*)(msg->getData()));
  imageData.AddImage (imagewidth, (byte*)(msg->getData()));
  
  //Contribute this processor's images to the global reduction
  msg->setCallback(CkCallback(vizPollReductionHandler));
  client->contribute(msg);
}





//Called by clients to start liveViz.
void liveVizPollInit()
{
  if (CkMyPe()!=0) CkAbort("liveVizInit must be called only on processor 0!");

  myGroupProxy = CProxy_liveVizPollArray::ckNew();
 
  // Incoming image requests get sent to the poll array
  CkCallback myCB(CkIndex_liveVizPollArray::request(0), myGroupProxy[0]);
  clientGetImageCallback=myCB;

  liveViz0PollInit();

#ifdef DEBUG_PRINTS
  CkPrintf("Done with liveVizPollInit\n");
#endif

}


#include "liveVizPoll.def.h"

