# Stub makefile for LaTeX PPL manual
FILE	= manual
TEX	= $(FILE).tex bignetsim.tex install.tex interconnects.tex usage.tex

DEST	= bignetsim
LATEX2HTML	= $(L2H) -split 5
DOCTITLE = 'BigSimulator (BigNetSim) Parallel Simulator Manual'

include ../Makefile.common

index.tex:
	touch index.tex
