CMK_CPP_C='icc -E '
CMK_CC='icc '
CMK_CC_RELIABLE='icc -I/usr/local/mpich/include'
CMK_CC_FASTEST='icc -I/usr/local/mpich/include'
CMK_CXX='icpc -I/usr/local/mpich/include'
CMK_CXXPP='icpc -E -I/usr/local/mpich/include'
CMK_LD='icc'
CMK_LDXX='icpc'
