CMK_DEFS="$CMK_DEFS -DHAVE_USR_INCLUDE_MALLOC_H=1 "
CMK_CC="$CMK_CC -m64 -fPIC $CMK_DEFS"
CMK_CXX="$CMK_CXX -Wno-deprecated -m64 -fPIC $CMK_DEFS "
CMK_SEQ_CC="$CMK_CC -m64 -fPIC $CMK_DEFS "
CMK_SEQ_CXX="$CMK_CXX -m64 -fPIC $CMK_DEFS "
CMK_LD="$CMK_LD -m64 "
CMK_LDXX="$CMK_LDXX -m64 "
CMK_QT='generic64'
