#undef CMK_GETPAGESIZE_AVAILABLE
#define  CMK_GETPAGESIZE_AVAILABLE			1

#undef CMK_TIMER_USE_RDTSC
#undef CMK_TIMER_USE_GETRUSAGE
#define CMK_TIMER_USE_RDTSC				0
#define CMK_TIMER_USE_GETRUSAGE				1

#undef CMK_MEMORY_PROTECTABLE
#define CMK_MEMORY_PROTECTABLE                          0

