#undef CMK_GETPAGESIZE_AVAILABLE
#define  CMK_GETPAGESIZE_AVAILABLE			1

#undef CMK_TIMER_USE_RDTSC
#undef CMK_TIMER_USE_GETRUSAGE
#define CMK_TIMER_USE_RDTSC				0
#define CMK_TIMER_USE_GETRUSAGE				1

#undef CMK_MALLOC_USE_GNU_MALLOC
#define CMK_MALLOC_USE_GNU_MALLOC                       0
#define CMK_MALLOC_USE_GNUOLD_MALLOC                    1
