CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='gcc -E'
CMK_CC='gcc '
CMK_CXX='g++ '
CMK_CXXPP="$CMK_CXX -x c++ -E "
CMK_CF77='f77 '
CMK_CF90='f90 '
CMK_CF90_FIXED="$CMK_CF90 -W132 "
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_XIOPTS=''
CMK_F90LIBS='-L/usr/absoft/lib -L/opt/absoft/lib -lf90math -lfio -lU77 -lf77math '
CMK_MOD_NAME_ALLCAPS=1
CMK_MOD_EXT="mod"
CMK_F90_USE_MODDIR=1
CMK_F90_MODINC="-p"
