
default:
	(cd METISLib ; $(MAKE) ) 
	(cd ParMETISLib ; $(MAKE) ) 
#	(cd Programs ; $(MAKE) ) 

clean:
	(cd METISLib ; $(MAKE) realclean )
	(cd ParMETISLib ; $(MAKE) realclean )
#	(cd Programs ; $(MAKE) realclean )

all:
	(cd METISLib ; $(MAKE) ) 
	(cd ParMETISLib ; $(MAKE) ) 
#	cp libparmetis.a $(LIBDIR)/
#	cp libmetis.a $(LIBDIR)/
