set(CTEST_PROJECT_NAME         "Charm++")
set(CTEST_NIGHTLY_START_TIME   "01:00:00 CET")
set(CTEST_DROP_METHOD          "http")
set(CTEST_DROP_SITE            "my.cdash.org")
set(CTEST_DROP_LOCATION        "/cdash/submit.php?project=Charm++")
set(CTEST_DROP_SITE_CDASH      TRUE)
