CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='cc -E '
CMK_CXXPP='CC -E '
CMK_CC='cc -Ae '
CMK_CXX='CC '
CMK_CF77='f77'
CMK_CF90='f90'
CMK_C_DEBUG='-g +O0 '
CMK_C_OPTIMIZE='+O2'
CMK_LD='cc -Wl,+parallel '
CMK_LDXX='CC -Wl,+parallel '
CMK_RANLIB='true'
CMK_LIBS='-lckqt -lpthread -lcps -lpthread -lail '
CMK_SEQ_LD='cc'
CMK_SEQ_LDXX='CC'
CMK_QT='convex'
CMK_XIOPTS=''

