# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex 
DEST=pose
LATEX2HTML=$(L2H) -split 5
DOCTITLE='POSE Reference Manual'
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/pose">POSE Homepage</a><br>'

include ../Makefile.common

index.tex:
	touch index.tex
