CMK_DEFS=' '
CMK_CPP_CHARM="/usr/ccs/lib/cpp $CMK_DEFS"
CMK_CPP_C="gcc -E $CMK_DEFS"
CMK_CC="gcc $CMK_DEFS"
CMK_CXX="g++ $CMK_DEFS "
CMK_CXXPP="g++ -x c++ -E $CMK_DEFS "
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='true'
CMK_LIBS=' -lnsl -lsocket -lckqt'
CMK_NATIVE_LIBS=' -lnsl -lsocket'
CMK_XIOPTS=''
