#include <time.h>
#include "vecadd.decl.h"
#include "hapi.h"
#ifdef USE_NVTX
#include "hapi_nvtx.h"
#endif
#include "nccl.h"

/* readonly */ CProxy_Main mainProxy;
/* readonly */ CProxy_NCCLManager ncclManagerProxy;


extern void cudaVecAdd(int vectorSize, float* h_A, float* d_A);
extern void localReduce(float* A, float* result, int n);

void randomInit(float* data, int size) {
#ifdef USE_NVTX
  NVTXTracer nvtx_range("randomInit", NVTXColor::PeterRiver);
#endif
  for (int i = 0; i < size; ++i) {
    data[i] = 10;
  }
}

class Main : public CBase_Main {
 private:
  CProxy_Workers workers;
  int numChares;
  double startTime;

 public:
  Main(CkArgMsg* m) {
#ifdef USE_NVTX
    NVTXTracer nvtx_range("Main::Main", NVTXColor::Turquoise);
#endif

    // default values
    mainProxy = thisProxy;
    numChares = 4;

    // handle arguments
    int c;
    while ((c = getopt(m->argc, m->argv, "c:s:")) != -1) {
      switch (c) {
        case 'c':
          numChares = atoi(optarg);
          break;
        default:
          CkPrintf("Usage: %s -c [chares] -s [vector size]\n", m->argv[0]);
          CkExit();
      }
    }
    delete m;

    // print configuration
    CkPrintf("\n[CUDA vecadd example]\n");
    CkPrintf("Chares: %d\n", 1);

    // create 1D chare array
    workers = CProxy_Workers::ckNew(1024, 4 * CkNumPes());

    ncclManagerProxy = CProxy_NCCLManager::ckNew();

    // start measuring execution time
    startTime = CkWallTimer();

    // fire off all chares in array
    //workers.begin();
  }

  void nccl_done() {
    workers.begin();
    //ncclManagerProxy.ckLocalBranch()->localChares++;
  }

  void done() {
#ifdef USE_NVTX
    NVTXTracer nvtx_range("Main::done", NVTXColor::Turquoise);
#endif

    CkPrintf("\nElapsed time: %f s\n", CkWallTimer() - startTime);
    CkExit();
  }
};

class NCCLManager : public CBase_NCCLManager {
 private:
  int localChares;
  ncclUniqueId id;
  ncclComm_t comm;
  float* localRed;
  int redCount;

 public:
  float* globalRed;

  NCCLManager() {
    redCount = 0;
    if (CkMyPe() == 0) {
      ncclGetUniqueId(&id);
      thisProxy.recvNCCLId(sizeof(ncclUniqueId), (char*)id.internal);
    }
  }

  NCCLManager(CkMigrateMessage* m) : CBase_NCCLManager(m) {}

  void registerChare() {
    localChares++;
  }

  void setupNCCL() {
    CkPrintf("NCCL Unique ID generated by PE %d\n", CkMyPe());

    CkCallback cb(CkIndex_Main::nccl_done(), mainProxy);
    contribute(cb);
  }

  void recvNCCLId(int size, char* id_buf) {
    //CkPrintf("NCCL Unique ID received by PE %d\n", CkMyPe());
    memcpy(id.internal, id_buf, sizeof(ncclUniqueId));

    ncclCommInitRank(&comm, CkNumPes(), id, CkMyPe());

    CkCallback cb(CkIndex_Main::nccl_done(), mainProxy);
    contribute(cb);
  }

  void deviceContribute(int size, float* data) {
    localReduce(localRed, data, size);
    if (++redCount == localChares) {
      ncclReduce((const void*)localRed, (void*)globalRed, size,
                    ncclFloat, ncclSum, 0, comm, cudaStreamDefault);
      redCount = 0;
    }
  }
};

class Workers : public CBase_Workers {
 private:
  int vectorSize;
  float* h_A;
  float* d_A;
  cudaStream_t stream;

 public:
  Workers(int size) : vectorSize(size) {
    int dataSize = sizeof(float) * vectorSize;
    hapiCheck(cudaMallocHost(&h_A, dataSize));
    hapiCheck(cudaStreamCreate(&stream));
    hapiCheck(hapiMalloc((void**) &d_A, dataSize));

    srand(time(NULL));
    randomInit(h_A, vectorSize);
  }

  Workers(CkMigrateMessage* m) : CBase_Workers(m) 
  {
    hapiCheck(cudaStreamCreate(&stream));    
  }

  ~Workers() {
    hapiCheck(cudaFreeHost(h_A));
    hapiCheck(cudaStreamDestroy(stream));
    hapiCheck(cudaFree(d_A));
  }

  void pup(PUP::er& p) {
    p | vectorSize;
    if (p.isUnpacking())
    {
      hapiMalloc((void**) &d_A, vectorSize * sizeof(float));
    }
    p(d_A, vectorSize, PUP::PUPMode::DEVICE);
  }

  void begin() {
    ncclManagerProxy.ckLocalBranch()->registerChare();
    CkCallback cb(CkIndex_Workers::reduction(), thisProxy);
    contribute(cb);
  }

  void reduction() {
    ncclManagerProxy.ckLocalBranch()->deviceContribute(vectorSize, d_A);

    if (thisIndex == 0) {
      cudaMemcpy(h_A, ncclManagerProxy.ckLocalBranch()->globalRed,
                 sizeof(float) * vectorSize, cudaMemcpyDeviceToHost);
    }

    for (int i = 0; i < vectorSize; ++i) {
      if (thisIndex == 0) {
        // Expected value is 10 * total number of chares
        float expected = 10.0f * 10;
        if (h_A[i] != expected) {
          CkPrintf("Error at index %d: Expected %.2f, Got %.2f\n",
                   i, expected, h_A[i]);
          break;
        }
      }
    }

    //hapiCheck(hapiFree(d_A));
    contribute(CkCallback(CkIndex_Main::done(), mainProxy));
  }
};

#include "vecadd.def.h"
