CMK_CPP_C="ecc -E "
CMK_CC="ecc -fpic $CMK_CFLAGS "
CMK_CC_RELIABLE="ecc "
CMK_CC_FASTEST="ecc "
CMK_CXX="ecpc -fpic "
CMK_CXXPP="ecpc -E "
CMK_LD="ecc "
CMK_LDXX="ecpc "
CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"
CMK_NATIVE_CC="ecc -fpic "
CMK_NATIVE_LD="ecc "
CMK_NATIVE_CXX="ecpc -fpic "
CMK_NATIVE_LDXX="ecpc "

