#CMK_CFLAGS='-I/usr/local/gnu/include'
#CMK_LDFLAGS='-L/usr/local/gnu/lib'
CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C="gcc3 -E $CMK_INCDIR"
CMK_CC="gcc3 $CMK_INCDIR"
CMK_CXX="g++3 $CMK_INCDIR"
CMK_CXXPP="$CMK_CC -x c++ -E "
CMK_CF77='f77'
CMK_CF90='f90'
CMK_LD="$CMK_CC -static "
CMK_LDXX="$CMK_CC -static "
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_QT='generic64'
CMK_XIOPTS=''
CMK_F90LIBS='-lvast90 -lg2c'
CMK_MOD_EXT="vo"
