#CMK_CFLAGS=""
#CMK_LDFLAGS="-L/usr/local/gnu/lib"

CMK_CPP_CHARM="/lib/cpp -P"
CMK_CPP_C="gcc -E $CMK_INCDIR"
CMK_CC="gcc -fpic $CMK_INCDIR $CMK_CFLAGS "
CMK_CXX="g++ -fpic $CMK_INCDIR "
CMK_CXXPP="$CMK_CC -x c++ -E "
CMK_LD="$CMK_CC "
CMK_LDXX="$CMK_CXX "
CMK_RANLIB="ranlib"
CMK_LIBS="-lckqt "
CMK_QT="generic64-light"
CMK_XIOPTS=""

CMK_CF77="f77"
CMK_CF90="f90"
CMK_F90LIBS="-lvast90 -lg2c"
