
CHARMBASE=../../../../
CHARMBIN=$(CHARMBASE)/bin
CHARMINC=$(CHARMBASE)/include

OBJDIR=../tmp

CHARMC=$(CHARMBIN)/charmc -I$(CHARMINC)/pose $(OPTS)
ETRANS=$(CHARMBIN)/etrans.pl
POSEMODULE=-module pose

ifeq ($(SEQUENTIAL),1)
OPTS += "-DSEQUENTIAL_POSE"
ETRANS += "-s"
POSEMODULE=-module seqpose
endif
