OPTS= -ll -ly
CC=cc -g

OBJECTS= y.tab.o 

all: $(OBJECTS)
	$(CC) $(OBJECTS) -o jitrans $(OPTS)

y.tab.o: y.tab.c lex.yy.c
	$(CC) -c y.tab.c

y.tab.c: jitrans.y
	yacc jitrans.y

lex.yy.c: jitrans.lex
	lex jitrans.lex

clean:
	rm -f core *~ jitrans y.tab.o y.tab.c lex.yy.c

