CMK_CPP_CHARM='/usr/ccs/lib/cpp '
CMK_CPP_C='cc -E '
CMK_CC='cc -KPIC '
CMK_CC_RELIABLE='cc '
CMK_CC_FASTEST='cc '
CMK_CXX='CC -KPIC -library=Cstd'
CMK_CXXPP='CC -E '
CMK_CF77='f77'
CMK_CF90='f90 -C -stackvar -g '
CMK_C_DEBUG='-g'
CMK_C_OPTIMIZE='-fast'
CMK_CXX_DEBUG='-g'
CMK_CXX_OPTIMIZE='-fast'
CMK_LD='cc '
CMK_LDXX='CC -library=Cstd'
CMK_AR='CC -xar -o'
CMK_LIBS='-lnsl -lsocket -lckqt'
CMK_SEQ_LIBS='-lnsl -lsocket'
CMK_SEQ_CC='cc'
CMK_SEQ_LD='cc'
CMK_SEQ_CXX='CC -library=Cstd'
CMK_SEQ_LDXX='CC -library=Cstd'
CMK_CPP_SUFFIX="cc"
CMK_XLATPP='charmxlat++ -w -p '
CMK_QT='solaris-cc'
CMK_F90LIBS='-lfsu -lsunmath -lfsumai -lfminlai -lfmaxlai -lfminvai -lfmaxvai -lfui -lfai'
CMK_MOD_EXT="mod"
CMK_F90_USE_MODDIR=1
