
CMK_CFLAGS="-I/usr/local/gm-1.4/include"
CMK_CC="$CMK_CC $CMK_CFLAGS"
CMK_CXX="$CMK_CXX $CMK_CFLAGS"
CMK_CXXPP="$CMK_CXXPP $CMK_CFLAGS"
CMK_LDFLAGS="-L/usr/local/gm-1.4/lib"
CMK_LD="$CMK_LD $CMK_LDFLAGS"
CMK_LDXX="$CMK_LDXX $CMK_LDFLAGS"
CMK_LIBS="$CMK_LIBS -lgm"
