CMK_DEFS="-fPIC"
CMK_CPP_CHARM="/usr/ccs/lib/cpp $CMK_DEFS"
CMK_CPP_C="gcc -E $CMK_DEFS"
CMK_CC="gcc $CMK_DEFS"
CMK_CXX="g++ $CMK_DEFS "
CMK_CXXPP="g++ -x c++ -E $CMK_DEFS "
CMK_CF77='f77 -stackvar '
CMK_CF90='f90 -C -stackvar '
CMK_CF90_FIXED="$CMK_CF90 -fixed "
CMK_RANLIB='true'
CMK_LIBS=' -lnsl -lsocket -lckqt'
CMK_LD_SHARED="-G"
CMK_LD_LIBRARY_PATH="-R $CHARMLIBSO/"
CMK_NATIVE_LIBS=' -lnsl -lsocket'
CMK_XIOPTS=''
CMK_F90LIBS='-L/opt/SUNWspro/lib -lfsu -lsunmath -lfsumai -lfminlai -lfmaxlai -lfminvai -lfmaxvai -lfui -lfai'
CMK_MOD_EXT="mod"
CMK_F90_USE_MODDIR=1
CMK_QT='solaris-gcc'
