CMK_DEFS=' '
CMK_CPP_CHARM="/usr/ccs/lib/cpp $CMK_DEFS"
CMK_CPP_C="gcc -E $CMK_DEFS"
CMK_CC="gcc $CMK_DEFS"
CMK_CC_RELIABLE="gcc $CMK_DEFS "
CMK_CC_FASTEST="gcc $CMK_DEFS "
CMK_CXX="g++ $CMK_DEFS "
CMK_CXXPP="g++ -x c++ -E $CMK_DEFS "
CMK_CF77='f77'
CMK_CF90='f90'
CMK_C_DEBUG='-g'
CMK_C_OPTIMIZE='-O'
CMK_CXX_DEBUG='-g'
CMK_CXX_OPTIMIZE='-O'
CMK_LD="gcc $CMK_DEFS "
CMK_LDXX="g++ $CMK_DEFS "
CMK_LD77=''
CMK_M4='m4'
CMK_SUF='o'
CMK_AR='ar q'
CMK_RANLIB='true'
CMK_LIBS=' -lnsl -lsocket -lckqt'
CMK_SEQ_LIBS=' -lnsl -lsocket'
CMK_SEQ_CC='gcc'
CMK_SEQ_LD='gcc'
CMK_SEQ_CXX='g++'
CMK_SEQ_LDXX='g++'
CMK_CPP_SUFFIX="ii"
CMK_XLATPP='charmxlat++ '
CMK_QT='solaris-gcc'
CMK_XIOPTS=''
