#!/bin/sh -x

CC="gcc -D__AXP__ -I."

ln -s md/axp.h qtmd.h
$CC -c -o qt.o qt.c
as -o qtmds.o md/axp.s
ar q libqt.a qt.o qtmds.o

$CC -c stp.c
ar q libstp.a stp.o

$CC -c meas.c
as -o qtmdb.o md/axp_b.s
$CC -o run meas.o qtmdb.o libstp.a libqt.a
