#!/bin/sh -x

CC="gcc -I. -O2"

sed 's/\/\*/\/\//' < md/i386.s > qtmds.s
sed 's/\/\*/\/\//' < md/i386_b.s > qtmdb.s

ln -s md/i386.h qtmd.h
$CC -pedantic -Wall -c -o qt.o qt.c
as -o qtmds.o qtmds.s
ar q libqt.a qt.o qtmds.o

$CC -c stp.c
ar q libstp.a stp.o

$CC -c meas.c
as -o qtmdb.o qtmdb.s
$CC -o run meas.o qtmdb.o libstp.a libqt.a
