#!/bin/sh -x

CC="cc -64 -I. -O"

ln -s md/mipspro.h qtmd.h
$CC -c -o qt.o qt.c
cc -c -O -64 -o qtmds.o md/mipspro.s
ar q libqt.a qt.o qtmds.o

$CC -c stp.c
ar q libstp.a stp.o

$CC -c meas.c
cc -c -64 -O -o qtmdb.o md/mipspro_b.s
$CC -O -o run meas.o qtmdb.o libstp.a libqt.a
