$(L)/libconv-machine.a: machine.c machine-common-core.c machine-dgram.c machine-pxshm.c  machine-tcp.c machine-eth.c machine.h machine-smp.c conv-onesided.c immediate.c machine-recover.c machine-commthd-util.c machine-onesided.h $(CVHEADERS)

charmrun: sockRoutines.c sockRoutines.h ccs-server.c ccs-server.h sockRoutines-seq.o $(L)/libck.a $(CVLIBS)
	if [ ! -f charmrun ]; then \
			(cd charmrun-src ; $(MAKE) OPTS='$(OPTS) -Wno-error' -j1) ; fi
