charmrun: sockRoutines.c sockRoutines.h ccs-server.c ccs-server.h sockRoutines-seq.o $(L)/libck.a $(CVLIBS)
	if [ ! -f charmrun ]; then \
			(cd charmrun-src ; $(MAKE) OPTS='$(OPTS) -Wno-error' -j1) ; fi
