CMK_CPP_CHARM='/lib/cpp -P'
CMK_CPP_C='mpicc -E'
CMK_CC='mpicc '
CMK_CXX='mpiCC '
CMK_CXXPP='mpiCC -E '
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_SEQ_LIBS=''
CMK_SEQ_CC='cc'
CMK_SEQ_LD='cc'
CMK_SEQ_CXX='CC'
CMK_SEQ_LDXX='CC'
CMK_QT='solaris-cc'
CMK_XIOPTS=''

