test -z "$CMK_INCDIR" && CMK_INCDIR='-I /usr/local/vmi/mpich/include'
test -z "$CMK_LIBDIR" && CMK_LIBDIR='-L /usr/local/vmi/mpich/lib/pgi'
CMK_CPP_C="pgcc -E $CMK_INCDIR "
CMK_CC="pgcc $CMK_INCDIR "
CMK_CC_RELIABLE="gcc $CMK_INCDIR "
CMK_CC_FASTEST="pgcc $CMK_INCDIR "
CMK_CXX="pgCC $CMK_INCDIR "
CMK_CXXPP="pgCC -E $CMK_INCDIR "
CMK_LD="pgcc $CMK_LIBDIR "
CMK_LDXX="pgCC $CMK_LIBDIR "
