CMK_CPP_C='pgcc -E -I/usr/local/vmi/mpich/include'
CMK_CC='pgcc -I/usr/local/vmi/mpich/include'
CMK_CC_RELIABLE='gcc -I/usr/local/vmi/mpich/include'
CMK_CC_FASTEST='pgcc -I/usr/local/vmi/mpich/include'
CMK_CXX='pgCC -I/usr/local/vmi/mpich/include'
CMK_CXXPP='pgCC -E -I/usr/local/vmi/mpich/include'
CMK_LD='pgcc -L/usr/local/vmi/mpich/lib/pgi'
CMK_LDXX='pgCC -L/usr/local/vmi/mpich/lib/pgi'
