# src/mpi-linux/conv-mach-vmi.sh
CMK_CPP_C='gcc -E'
CMK_CC='gcc -I/usr/local/vmi/mpich/include '
CMK_CC_RELIABLE='gcc '
CMK_CC_FASTEST='gcc '
CMK_CXX='g++ -I/usr/local/vmi/mpich/include '
CMK_CXXPP='gcc -E '
CMK_LD='gcc -L /usr/local/vmi/mpich/lib/gcc'
CMK_LDXX='g++ -L /usr/local/vmi/mpich/lib/gcc'
CMK_LIBS='-lckqt -lmpich -lvmi -ldl -lpthread'
