CMK_CPP_C='pgcc -E -I/usr/local/mpich/include'
CMK_CC='pgcc -I/usr/local/mpich/include'
CMK_CC_RELIABLE='gcc -I/usr/local/mpich/include'
CMK_CC_FASTEST='pgcc -I/usr/local/mpich/include'
CMK_CXX='pgCC -I/usr/local/mpich/include'
CMK_CXXPP='pgCC -E -I/usr/local/mpich/include'
CMK_LD='pgcc'
CMK_LDXX='pgCC'
