#undef CMK_GETPAGESIZE_AVAILABLE
#define  CMK_GETPAGESIZE_AVAILABLE			1

#undef CMK_TIMER_USE_GETRUSAGE
#undef CMK_TIMER_USE_SPECIAL
#undef CMK_TIMER_USE_RDTSC
#define CMK_TIMER_USE_RDTSC				1

#undef CMK_MEMORY_PROTECTABLE
#define CMK_MEMORY_PROTECTABLE                          0

