#!/bin/sh
#
# Conv-host for Cray T3E:
#  Translates +pN-style conv-host options into 
# mpp -n N options.

args=""
pes=1

while [ $# -gt 0 ]
do
	case $1 in
	+p)
		pes=$2
		shift
		;;
	+p*)
		pes=`echo $1 | awk '{print substr($1,3)}'`
		;;
	*) 
		args="$args $1"
		;;
	esac
	shift
done

echo "Running on $pes processors: $args"

mpprun -n $pes $args
