/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_accept[157] =
    {   0,
        0,    0,   67,   65,   61,   62,   17,   65,   65,   11,
        5,   65,   12,   13,    9,    7,   43,    8,   16,   10,
       57,   56,    3,   46,   24,   32,   25,    2,    1,   51,
       14,   15,    6,   44,    4,   45,   18,   61,   29,    0,
       60,    0,    0,   50,    0,    0,    0,   37,   30,   40,
        0,    0,   35,   20,   33,    0,   47,   48,   21,   34,
       19,   54,   36,   53,   57,    0,    0,   57,   57,    0,
       56,   56,   56,   22,   26,   28,   27,   23,    0,   51,
        0,   42,   41,   31,    0,    0,    0,    0,    0,    0,
        0,   59,    0,    0,    0,   54,   53,    0,   53,    0,

       55,   57,   57,   58,   56,   56,   39,   38,    0,    0,
        0,    0,   49,    0,    0,    0,    0,    0,    0,    0,
       54,    0,   53,   55,   58,   58,    0,   52,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   58,   58,   52,
        0,    0,    0,   64,    0,    0,    0,    0,    0,   64,
       64,   63,    0,   63,   63,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   29,   29,   29,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   32,   32,   35,   32,   32,
       36,   37,   38,   39,   32,    1,   40,   41,   29,   42,

       43,   44,   45,   32,   46,   32,   32,   47,   48,   49,
       32,   50,   32,   51,   32,   52,   34,   53,   32,   35,
       32,   32,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    5,
        1,    1,    1,    1,    1,    1,    1,    1,    6,    6,
        7,    8,    1,    1,    1,    1,    4,    1,    9,    9,
        9,   10,   10,   10,   11,    1,    4,    1,    1,   12,
       12,    9,    9,   12,   10,   10,   10,   10,   11,   10,
       11,   11,   11,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[172] =
    {   0,
        0,    0,  314,  596,   56,  596,  288,   53,   59,  286,
       56,  269,  596,  596,  278,   48,   61,   50,   48,  277,
      101,  132,  596,  596,   46,  267,   57,  596,  596,   82,
      596,  596,  261,  596,   47,  596,  596,   84,  596,   71,
      596,   72,   91,  126,  243,  235,  227,  596,  596,  596,
       64,   78,  596,  596,  596,  122,  596,  596,  596,  596,
      596,  161,  596,  190,  241,  140,  153,  241,   56,    0,
        0,  237,   67,  240,  596,  596,  596,  238,  184,  193,
      191,  596,  596,  596,  165,    0,   93,   90,  164,  154,
      157,  596,  179,    0,  198,  596,    0,  208,  596,  135,

      211,  596,  596,   96,  596,  596,  596,  596,  137,  219,
      253,  113,  596,  216,  144,  147,  143,  230,  288,  226,
      233,  241,  268,  596,  134,  130,  198,    0,  127,  314,
      285,    0,  106,  318,   94,  231,  340,  596,  596,    0,
      220,  304,  379,  124,  344,   83,  233,  242,  405,    0,
      114,   92,  263,    0,   85,  596,  449,  461,  472,  482,
      491,  498,  505,  517,  524,  535,  545,  552,  559,  571,
      583
    } ;

static yyconst short int yy_def[172] =
    {   0,
      156,    1,  156,  156,  156,  156,  156,  157,  156,  156,
      156,  158,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  159,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  157,
      156,  160,  156,  156,  156,  156,  156,  156,  156,  156,
      158,  161,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,   21,  156,  156,  156,  156,  162,
       22,  156,  156,  156,  156,  156,  156,  156,  156,  159,
      156,  156,  156,  156,  157,  163,  156,  164,  156,  156,
      156,  156,  158,  165,  156,  156,   64,  156,  156,  156,

      156,  156,  156,  162,  156,  156,  156,  156,  166,  157,
      157,  164,  156,  167,  156,  156,  156,  158,  158,  156,
      156,  156,  156,  156,  156,  156,  166,  168,  157,  111,
      164,  169,  156,  156,  156,  158,  119,  156,  156,  168,
      157,  164,  164,  170,  156,  156,  158,  164,  143,  170,
      170,  171,  164,  171,  171,    0,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156
    } ;

static yyconst short int yy_nxt[654] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   30,   30,   30,   30,   31,    4,   32,   33,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   34,   35,   36,   37,   38,   41,   38,
       43,   54,   56,   56,   49,   59,   62,   62,   62,   74,
       75,   83,   55,   92,   60,   61,   41,   44,   44,   44,
       50,   77,   78,   79,   79,   38,  155,   38,  103,   42,
       85,   85,   43,  155,   87,  113,   93,   93,   88,  106,

       52,   84,  103,   81,   45,   46,   86,   42,   47,   44,
       44,   44,   94,  106,   57,  151,   58,   64,  113,   65,
       65,   66,  152,   56,   56,  151,  114,   87,  125,  126,
       67,   88,   41,   68,   69,   70,   45,   46,  127,  127,
       47,  146,  125,   67,   44,   44,   44,   68,   64,  114,
       71,   71,   71,  101,  101,  101,   64,  144,   66,   66,
       66,   67,  139,   42,   72,   73,  100,  138,  100,   67,
       41,  101,  101,  101,   67,   57,  139,   58,   72,   62,
       62,   62,   67,  110,  110,   79,   79,  135,   92,  134,
       95,   96,  133,   96,   79,   79,  117,  118,  118,  127,

      127,   42,  116,   95,   96,   81,  115,   96,   97,   97,
       97,  120,  109,  120,   81,   52,  121,  121,  121,   98,
       99,  122,   99,  122,   41,   41,  123,  123,  123,  101,
      101,  101,   98,   99,  131,  131,   99,  129,  129,   92,
       92,  124,   92,  124,  121,  121,  121,  113,  136,  136,
      132,  121,  121,  121,  124,   42,   42,  124,   41,  123,
      123,  123,  108,   96,  107,   96,   52,   52,  113,   52,
      105,  130,  130,  130,  102,  156,   96,   91,  114,   96,
       90,  130,  130,  130,   89,   82,  123,  123,  123,   42,
      113,   76,  130,  130,  130,  130,  130,   92,   99,  114,

       99,   63,   53,  142,  142,   52,  137,  137,  137,  113,
       48,   99,   39,  156,   99,  156,  137,  137,  137,  145,
      156,  114,  148,  148,   52,  156,  156,  137,  137,  137,
      137,  137,  141,  141,  141,  156,   44,   44,   44,  156,
      114,  156,  141,  141,  141,  145,  156,  156,  156,  156,
      156,  156,  156,  141,  141,  141,  141,  141,  147,  147,
      147,  156,   44,   44,   44,  156,  156,  156,  147,  147,
      147,  156,  156,  156,  156,  156,  156,  156,  156,  147,
      147,  147,  147,  147,  113,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  149,  149,  149,

      156,  156,  156,  156,  156,  156,  156,  149,  149,  149,
      156,  156,  156,  156,  156,  114,  156,  156,  149,  149,
      149,  149,  149,  153,  153,  153,  156,  156,  156,  156,
      156,  156,  156,  153,  153,  153,  156,  156,  156,  156,
      156,  156,  156,  156,  153,  153,  153,  153,  153,   40,
       40,  156,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   51,   51,  156,   51,  156,   51,   51,   51,   51,
       51,   51,   51,   80,   80,  156,  156,   80,   80,   80,
       80,   80,   80,   80,   40,   40,   40,   40,  156,  156,
      156,  156,   40,   40,   51,   51,   51,  156,  156,  156,

      156,   51,   51,  104,  104,  156,  104,  156,  156,  104,
      111,  111,  156,  111,  156,  156,  111,  112,  112,  156,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  119,
      119,  156,  119,  156,  156,  119,  128,  128,  156,  156,
      156,  156,  156,  128,  128,  128,  128,  112,  112,  112,
      112,  156,  156,  156,  156,  112,  112,  140,  140,  156,
      140,  140,  140,  140,  143,  143,  156,  143,  156,  156,
      143,  150,  150,  156,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  154,  154,  156,  154,  154,  154,  154,
      154,  154,  154,  154,  154,    3,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156
    } ;

static yyconst short int yy_chk[654] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,    8,    5,
        9,   16,   17,   17,   11,   18,   19,   19,   19,   25,
       25,   35,   16,   51,   18,   18,   40,    9,    9,    9,
       11,   27,   27,   30,   30,   38,  155,   38,   69,    8,
       42,   42,   43,  152,   87,   88,   52,   52,   87,   73,

       51,   35,   69,   30,    9,    9,   42,   40,    9,   43,
       43,   43,   52,   73,   17,  151,   17,   21,  112,   21,
       21,   21,  146,   56,   56,  144,   88,   44,  104,  104,
       21,   44,  129,   21,   21,   21,   43,   43,  109,  109,
       43,  135,  104,   21,   44,   44,   44,   21,   22,  112,
       22,   22,   22,  100,  100,  100,   66,  133,   66,   66,
       66,   22,  126,  129,   22,   22,   67,  125,   67,   66,
       85,   67,   67,   67,   22,   56,  126,   56,   22,   62,
       62,   62,   66,   85,   85,   79,   79,  117,   93,  116,
       62,   62,  115,   62,   80,   80,   91,   93,   93,  127,

      127,   85,   90,   62,   62,   79,   89,   62,   64,   64,
       64,   95,   81,   95,   80,   93,   95,   95,   95,   64,
       64,   98,   64,   98,  110,  141,   98,   98,   98,  101,
      101,  101,   64,   64,  114,  114,   64,  110,  110,  118,
      136,  101,  147,  101,  120,  120,  120,  148,  118,  118,
      114,  121,  121,  121,  101,  110,  141,  101,  111,  122,
      122,  122,   78,  121,   74,  121,  118,  136,  153,  147,
       72,  111,  111,  111,   68,   65,  121,   47,  148,  121,
       46,  111,  111,  111,   45,   33,  123,  123,  123,  111,
      131,   26,  111,  111,  111,  111,  111,  119,  123,  153,

      123,   20,   15,  131,  131,   12,  119,  119,  119,  142,
       10,  123,    7,    3,  123,    0,  119,  119,  119,  134,
        0,  131,  142,  142,  119,    0,    0,  119,  119,  119,
      119,  119,  130,  130,  130,    0,  134,  134,  134,    0,
      142,    0,  130,  130,  130,  145,    0,    0,    0,    0,
        0,    0,    0,  130,  130,  130,  130,  130,  137,  137,
      137,    0,  145,  145,  145,    0,    0,    0,  137,  137,
      137,    0,    0,    0,    0,    0,    0,    0,    0,  137,
      137,  137,  137,  137,  143,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  143,  143,  143,

        0,    0,    0,    0,    0,    0,    0,  143,  143,  143,
        0,    0,    0,    0,    0,  143,    0,    0,  143,  143,
      143,  143,  143,  149,  149,  149,    0,    0,    0,    0,
        0,    0,    0,  149,  149,  149,    0,    0,    0,    0,
        0,    0,    0,    0,  149,  149,  149,  149,  149,  157,
      157,    0,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  158,  158,    0,  158,    0,  158,  158,  158,  158,
      158,  158,  158,  159,  159,    0,    0,  159,  159,  159,
      159,  159,  159,  159,  160,  160,  160,  160,    0,    0,
        0,    0,  160,  160,  161,  161,  161,    0,    0,    0,

        0,  161,  161,  162,  162,    0,  162,    0,    0,  162,
      163,  163,    0,  163,    0,    0,  163,  164,  164,    0,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  165,
      165,    0,  165,    0,    0,  165,  166,  166,    0,    0,
        0,    0,    0,  166,  166,  166,  166,  167,  167,  167,
      167,    0,    0,    0,    0,  167,  167,  168,  168,    0,
      168,  168,  168,  168,  169,  169,    0,  169,    0,    0,
      169,  170,  170,    0,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  171,  171,    0,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "xl-lexsp.flex"
#define INITIAL 0
#line 3 "xl-lexsp.flex"
#define YYSTYPE YSNPTR
#include "xl-lex.h"
#include "xl-yacc.tab.h"
#include "xl-sym.h"
#include <string.h>

extern YSNPTR yylval;
extern int MsgToStructFlag;
int CurrentInputLineNo=1;
int SavedLineNo;
int CurrentOutputLineNo=0;
char CurrentFileName[2*FILENAMELENGTH];
char SavedFileName[2*FILENAMELENGTH];
int OutputLineLength=0;
extern FILE *outfile;

extern SYMTABPTR GlobalModuleSearch();
extern char token[];
int PrevToken=0;

#define CREATE 1
#define NOCREATE 0

#ifdef yywrap
#undef yywrap
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 43 "xl-lexsp.flex"


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 157 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 596 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "xl-lexsp.flex"
{ strcpy(token,yytext);return(PrevToken=AT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "xl-lexsp.flex"
{ mywriteoutput("?",NOCREATE);strcpy(token,yytext);return(PrevToken=QUESTION); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "xl-lexsp.flex"
{ strcpy(token,yytext);return(PrevToken=COLON); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "xl-lexsp.flex"
{ mywriteoutput("|",NOCREATE);strcpy(token,yytext);return(PrevToken=OR); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "xl-lexsp.flex"
{ mywriteoutput("&",NOCREATE);strcpy(token,yytext);return(PrevToken=AND); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "xl-lexsp.flex"
{ mywriteoutput("^",NOCREATE);strcpy(token,yytext);return(PrevToken=HAT); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "xl-lexsp.flex"
{ mywriteoutput("+",NOCREATE);strcpy(token,yytext);return(PrevToken=PLUS); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "xl-lexsp.flex"
{ mywriteoutput("-",NOCREATE);strcpy(token,yytext);return(PrevToken=MINUS); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "xl-lexsp.flex"
{ mywriteoutput("*",NOCREATE);strcpy(token,yytext);return(PrevToken=MULT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "xl-lexsp.flex"
{ mywriteoutput("/",NOCREATE);strcpy(token,yytext);return(PrevToken=DIV); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "xl-lexsp.flex"
{ mywriteoutput("%",NOCREATE);strcpy(token,yytext);return(PrevToken=MOD); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "xl-lexsp.flex"
{ mywriteoutput("(",NOCREATE);strcpy(token,yytext);return(PrevToken=L_PAREN); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "xl-lexsp.flex"
{ mywriteoutput(")",NOCREATE);strcpy(token,yytext);return(PrevToken=R_PAREN); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "xl-lexsp.flex"
{ mywriteoutput("[",NOCREATE);strcpy(token,yytext);return(PrevToken=L_SQUARE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "xl-lexsp.flex"
{ mywriteoutput("]",NOCREATE);strcpy(token,yytext);return(PrevToken=R_SQUARE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "xl-lexsp.flex"
{ mywriteoutput(".",NOCREATE);strcpy(token,yytext);return(PrevToken=DOT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "xl-lexsp.flex"
{ mywriteoutput("!",NOCREATE);strcpy(token,yytext);return(PrevToken=EXCLAIM); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "xl-lexsp.flex"
{ mywriteoutput("~",NOCREATE);strcpy(token,yytext);return(PrevToken=TILDE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "xl-lexsp.flex"
{ mywriteoutput("->",NOCREATE);strcpy(token,yytext);return(PrevToken=POINTERREF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "xl-lexsp.flex"
{ mywriteoutput("++",CREATE);strcpy(token,yytext);return(PrevToken=INCDEC); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "xl-lexsp.flex"
{ mywriteoutput("--",CREATE);strcpy(token,yytext);return(PrevToken=INCDEC); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "xl-lexsp.flex"
{ mywriteoutput("<<",CREATE);strcpy(token,yytext);return(PrevToken=SHIFT); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "xl-lexsp.flex"
{ mywriteoutput(">>",CREATE);strcpy(token,yytext);return(PrevToken=SHIFT); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "xl-lexsp.flex"
{ mywriteoutput("<",CREATE);strcpy(token,yytext);return(PrevToken=COMPARE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "xl-lexsp.flex"
{ mywriteoutput(">",CREATE);strcpy(token,yytext);return(PrevToken=COMPARE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "xl-lexsp.flex"
{ mywriteoutput("<=",CREATE);strcpy(token,yytext);return(PrevToken=COMPARE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "xl-lexsp.flex"
{ mywriteoutput(">=",CREATE);strcpy(token,yytext);return(PrevToken=COMPARE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "xl-lexsp.flex"
{ mywriteoutput("==",NOCREATE);strcpy(token,yytext);return(PrevToken=EQUALEQUAL); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "xl-lexsp.flex"
{ mywriteoutput("!=",NOCREATE);strcpy(token,yytext);return(PrevToken=NOTEQUAL); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "xl-lexsp.flex"
{ mywriteoutput("&&",NOCREATE);strcpy(token,yytext);return(PrevToken=ANDAND); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "xl-lexsp.flex"
{ mywriteoutput("||",NOCREATE);strcpy(token,yytext);return(PrevToken=OROR); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "xl-lexsp.flex"
{ mywriteoutput("=",NOCREATE);strcpy(token,yytext);return(PrevToken=EQUAL); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "xl-lexsp.flex"
{ mywriteoutput("+=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "xl-lexsp.flex"
{ mywriteoutput("-=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "xl-lexsp.flex"
{ mywriteoutput("*=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "xl-lexsp.flex"
{ mywriteoutput("/=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "xl-lexsp.flex"
{ mywriteoutput("%=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "xl-lexsp.flex"
{ mywriteoutput(">>=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "xl-lexsp.flex"
{ mywriteoutput("<<=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "xl-lexsp.flex"
{ mywriteoutput("&=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "xl-lexsp.flex"
{ mywriteoutput("|=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "xl-lexsp.flex"
{ mywriteoutput("^=",CREATE);strcpy(token,yytext);return(PrevToken=ASGNOP); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "xl-lexsp.flex"
{ mywriteoutput(",",NOCREATE);strcpy(token,yytext);return(PrevToken=COMMA); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "xl-lexsp.flex"
{ strcpy(token,yytext);return(PrevToken=L_BRACE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "xl-lexsp.flex"
{ strcpy(token,yytext);return(PrevToken=R_BRACE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "xl-lexsp.flex"
{ mywriteoutput(";",NOCREATE);strcpy(token,yytext);return(PrevToken=SEMICOLON); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "xl-lexsp.flex"
{ int i,count=0;
		
		  strcpy(token,yytext);
		  for (i=0;i<yyleng;i++)
			if (yytext[i]=='\n') count++;
		  CurrentInputLineNo += count;
		  mywriteoutput(",{ ",NOCREATE);return(PrevToken=COMMA_L_BRACE); 
		}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "xl-lexsp.flex"
{ int i,count=0;
		
		  for (i=0;i<yyleng;i++)
			if (yytext[i]=='\n') count++;
		  CurrentInputLineNo += count;
		  mywriteoutput(",} ",NOCREATE);return(PrevToken=COMMA_R_BRACE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 106 "xl-lexsp.flex"
{ int i=0,j=0;
						  char temp[FILENAMELENGTH];

						  while ((yytext[i]<'0')||
						         (yytext[i]>'9')) 
							i++;
						  while ((yytext[i]>='0') &&
							 (yytext[i]<='9'))
							temp[j++]=yytext[i++];
						  temp[j]='\0';
						  CurrentInputLineNo = 
							atoi(temp);
						  while (yytext[i]!='\"')
							i++;
						  yytext[yyleng-1]='\0';
						  strcpy(CurrentFileName,
								yytext+i+1);
						}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 125 "xl-lexsp.flex"
{ int i=0,j=0;
						  char temp[FILENAMELENGTH];

						  while ((yytext[i]<'0')||
						         (yytext[i]>'9')) 
							i++;
						  while ((yytext[i]>='0') &&
							 (yytext[i]<='9'))
							temp[j++]=yytext[i++];
						  temp[j]='\0';
						  CurrentInputLineNo = 
							atoi(temp);
						}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 139 "xl-lexsp.flex"
{ int retvalue;
		
			      strcpy(token,yytext);
			      yylval=GetYSN();
			      yylval->string=MakeString(yytext);
			      if ((retvalue=SearchKey(yytext)) == -1)
				  return(PrevToken=TypeToToken(IDType(yytext)));
			      else { if (IsKey(yytext))
					writeoutput(yytext,NOFREE);
				     if (retvalue==0) return(IDENTIFIER);
				     if (MsgToStructFlag && (retvalue==MESSAGE))
					{ retvalue=STRUCT;
					  writeoutput("struct ",NOFREE);
					}
				     if (retvalue==MAIN)
					if (PrevToken!=CHARE)
						return(PrevToken=IDENTIFIER);
			 	     return(PrevToken=retvalue);
				   }
			    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 160 "xl-lexsp.flex"
{ SYMTABPTR worksymtab;
			  char *modname,*name,*string;
			  int i;char ch;

			  strcpy(token,yytext);
			  yylval=GetYSN();
			  i=0;ch=yytext[0];
			  string=GetMem(strlen(yytext));
			  while ((ch!=' ')&&(ch!='\t')&&(ch!='\n')&&(ch!=':'))
				{ string[i]=ch;ch=yytext[++i]; }
			  string[i]='\0';
			  modname=yylval->modstring=MakeString(string);
			  while ((ch==' ')||(ch=='\t')||(ch=='\n')||(ch==':'))
				{ if (ch=='\n') CurrentInputLineNo++;
				  ch=yytext[++i]; 
				}
			  name=yylval->string=MakeString(yytext+i);

			  worksymtab=GlobalModuleSearch(name,modname);
			  if (worksymtab==NULL)
				{ error("Bad Module Reference",EXIT);
				  return(ID_DCOLON_ID);
				}
			  switch (TypeToToken(worksymtab->idtype))
			  { case IDENTIFIER : return(ID_DCOLON_ID);
			    case TYPE_IDENTIFIER : return(TYPE_IDENTIFIER);
			  }
			}
	YY_BREAK
case 53:
#line 190 "xl-lexsp.flex"
case 54:
#line 191 "xl-lexsp.flex"
case 55:
#line 192 "xl-lexsp.flex"
case 56:
#line 193 "xl-lexsp.flex"
case 57:
#line 194 "xl-lexsp.flex"
case 58:
YY_RULE_SETUP
#line 194 "xl-lexsp.flex"
{ mywriteoutput(yytext,CREATE);
				  strcpy(token,yytext);return(PrevToken=NUMBER);                
				}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 198 "xl-lexsp.flex"
{
				mywriteoutput(yytext,CREATE);
		                  strcpy(token,yytext);return(PrevToken=CHAR_CONST);              }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 202 "xl-lexsp.flex"
{ mywriteoutput(yytext,CREATE);
                                  strcpy(token,yytext);return(PrevToken=STRING);
                                }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "xl-lexsp.flex"
{ writeoutput(yytext,NOFREE); }        /* Skip whitespace...*/
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 207 "xl-lexsp.flex"
{ CurrentInputLineNo++; WriteReturn(); 
		/*printf("%d Line\n",yylineno);*/
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 211 "xl-lexsp.flex"
{writeoutput(yytext,NOFREE);
				 	CurrentInputLineNo++;
					WriteReturn();}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 215 "xl-lexsp.flex"
{writeoutput(yytext,NOFREE);
				 	CurrentInputLineNo++;
					WriteReturn();}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 219 "xl-lexsp.flex"
{ error("Lexical Oddity",EXIT); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 221 "xl-lexsp.flex"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 157 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 157 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 156);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 221 "xl-lexsp.flex"


yywrap(){ PrevToken=0; return(1); }

mywriteoutput(string,flag)
char *string;
int flag;
{ if (!flag) return;
  yylval=GetYSN();
  yylval->string=MakeString(string);
}

TypeToToken(type)
int type;
{ switch (type)
  { case TYPENAME :
    case MESSAGENAME : return(TYPE_IDENTIFIER);
    case MODULENAME :
    case CHARENAME  :
    case BOCNAME    :
    case ENTRYNAME  :
    default    : return(IDENTIFIER);
  }
}
