#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from xi-grammar.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 2 "xi-grammar.y"

#include "xi-symbol.h"
#include "EToken.h"
extern int yylex (void) ;
extern unsigned char in_comment;
void yyerror(const char *);
extern unsigned int lineno;
extern int in_bracket,in_braces,in_int_expr;
extern TList<Entry *> *connectEntries;
ModuleList *modlist;
extern int macroDefined(char *str, int istrue);
extern char *python_doc;


#line 17 "xi-grammar.y"
typedef union {
  ModuleList *modlist;
  Module *module;
  ConstructList *conslist;
  Construct *construct;
  TParam *tparam;
  TParamList *tparlist;
  Type *type;
  PtrType *ptype;
  NamedType *ntype;
  FuncType *ftype;
  Readonly *readonly;
  Message *message;
  Chare *chare;
  Entry *entry;
  EntryList *entrylist;
  Parameter *pname;
  ParamList *plist;
  Template *templat;
  TypeList *typelist;
  MemberList *mbrlist;
  Member *member;
  TVar *tvar;
  TVarList *tvarlist;
  Value *val;
  ValueList *vallist;
  MsgVar *mv;
  MsgVarList *mvlist;
  PUPableClass *pupable;
  IncludeFile *includeFile;
  char *strval;
  int intval;
  Chare::attrib_t cattr;
  SdagConstruct *sc;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	MODULE	258
#define	MAINMODULE	259
#define	EXTERN	260
#define	READONLY	261
#define	INITCALL	262
#define	INITNODE	263
#define	INITPROC	264
#define	PUPABLE	265
#define	CHARE	266
#define	MAINCHARE	267
#define	GROUP	268
#define	NODEGROUP	269
#define	ARRAY	270
#define	MESSAGE	271
#define	CLASS	272
#define	INCLUDE	273
#define	STACKSIZE	274
#define	THREADED	275
#define	TEMPLATE	276
#define	SYNC	277
#define	IGET	278
#define	EXCLUSIVE	279
#define	IMMEDIATE	280
#define	SKIPSCHED	281
#define	INLINE	282
#define	VIRTUAL	283
#define	MIGRATABLE	284
#define	CREATEHERE	285
#define	CREATEHOME	286
#define	NOKEEP	287
#define	NOTRACE	288
#define	VOID	289
#define	CONST	290
#define	PACKED	291
#define	VARSIZE	292
#define	ENTRY	293
#define	FOR	294
#define	FORALL	295
#define	WHILE	296
#define	WHEN	297
#define	OVERLAP	298
#define	ATOMIC	299
#define	FORWARD	300
#define	IF	301
#define	ELSE	302
#define	CONNECT	303
#define	PUBLISHES	304
#define	PYTHON	305
#define	LOCAL	306
#define	IDENT	307
#define	NUMBER	308
#define	LITERAL	309
#define	CPROGRAM	310
#define	HASHIF	311
#define	HASHIFDEF	312
#define	INT	313
#define	LONG	314
#define	SHORT	315
#define	CHAR	316
#define	FLOAT	317
#define	DOUBLE	318
#define	UNSIGNED	319


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int MODULE;
static const int MAINMODULE;
static const int EXTERN;
static const int READONLY;
static const int INITCALL;
static const int INITNODE;
static const int INITPROC;
static const int PUPABLE;
static const int CHARE;
static const int MAINCHARE;
static const int GROUP;
static const int NODEGROUP;
static const int ARRAY;
static const int MESSAGE;
static const int CLASS;
static const int INCLUDE;
static const int STACKSIZE;
static const int THREADED;
static const int TEMPLATE;
static const int SYNC;
static const int IGET;
static const int EXCLUSIVE;
static const int IMMEDIATE;
static const int SKIPSCHED;
static const int INLINE;
static const int VIRTUAL;
static const int MIGRATABLE;
static const int CREATEHERE;
static const int CREATEHOME;
static const int NOKEEP;
static const int NOTRACE;
static const int VOID;
static const int CONST;
static const int PACKED;
static const int VARSIZE;
static const int ENTRY;
static const int FOR;
static const int FORALL;
static const int WHILE;
static const int WHEN;
static const int OVERLAP;
static const int ATOMIC;
static const int FORWARD;
static const int IF;
static const int ELSE;
static const int CONNECT;
static const int PUBLISHES;
static const int PYTHON;
static const int LOCAL;
static const int IDENT;
static const int NUMBER;
static const int LITERAL;
static const int CPROGRAM;
static const int HASHIF;
static const int HASHIFDEF;
static const int INT;
static const int LONG;
static const int SHORT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int UNSIGNED;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,MODULE=258
	,MAINMODULE=259
	,EXTERN=260
	,READONLY=261
	,INITCALL=262
	,INITNODE=263
	,INITPROC=264
	,PUPABLE=265
	,CHARE=266
	,MAINCHARE=267
	,GROUP=268
	,NODEGROUP=269
	,ARRAY=270
	,MESSAGE=271
	,CLASS=272
	,INCLUDE=273
	,STACKSIZE=274
	,THREADED=275
	,TEMPLATE=276
	,SYNC=277
	,IGET=278
	,EXCLUSIVE=279
	,IMMEDIATE=280
	,SKIPSCHED=281
	,INLINE=282
	,VIRTUAL=283
	,MIGRATABLE=284
	,CREATEHERE=285
	,CREATEHOME=286
	,NOKEEP=287
	,NOTRACE=288
	,VOID=289
	,CONST=290
	,PACKED=291
	,VARSIZE=292
	,ENTRY=293
	,FOR=294
	,FORALL=295
	,WHILE=296
	,WHEN=297
	,OVERLAP=298
	,ATOMIC=299
	,FORWARD=300
	,IF=301
	,ELSE=302
	,CONNECT=303
	,PUBLISHES=304
	,PYTHON=305
	,LOCAL=306
	,IDENT=307
	,NUMBER=308
	,LITERAL=309
	,CPROGRAM=310
	,HASHIF=311
	,HASHIFDEF=312
	,INT=313
	,LONG=314
	,SHORT=315
	,CHAR=316
	,FLOAT=317
	,DOUBLE=318
	,UNSIGNED=319


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::MODULE=258;
const int YY_parse_CLASS::MAINMODULE=259;
const int YY_parse_CLASS::EXTERN=260;
const int YY_parse_CLASS::READONLY=261;
const int YY_parse_CLASS::INITCALL=262;
const int YY_parse_CLASS::INITNODE=263;
const int YY_parse_CLASS::INITPROC=264;
const int YY_parse_CLASS::PUPABLE=265;
const int YY_parse_CLASS::CHARE=266;
const int YY_parse_CLASS::MAINCHARE=267;
const int YY_parse_CLASS::GROUP=268;
const int YY_parse_CLASS::NODEGROUP=269;
const int YY_parse_CLASS::ARRAY=270;
const int YY_parse_CLASS::MESSAGE=271;
const int YY_parse_CLASS::CLASS=272;
const int YY_parse_CLASS::INCLUDE=273;
const int YY_parse_CLASS::STACKSIZE=274;
const int YY_parse_CLASS::THREADED=275;
const int YY_parse_CLASS::TEMPLATE=276;
const int YY_parse_CLASS::SYNC=277;
const int YY_parse_CLASS::IGET=278;
const int YY_parse_CLASS::EXCLUSIVE=279;
const int YY_parse_CLASS::IMMEDIATE=280;
const int YY_parse_CLASS::SKIPSCHED=281;
const int YY_parse_CLASS::INLINE=282;
const int YY_parse_CLASS::VIRTUAL=283;
const int YY_parse_CLASS::MIGRATABLE=284;
const int YY_parse_CLASS::CREATEHERE=285;
const int YY_parse_CLASS::CREATEHOME=286;
const int YY_parse_CLASS::NOKEEP=287;
const int YY_parse_CLASS::NOTRACE=288;
const int YY_parse_CLASS::VOID=289;
const int YY_parse_CLASS::CONST=290;
const int YY_parse_CLASS::PACKED=291;
const int YY_parse_CLASS::VARSIZE=292;
const int YY_parse_CLASS::ENTRY=293;
const int YY_parse_CLASS::FOR=294;
const int YY_parse_CLASS::FORALL=295;
const int YY_parse_CLASS::WHILE=296;
const int YY_parse_CLASS::WHEN=297;
const int YY_parse_CLASS::OVERLAP=298;
const int YY_parse_CLASS::ATOMIC=299;
const int YY_parse_CLASS::FORWARD=300;
const int YY_parse_CLASS::IF=301;
const int YY_parse_CLASS::ELSE=302;
const int YY_parse_CLASS::CONNECT=303;
const int YY_parse_CLASS::PUBLISHES=304;
const int YY_parse_CLASS::PYTHON=305;
const int YY_parse_CLASS::LOCAL=306;
const int YY_parse_CLASS::IDENT=307;
const int YY_parse_CLASS::NUMBER=308;
const int YY_parse_CLASS::LITERAL=309;
const int YY_parse_CLASS::CPROGRAM=310;
const int YY_parse_CLASS::HASHIF=311;
const int YY_parse_CLASS::HASHIFDEF=312;
const int YY_parse_CLASS::INT=313;
const int YY_parse_CLASS::LONG=314;
const int YY_parse_CLASS::SHORT=315;
const int YY_parse_CLASS::CHAR=316;
const int YY_parse_CLASS::FLOAT=317;
const int YY_parse_CLASS::DOUBLE=318;
const int YY_parse_CLASS::UNSIGNED=319;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		491
#define	YYFLAG		-32768
#define	YYNTBASE	79

#define YYTRANSLATE(x) ((unsigned)(x) <= 319 ? yytranslate[x] : 179)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    75,     2,    73,
    74,    72,     2,    69,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    66,    65,    70,
    78,    71,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    76,     2,    77,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    67,     2,    68,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58,    59,    60,    61,    62,    63,    64
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     6,     7,     9,    10,    12,    14,    16,
    21,    25,    29,    31,    36,    37,    40,    46,    49,    52,
    56,    59,    62,    65,    68,    71,    73,    75,    77,    79,
    81,    83,    87,    88,    90,    91,    95,    97,    99,   101,
   103,   106,   109,   113,   117,   120,   123,   126,   128,   130,
   133,   135,   138,   141,   143,   145,   148,   151,   154,   163,
   165,   167,   169,   171,   174,   177,   180,   182,   184,   186,
   190,   191,   194,   199,   205,   206,   208,   209,   213,   215,
   219,   221,   223,   224,   228,   230,   234,   235,   237,   239,
   240,   244,   246,   250,   252,   254,   260,   262,   265,   269,
   276,   277,   280,   282,   286,   292,   298,   304,   310,   315,
   319,   326,   333,   339,   345,   351,   357,   363,   368,   376,
   377,   380,   381,   384,   387,   391,   394,   398,   400,   404,
   409,   412,   415,   418,   421,   424,   426,   431,   432,   435,
   438,   441,   444,   447,   451,   455,   459,   463,   470,   474,
   481,   485,   492,   494,   498,   500,   503,   505,   513,   519,
   521,   523,   524,   528,   530,   534,   536,   538,   540,   542,
   544,   546,   548,   550,   552,   554,   556,   558,   561,   563,
   565,   567,   568,   570,   574,   575,   577,   583,   589,   595,
   600,   604,   606,   608,   610,   613,   618,   622,   624,   628,
   632,   635,   636,   640,   641,   643,   647,   649,   652,   654,
   657,   658,   663,   665,   669,   671,   672,   679,   688,   693,
   697,   703,   708,   720,   730,   743,   758,   765,   774,   780,
   788,   792,   796,   797,   800,   805,   807,   811,   813,   815,
   818,   824,   826,   830,   832,   834,   837
};

static const short yyrhs[] = {    80,
     0,     0,    85,    80,     0,     0,     5,     0,     0,    65,
     0,    52,     0,    52,     0,    84,    66,    66,    52,     0,
     3,    83,    86,     0,     4,    83,    86,     0,    65,     0,
    67,    87,    68,    82,     0,     0,    88,    87,     0,    81,
    67,    87,    68,    82,     0,    81,    85,     0,    81,   141,
     0,    81,   120,    65,     0,    81,   123,     0,    81,   124,
     0,    81,   125,     0,    81,   127,     0,    81,   138,     0,
   177,     0,   178,     0,   101,     0,    53,     0,    54,     0,
    89,     0,    89,    69,    90,     0,     0,    90,     0,     0,
    70,    91,    71,     0,    58,     0,    59,     0,    60,     0,
    61,     0,    64,    58,     0,    64,    59,     0,    64,    59,
    58,     0,    64,    59,    59,     0,    64,    60,     0,    64,
    61,     0,    59,    59,     0,    62,     0,    63,     0,    59,
    63,     0,    34,     0,    83,    92,     0,    84,    92,     0,
    93,     0,    95,     0,    96,    72,     0,    97,    72,     0,
    98,    72,     0,   100,    73,    72,    83,    74,    73,   159,
    74,     0,    96,     0,    97,     0,    98,     0,    99,     0,
    35,   100,     0,   100,    35,     0,   100,    75,     0,   100,
     0,    53,     0,    84,     0,    76,   102,    77,     0,     0,
   103,   104,     0,     6,   101,    84,   104,     0,     6,    16,
    96,    72,    83,     0,     0,    34,     0,     0,    76,   109,
    77,     0,   110,     0,   110,    69,   109,     0,    36,     0,
    37,     0,     0,    76,   112,    77,     0,   117,     0,   117,
    69,   112,     0,     0,    54,     0,    50,     0,     0,    76,
   116,    77,     0,   114,     0,   114,    69,   116,     0,    29,
     0,    50,     0,   101,    83,    76,    77,    65,     0,   118,
     0,   118,   119,     0,    16,   108,    94,     0,    16,   108,
    94,    67,   119,    68,     0,     0,    66,   122,     0,    94,
     0,    94,    69,   122,     0,    11,   111,    94,   121,   139,
     0,    12,   111,    94,   121,   139,     0,    13,   111,    94,
   121,   139,     0,    14,   111,    94,   121,   139,     0,    76,
    53,    83,    77,     0,    76,    83,    77,     0,    15,   115,
   126,    94,   121,   139,     0,    15,   126,   115,    94,   121,
   139,     0,    11,   111,    83,   121,   139,     0,    12,   111,
    83,   121,   139,     0,    13,   111,    83,   121,   139,     0,
    14,   111,    83,   121,   139,     0,    15,   126,    83,   121,
   139,     0,    16,   108,    83,    65,     0,    16,   108,    83,
    67,   119,    68,    65,     0,     0,    78,   101,     0,     0,
    78,    53,     0,    78,    54,     0,    17,    83,   133,     0,
    99,   134,     0,   101,    83,   134,     0,   135,     0,   135,
    69,   136,     0,    21,    70,   136,    71,     0,   137,   128,
     0,   137,   129,     0,   137,   130,     0,   137,   131,     0,
   137,   132,     0,    65,     0,    67,   140,    68,    82,     0,
     0,   146,   140,     0,   105,    65,     0,   106,    65,     0,
   143,    65,     0,   142,    65,     0,    10,   144,    65,     0,
    18,   145,    65,     0,    17,    83,    65,     0,     8,   107,
    84,     0,     8,   107,    84,    73,   107,    74,     0,     7,
   107,    84,     0,     7,   107,    84,    73,   107,    74,     0,
     9,   107,    84,     0,     9,   107,    84,    73,   107,    74,
     0,    84,     0,    84,    69,   144,     0,    54,     0,   147,
    65,     0,   141,     0,    38,   149,   148,    83,   160,   161,
   162,     0,    38,   149,    83,   160,   162,     0,    34,     0,
    97,     0,     0,    76,   150,    77,     0,   151,     0,   151,
    69,   150,     0,    20,     0,    22,     0,    23,     0,    24,
     0,    30,     0,    31,     0,    32,     0,    33,     0,    25,
     0,    26,     0,    27,     0,    51,     0,    50,   113,     0,
    54,     0,    53,     0,    84,     0,     0,    55,     0,    55,
    69,   153,     0,     0,    55,     0,    55,    76,   154,    77,
   154,     0,    55,    67,   154,    68,   154,     0,    55,    73,
   153,    74,   154,     0,    73,   154,    74,   154,     0,   101,
    83,    76,     0,    67,     0,    68,     0,   101,     0,   101,
    83,     0,   101,    83,    78,   152,     0,   155,   154,    77,
     0,   158,     0,   158,    69,   159,     0,    73,   159,    74,
     0,    73,    74,     0,     0,    19,    78,    53,     0,     0,
   168,     0,    67,   163,    68,     0,   168,     0,   168,   163,
     0,   168,     0,   168,   163,     0,     0,    49,    73,   166,
    74,     0,    52,     0,    52,    69,   166,     0,    54,     0,
     0,    44,   167,   156,   154,   157,   165,     0,    48,    73,
    52,   160,    74,   156,   154,    68,     0,    42,   174,    67,
    68,     0,    42,   174,   168,     0,    42,   174,    67,   163,
    68,     0,    43,    67,   164,    68,     0,    39,   172,   154,
    65,   154,    65,   154,   171,    67,   163,    68,     0,    39,
   172,   154,    65,   154,    65,   154,   171,   168,     0,    40,
    76,    52,    77,   172,   154,    66,   154,    69,   154,   171,
   168,     0,    40,    76,    52,    77,   172,   154,    66,   154,
    69,   154,   171,    67,   163,    68,     0,    46,   172,   154,
   171,   168,   169,     0,    46,   172,   154,   171,    67,   163,
    68,   169,     0,    41,   172,   154,   171,   168,     0,    41,
   172,   154,   171,    67,   163,    68,     0,    45,   170,    65,
     0,   156,   154,   157,     0,     0,    47,   168,     0,    47,
    67,   163,    68,     0,    52,     0,    52,    69,   170,     0,
    74,     0,    73,     0,    52,   160,     0,    52,   175,   154,
   176,   160,     0,   173,     0,   173,    69,   174,     0,    76,
     0,    77,     0,    56,    83,     0,    57,    83,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   133,   137,   141,   145,   147,   151,   153,   157,   161,   163,
   171,   175,   182,   184,   188,   190,   194,   196,   198,   200,
   202,   204,   206,   208,   210,   212,   214,   218,   220,   222,
   226,   228,   232,   234,   238,   240,   244,   246,   248,   250,
   252,   254,   256,   258,   260,   262,   264,   266,   268,   270,
   272,   276,   277,   279,   281,   285,   289,   291,   295,   299,
   301,   303,   305,   308,   310,   314,   316,   320,   322,   326,
   330,   332,   336,   340,   344,   346,   350,   352,   362,   364,
   368,   370,   374,   376,   380,   382,   386,   388,   392,   396,
   398,   402,   404,   408,   410,   414,   418,   420,   424,   426,
   430,   432,   436,   438,   442,   444,   448,   452,   456,   462,
   466,   468,   472,   474,   478,   482,   486,   490,   492,   496,
   498,   502,   504,   506,   510,   512,   514,   518,   520,   524,
   528,   530,   532,   534,   536,   540,   542,   546,   565,   569,
   571,   573,   574,   576,   578,   580,   584,   586,   588,   591,
   596,   598,   602,   604,   608,   612,   614,   618,   629,   642,
   644,   648,   650,   654,   656,   660,   662,   664,   666,   668,
   670,   672,   674,   676,   678,   680,   682,   684,   688,   690,
   692,   696,   698,   700,   708,   710,   712,   718,   724,   730,
   738,   745,   753,   760,   762,   764,   766,   773,   775,   779,
   781,   785,   787,   791,   793,   795,   799,   801,   805,   807,
   811,   813,   817,   819,   823,   825,   829,   834,   848,   850,
   852,   854,   856,   859,   862,   865,   868,   870,   872,   874,
   876,   878,   884,   886,   888,   891,   893,   897,   901,   905,
   913,   921,   923,   927,   930,   934,   938
};

static const char * const yytname[] = {   "$","error","$illegal.","MODULE","MAINMODULE",
"EXTERN","READONLY","INITCALL","INITNODE","INITPROC","PUPABLE","CHARE","MAINCHARE",
"GROUP","NODEGROUP","ARRAY","MESSAGE","CLASS","INCLUDE","STACKSIZE","THREADED",
"TEMPLATE","SYNC","IGET","EXCLUSIVE","IMMEDIATE","SKIPSCHED","INLINE","VIRTUAL",
"MIGRATABLE","CREATEHERE","CREATEHOME","NOKEEP","NOTRACE","VOID","CONST","PACKED",
"VARSIZE","ENTRY","FOR","FORALL","WHILE","WHEN","OVERLAP","ATOMIC","FORWARD",
"IF","ELSE","CONNECT","PUBLISHES","PYTHON","LOCAL","IDENT","NUMBER","LITERAL",
"CPROGRAM","HASHIF","HASHIFDEF","INT","LONG","SHORT","CHAR","FLOAT","DOUBLE",
"UNSIGNED","';'","':'","'{'","'}'","','","'<'","'>'","'*'","'('","')'","'&'",
"'['","']'","'='","File","ModuleEList","OptExtern","OptSemiColon","Name","QualName",
"Module","ConstructEList","ConstructList","Construct","TParam","TParamList",
"TParamEList","OptTParams","BuiltinType","NamedType","QualNamedType","SimpleType",
"OnePtrType","PtrType","FuncType","BaseType","Type","ArrayDim","Dim","DimList",
"Readonly","ReadonlyMsg","OptVoid","MAttribs","MAttribList","MAttrib","CAttribs",
"CAttribList","PythonOptions","ArrayAttrib","ArrayAttribs","ArrayAttribList",
"CAttrib","Var","VarList","Message","OptBaseList","BaseList","Chare","Group",
"NodeGroup","ArrayIndexType","Array","TChare","TGroup","TNodeGroup","TArray",
"TMessage","OptTypeInit","OptNameInit","TVar","TVarList","TemplateSpec","Template",
"MemberEList","MemberList","NonEntryMember","InitNode","InitProc","PUPableClass",
"IncludeFile","Member","Entry","EReturn","EAttribs","EAttribList","EAttrib",
"DefaultParameter","CPROGRAM_List","CCode","ParamBracketStart","ParamBraceStart",
"ParamBraceEnd","Parameter","ParamList","EParameters","OptStackSize","OptSdagCode",
"Slist","Olist","OptPubList","PublishesList","OptTraceName","SingleConstruct",
"HasElse","ForwardList","EndIntExpr","StartIntExpr","SEntry","SEntryList","SParamBracketStart",
"SParamBracketEnd","HashIFComment","HashIFDefComment",""
};
#endif

static const short yyr1[] = {     0,
    79,    80,    80,    81,    81,    82,    82,    83,    84,    84,
    85,    85,    86,    86,    87,    87,    88,    88,    88,    88,
    88,    88,    88,    88,    88,    88,    88,    89,    89,    89,
    90,    90,    91,    91,    92,    92,    93,    93,    93,    93,
    93,    93,    93,    93,    93,    93,    93,    93,    93,    93,
    93,    94,    95,    96,    96,    97,    98,    98,    99,   100,
   100,   100,   100,   100,   100,   101,   101,   102,   102,   103,
   104,   104,   105,   106,   107,   107,   108,   108,   109,   109,
   110,   110,   111,   111,   112,   112,   113,   113,   114,   115,
   115,   116,   116,   117,   117,   118,   119,   119,   120,   120,
   121,   121,   122,   122,   123,   123,   124,   125,   126,   126,
   127,   127,   128,   128,   129,   130,   131,   132,   132,   133,
   133,   134,   134,   134,   135,   135,   135,   136,   136,   137,
   138,   138,   138,   138,   138,   139,   139,   140,   140,   141,
   141,   141,   141,   141,   141,   141,   142,   142,   142,   142,
   143,   143,   144,   144,   145,   146,   146,   147,   147,   148,
   148,   149,   149,   150,   150,   151,   151,   151,   151,   151,
   151,   151,   151,   151,   151,   151,   151,   151,   152,   152,
   152,   153,   153,   153,   154,   154,   154,   154,   154,   154,
   155,   156,   157,   158,   158,   158,   158,   159,   159,   160,
   160,   161,   161,   162,   162,   162,   163,   163,   164,   164,
   165,   165,   166,   166,   167,   167,   168,   168,   168,   168,
   168,   168,   168,   168,   168,   168,   168,   168,   168,   168,
   168,   168,   169,   169,   169,   170,   170,   171,   172,   173,
   173,   174,   174,   175,   176,   177,   178
};

static const short yyr2[] = {     0,
     1,     0,     2,     0,     1,     0,     1,     1,     1,     4,
     3,     3,     1,     4,     0,     2,     5,     2,     2,     3,
     2,     2,     2,     2,     2,     1,     1,     1,     1,     1,
     1,     3,     0,     1,     0,     3,     1,     1,     1,     1,
     2,     2,     3,     3,     2,     2,     2,     1,     1,     2,
     1,     2,     2,     1,     1,     2,     2,     2,     8,     1,
     1,     1,     1,     2,     2,     2,     1,     1,     1,     3,
     0,     2,     4,     5,     0,     1,     0,     3,     1,     3,
     1,     1,     0,     3,     1,     3,     0,     1,     1,     0,
     3,     1,     3,     1,     1,     5,     1,     2,     3,     6,
     0,     2,     1,     3,     5,     5,     5,     5,     4,     3,
     6,     6,     5,     5,     5,     5,     5,     4,     7,     0,
     2,     0,     2,     2,     3,     2,     3,     1,     3,     4,
     2,     2,     2,     2,     2,     1,     4,     0,     2,     2,
     2,     2,     2,     3,     3,     3,     3,     6,     3,     6,
     3,     6,     1,     3,     1,     2,     1,     7,     5,     1,
     1,     0,     3,     1,     3,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     2,     1,     1,
     1,     0,     1,     3,     0,     1,     5,     5,     5,     4,
     3,     1,     1,     1,     2,     4,     3,     1,     3,     3,
     2,     0,     3,     0,     1,     3,     1,     2,     1,     2,
     0,     4,     1,     3,     1,     0,     6,     8,     4,     3,
     5,     4,    11,     9,    12,    14,     6,     8,     5,     7,
     3,     3,     0,     2,     4,     1,     3,     1,     1,     2,
     5,     1,     3,     1,     1,     2,     2
};

static const short yydefact[] = {     2,
     0,     0,     1,     2,     8,     0,     0,     3,    13,     4,
    11,    12,     5,     0,     0,     0,     0,     4,    26,    27,
   246,   247,     0,    75,    75,    75,     0,    83,    83,    83,
    83,     0,    77,     0,     0,     0,     4,    18,     0,     0,
     0,    21,    22,    23,    24,     0,    25,    19,     0,     0,
     6,    16,     0,    51,     0,     9,    37,    38,    39,    40,
    48,    49,     0,    35,    54,    55,    60,    61,    62,    63,
    67,     0,    76,     0,     0,     0,   153,     0,     0,     0,
     0,     0,     0,     0,     0,    90,     0,     0,     0,   155,
     0,     0,     0,   140,   141,    20,    83,    83,    83,    83,
     0,    77,   131,   132,   133,   134,   135,   143,   142,     7,
    14,     0,    64,    47,    50,    41,    42,    45,    46,     0,
    33,    53,    56,    57,    58,    65,     0,    66,    71,   149,
   147,   151,     0,   144,    94,    95,     0,    85,    35,   101,
   101,   101,   101,    89,     0,     0,    92,     0,     0,     0,
     0,     0,    81,    82,     0,    79,    99,   146,   145,     0,
    63,     0,   128,     0,     6,     0,     0,     0,     0,     0,
     0,     0,    43,    44,     0,    29,    30,    31,    34,     0,
    28,     0,     0,    71,    73,    75,    75,    75,   154,    84,
     0,    52,     0,     0,     0,     0,     0,     0,   110,     0,
    91,   101,   101,    78,     0,     0,   120,     0,   126,   122,
     0,   130,    17,   101,   101,   101,   101,   101,     0,    74,
    10,     0,    36,     0,    68,    69,     0,    72,     0,     0,
     0,    86,   103,   102,   136,   138,   105,   106,   107,   108,
   109,    93,     0,     0,    80,     0,    97,     0,     0,   125,
   123,   124,   127,   129,     0,     0,     0,     0,     0,   118,
     0,    32,     0,    70,   150,   148,   152,     0,   162,     0,
   157,   138,     0,   111,   112,     0,    98,   100,   121,   113,
   114,   115,   116,   117,     0,     0,   104,     0,     0,     6,
   139,   156,     0,     0,   194,   185,   198,     0,   166,   167,
   168,   169,   174,   175,   176,   170,   171,   172,   173,    87,
   177,     0,   164,    51,     9,     0,     0,   161,     0,   137,
     0,   119,   195,   186,   185,     0,     0,    59,    88,   178,
   163,     0,     0,   204,     0,    96,   191,     0,   185,   182,
   185,     0,   197,   199,   165,   201,     0,     0,     0,     0,
     0,     0,   216,     0,     0,     0,   192,   185,   159,   205,
   202,   180,   179,   181,   196,     0,   183,     0,     0,   185,
   200,   239,   185,     0,   185,     0,   242,     0,     0,   215,
     0,   236,     0,   185,     0,   192,     0,   207,     0,     0,
   204,   185,   182,   185,   185,   190,     0,     0,     0,   244,
   240,   185,     0,   192,   220,     0,   209,   185,     0,   231,
     0,     0,   206,   208,   193,   232,     0,   158,   188,   184,
   189,   187,   185,     0,   238,     0,     0,   243,   219,     0,
   222,   210,     0,   237,     0,     0,   203,     0,   185,   192,
   229,   245,     0,   221,   211,   192,   233,     0,   185,     0,
     0,   241,     0,   217,     0,     0,   227,   185,     0,   185,
   230,     0,   233,   192,   234,     0,     0,     0,   213,     0,
   228,     0,   218,   192,   224,   185,     0,   212,   235,     0,
     0,   214,   223,     0,   192,   225,     0,   226,     0,     0,
     0
};

static const short yydefgoto[] = {   489,
     3,    16,   111,   139,    64,     4,    11,    17,    18,   178,
   179,   180,   122,    65,   233,    66,    67,    68,    69,    70,
    71,   246,   227,   184,   185,    39,    40,    74,    88,   155,
   156,    80,   137,   330,   147,    85,   148,   138,   247,   248,
    41,   194,   234,    42,    43,    44,    86,    45,   103,   104,
   105,   106,   107,   250,   209,   163,   164,    46,    47,   237,
   270,   271,    49,    50,    78,    91,   272,   273,   319,   289,
   312,   313,   365,   368,   326,   296,   358,   416,   297,   298,
   334,   391,   359,   387,   406,   454,   470,   381,   388,   457,
   383,   426,   373,   377,   378,   402,   443,    19,    20
};

static const short yypact[] = {    85,
   -26,   -26,-32768,    85,-32768,    47,    47,-32768,-32768,    25,
-32768,-32768,-32768,   -26,   -26,   207,   -33,    25,-32768,-32768,
-32768,-32768,   219,    18,    18,    18,     7,    51,    51,    51,
    51,    59,    74,   -26,    98,    84,    25,-32768,   110,   112,
   121,-32768,-32768,-32768,-32768,   184,-32768,-32768,   126,   147,
   164,-32768,   347,-32768,   328,-32768,-32768,    28,-32768,-32768,
-32768,-32768,   124,    35,-32768,-32768,   162,   166,   168,-32768,
   -29,     7,-32768,     7,     7,     7,    34,   176,   -21,   -26,
   -26,   -26,   -26,    26,   167,   170,   120,   -26,   177,-32768,
   182,   238,   196,-32768,-32768,-32768,    51,    51,    51,    51,
   167,    74,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   172,   -16,-32768,-32768,-32768,   105,-32768,-32768,   200,
   315,-32768,-32768,-32768,-32768,-32768,   197,-32768,   -13,   -11,
    49,    58,     7,-32768,-32768,-32768,   191,   201,   205,   210,
   210,   210,   210,-32768,   -26,   209,   218,   212,   127,   -26,
   241,   -26,-32768,-32768,   215,   224,   228,-32768,-32768,   -26,
   -47,   -26,   236,   235,   164,   -26,   -26,   -26,   -26,   -26,
   -26,   -26,-32768,-32768,   255,-32768,-32768,   240,-32768,   239,
-32768,   -26,   149,   243,-32768,    18,    18,    18,-32768,-32768,
   -21,-32768,   -26,    75,    75,    75,    75,   234,-32768,   241,
-32768,   210,   210,-32768,   120,   328,   237,   173,-32768,   242,
   238,-32768,-32768,   210,   210,   210,   210,   210,    78,-32768,
-32768,   315,-32768,   248,-32768,   246,   247,-32768,   249,   251,
   252,-32768,   266,-32768,-32768,   111,-32768,-32768,-32768,-32768,
-32768,-32768,    75,    75,-32768,   -26,   328,   274,   328,-32768,
-32768,-32768,-32768,-32768,    75,    75,    75,    75,    75,-32768,
   328,-32768,   244,-32768,-32768,-32768,-32768,   -26,   272,   283,
-32768,   111,   287,-32768,-32768,   277,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   286,   328,-32768,   314,   360,   164,
-32768,-32768,   278,   291,   -26,   -37,   288,   284,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,   262,
-32768,   282,   292,   308,   293,   297,   162,-32768,   -26,-32768,
   306,-32768,   -12,    -2,   -37,   295,   328,-32768,-32768,-32768,
-32768,   314,   269,   386,   297,-32768,-32768,   179,   -37,   327,
   -37,   309,-32768,-32768,-32768,-32768,   310,   312,   317,   312,
   343,   329,   344,   345,   312,   330,   396,   -37,-32768,-32768,
   381,-32768,-32768,   246,-32768,   333,   335,   339,   325,   -37,
-32768,-32768,   -37,   362,   -37,    40,   346,   406,   396,-32768,
   349,   348,   368,   -37,   391,-32768,   437,   396,   438,   429,
   386,   -37,   327,   -37,   -37,-32768,   443,   432,   440,-32768,
-32768,   -37,   343,   217,-32768,   442,   396,   -37,   345,-32768,
   440,   297,-32768,-32768,-32768,-32768,   458,-32768,-32768,-32768,
-32768,-32768,   -37,   312,-32768,   416,   435,-32768,-32768,   447,
-32768,-32768,   438,-32768,   426,   444,-32768,   451,   -37,   396,
-32768,-32768,   297,-32768,   468,   396,   472,   349,   -37,   454,
   453,-32768,   449,-32768,   457,   436,-32768,   -37,   440,   -37,
-32768,   474,   472,   396,-32768,   459,   446,   455,   460,   461,
-32768,   462,-32768,   396,-32768,   -37,   474,-32768,-32768,   463,
   440,-32768,-32768,   456,   396,-32768,   464,-32768,   528,   533,
-32768
};

static const short yypgoto[] = {-32768,
   530,-32768,  -160,    -1,   -25,   520,   531,     5,-32768,-32768,
   318,-32768,   398,-32768,   -43,-32768,   -50,   250,-32768,   -85,
   486,   -19,-32768,-32768,   358,-32768,-32768,   -14,   441,   340,
-32768,    39,   353,-32768,-32768,   465,   350,-32768,-32768,  -227,
-32768,    -9,   279,-32768,-32768,-32768,   -53,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,   336,-32768,   337,-32768,-32768,    -7,
   280,   537,-32768,-32768,   421,-32768,-32768,-32768,-32768,-32768,
   223,-32768,-32768,   156,  -298,-32768,  -364,   123,-32768,  -180,
  -320,-32768,   169,  -379,-32768,-32768,    80,-32768,  -280,    95,
   150,  -401,  -334,-32768,   158,-32768,-32768,-32768,-32768
};


#define	YYLAST		561


static const short yytable[] = {     6,
     7,    77,   112,    72,   213,   126,   161,   135,   414,   435,
    75,    76,    21,    22,   361,   375,   408,   324,   126,   277,
   384,  -122,    52,  -122,   430,     5,   342,   432,   136,    13,
   208,   150,    89,   285,    51,   325,   140,   141,   142,   143,
   366,    93,   369,   127,   157,   128,   129,   170,   130,   131,
   132,    73,   120,   360,   120,   401,   127,   467,    56,   389,
   451,   186,   183,   337,   339,   338,   455,    81,    82,    83,
   340,   396,   162,   341,   397,   144,   399,     5,   145,   484,
    14,    15,   146,   458,   472,   411,   114,     1,     2,   439,
   115,   436,   -15,   419,   480,   421,   422,   405,   407,   120,
   120,   181,   133,   427,   121,   487,   202,    77,   203,   433,
   360,     9,   333,    10,   120,   400,    23,    24,    25,    26,
    27,   187,   452,   120,   438,   161,    79,    34,    35,   320,
   188,   195,   196,   197,    84,   166,   167,   168,   169,   235,
   450,   236,   260,   198,   261,   441,   344,   146,   269,    87,
   459,    90,   347,    92,   447,   153,   154,   226,   207,   466,
   210,   468,   173,   174,   214,   215,   216,   217,   218,   219,
   220,   229,   230,   231,    94,   465,    95,   481,     5,   145,
   224,   116,   117,   118,   119,    96,   475,   238,   239,   240,
   108,   162,   243,   244,    97,    98,    99,   100,   101,   102,
    56,   225,   181,   486,   255,   256,   257,   258,   259,     1,
     2,   109,    23,    24,    25,    26,    27,    28,    29,    30,
    31,    32,    33,    34,    35,   251,   252,    36,   110,   279,
    56,   362,   363,   123,    53,   274,   275,   124,   317,   125,
   134,   158,   149,   172,   276,   151,   159,   280,   281,   282,
   283,   284,    54,    55,   160,   348,   349,   350,   351,   352,
   353,   354,   355,   165,   356,   175,   295,   190,   182,   191,
    56,    54,    55,    37,   121,   193,    57,    58,    59,    60,
    61,    62,    63,   386,   429,   199,   200,   316,   201,    56,
   144,   204,   205,   323,   206,    57,    58,    59,    60,    61,
    62,    63,    54,    55,   211,   212,   221,   295,   222,   223,
   241,   120,   364,   295,   249,   329,   286,   335,   183,   208,
    56,   263,   265,   264,   266,   267,    57,    58,    59,    60,
    61,    62,    63,   299,   268,   300,   301,   302,   303,   304,
   305,   278,   346,   306,   307,   308,   309,   288,    54,    55,
   290,   292,   293,   294,   321,   322,   327,   328,   331,  -160,
   332,    54,    55,   310,   311,    -8,    56,   176,   177,   333,
   336,   343,    57,    58,    59,    60,    61,    62,    63,    56,
    54,   367,   370,   371,   372,    57,    58,    59,    60,    61,
    62,    63,   374,   314,   376,   379,   382,   380,    56,   390,
   392,   395,   385,   393,    57,    58,    59,    60,    61,    62,
    63,   315,   394,   398,   403,   386,   409,    57,    58,    59,
    60,    61,    62,    63,   348,   349,   350,   351,   352,   353,
   354,   355,   410,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   412,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   357,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   386,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   404,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   440,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   446,   356,   348,   349,   350,   351,   352,   353,
   354,   355,   464,   356,   413,   415,   417,   423,   424,   431,
   437,   442,   474,   425,   444,   449,   453,   448,   456,   460,
   461,   462,   485,   476,   463,   469,   473,   490,   477,   479,
   483,   488,   491,     8,   478,    38,   192,    12,   318,   262,
   113,   228,   171,   232,   245,   253,   287,   254,   420,   242,
   152,   291,    48,   189,   345,   445,   482,   471,   434,   418,
   428
};

static const short yycheck[] = {     1,
     2,    27,    53,    23,   165,    35,    92,    29,   388,   411,
    25,    26,    14,    15,   335,   350,   381,    55,    35,   247,
   355,    69,    18,    71,   404,    52,   325,   407,    50,     5,
    78,    85,    34,   261,    68,    73,    80,    81,    82,    83,
   339,    37,   341,    73,    88,    75,    72,   101,    74,    75,
    76,    34,    66,   334,    66,   376,    73,   459,    52,   358,
   440,    73,    76,    76,    67,    78,   446,    29,    30,    31,
    73,   370,    92,    76,   373,    50,   375,    52,    53,   481,
    56,    57,    84,   448,   464,   384,    59,     3,     4,   424,
    63,   412,    68,   392,   474,   394,   395,   378,   379,    66,
    66,   121,    69,   402,    70,   485,   150,   133,   152,   408,
   391,    65,    73,    67,    66,    76,     6,     7,     8,     9,
    10,    73,   443,    66,   423,   211,    76,    17,    18,   290,
    73,   141,   142,   143,    76,    97,    98,    99,   100,    65,
   439,    67,    65,   145,    67,   426,   327,   149,    38,    76,
   449,    54,   333,    70,   435,    36,    37,   183,   160,   458,
   162,   460,    58,    59,   166,   167,   168,   169,   170,   171,
   172,   186,   187,   188,    65,   456,    65,   476,    52,    53,
   182,    58,    59,    60,    61,    65,   467,   195,   196,   197,
    65,   211,   202,   203,    11,    12,    13,    14,    15,    16,
    52,    53,   222,   484,   214,   215,   216,   217,   218,     3,
     4,    65,     6,     7,     8,     9,    10,    11,    12,    13,
    14,    15,    16,    17,    18,    53,    54,    21,    65,   249,
    52,    53,    54,    72,    16,   243,   244,    72,   289,    72,
    65,    65,    76,    72,   246,    76,    65,   255,   256,   257,
   258,   259,    34,    35,    17,    39,    40,    41,    42,    43,
    44,    45,    46,    68,    48,    66,   286,    77,    72,    69,
    52,    34,    35,    67,    70,    66,    58,    59,    60,    61,
    62,    63,    64,    67,    68,    77,    69,   289,    77,    52,
    50,    77,    69,   295,    67,    58,    59,    60,    61,    62,
    63,    64,    34,    35,    69,    71,    52,   327,    69,    71,
    77,    66,   338,   333,    78,    54,    73,   319,    76,    78,
    52,    74,    74,    77,    74,    74,    58,    59,    60,    61,
    62,    63,    64,    20,    69,    22,    23,    24,    25,    26,
    27,    68,    74,    30,    31,    32,    33,    76,    34,    35,
    68,    65,    76,    68,    77,    65,    69,    74,    77,    52,
    69,    34,    35,    50,    51,    73,    52,    53,    54,    73,
    65,    77,    58,    59,    60,    61,    62,    63,    64,    52,
    34,    55,    74,    74,    73,    58,    59,    60,    61,    62,
    63,    64,    76,    34,    52,    67,    52,    54,    52,    19,
    68,    77,    73,    69,    58,    59,    60,    61,    62,    63,
    64,    52,    74,    52,    69,    67,    69,    58,    59,    60,
    61,    62,    63,    64,    39,    40,    41,    42,    43,    44,
    45,    46,    65,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    52,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    39,    40,    41,    42,    43,    44,
    45,    46,    67,    48,    68,    68,    78,    65,    77,    68,
    53,    77,    67,    74,    68,    65,    49,    74,    47,    66,
    68,    73,    67,    69,    68,    52,    68,     0,    69,    68,
    68,    68,     0,     4,    74,    16,   139,     7,   289,   222,
    55,   184,   102,   191,   205,   210,   268,   211,   393,   200,
    86,   272,    16,   133,   332,   433,   477,   463,   409,   391,
   403
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 134 "xi-grammar.y"
{ yyval.modlist = yyvsp[0].modlist; modlist = yyvsp[0].modlist; ;
    break;}
case 2:
#line 138 "xi-grammar.y"
{ 
		  yyval.modlist = 0; 
		;
    break;}
case 3:
#line 142 "xi-grammar.y"
{ yyval.modlist = new ModuleList(lineno, yyvsp[-1].module, yyvsp[0].modlist); ;
    break;}
case 4:
#line 146 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 5:
#line 148 "xi-grammar.y"
{ yyval.intval = 1; ;
    break;}
case 6:
#line 152 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 7:
#line 154 "xi-grammar.y"
{ yyval.intval = 1; ;
    break;}
case 8:
#line 158 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 9:
#line 162 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 10:
#line 164 "xi-grammar.y"
{
		  char *tmp = new char[strlen(yyvsp[-3].strval)+strlen(yyvsp[0].strval)+3];
		  sprintf(tmp,"%s::%s", yyvsp[-3].strval, yyvsp[0].strval);
		  yyval.strval = tmp;
		;
    break;}
case 11:
#line 172 "xi-grammar.y"
{ 
		    yyval.module = new Module(lineno, yyvsp[-1].strval, yyvsp[0].conslist); 
		;
    break;}
case 12:
#line 176 "xi-grammar.y"
{  
		    yyval.module = new Module(lineno, yyvsp[-1].strval, yyvsp[0].conslist); 
		    yyval.module->setMain();
		;
    break;}
case 13:
#line 183 "xi-grammar.y"
{ yyval.conslist = 0; ;
    break;}
case 14:
#line 185 "xi-grammar.y"
{ yyval.conslist = yyvsp[-2].conslist; ;
    break;}
case 15:
#line 189 "xi-grammar.y"
{ yyval.conslist = 0; ;
    break;}
case 16:
#line 191 "xi-grammar.y"
{ yyval.conslist = new ConstructList(lineno, yyvsp[-1].construct, yyvsp[0].conslist); ;
    break;}
case 17:
#line 195 "xi-grammar.y"
{ if(yyvsp[-2].conslist) yyvsp[-2].conslist->setExtern(yyvsp[-4].intval); yyval.construct = yyvsp[-2].conslist; ;
    break;}
case 18:
#line 197 "xi-grammar.y"
{ yyvsp[0].module->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].module; ;
    break;}
case 19:
#line 199 "xi-grammar.y"
{ yyvsp[0].member->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].member; ;
    break;}
case 20:
#line 201 "xi-grammar.y"
{ yyvsp[-1].message->setExtern(yyvsp[-2].intval); yyval.construct = yyvsp[-1].message; ;
    break;}
case 21:
#line 203 "xi-grammar.y"
{ yyvsp[0].chare->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].chare; ;
    break;}
case 22:
#line 205 "xi-grammar.y"
{ yyvsp[0].chare->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].chare; ;
    break;}
case 23:
#line 207 "xi-grammar.y"
{ yyvsp[0].chare->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].chare; ;
    break;}
case 24:
#line 209 "xi-grammar.y"
{ yyvsp[0].chare->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].chare; ;
    break;}
case 25:
#line 211 "xi-grammar.y"
{ yyvsp[0].templat->setExtern(yyvsp[-1].intval); yyval.construct = yyvsp[0].templat; ;
    break;}
case 26:
#line 213 "xi-grammar.y"
{ yyval.construct = NULL; ;
    break;}
case 27:
#line 215 "xi-grammar.y"
{ yyval.construct = NULL; ;
    break;}
case 28:
#line 219 "xi-grammar.y"
{ yyval.tparam = new TParamType(yyvsp[0].type); ;
    break;}
case 29:
#line 221 "xi-grammar.y"
{ yyval.tparam = new TParamVal(yyvsp[0].strval); ;
    break;}
case 30:
#line 223 "xi-grammar.y"
{ yyval.tparam = new TParamVal(yyvsp[0].strval); ;
    break;}
case 31:
#line 227 "xi-grammar.y"
{ yyval.tparlist = new TParamList(yyvsp[0].tparam); ;
    break;}
case 32:
#line 229 "xi-grammar.y"
{ yyval.tparlist = new TParamList(yyvsp[-2].tparam, yyvsp[0].tparlist); ;
    break;}
case 33:
#line 233 "xi-grammar.y"
{ yyval.tparlist = 0; ;
    break;}
case 34:
#line 235 "xi-grammar.y"
{ yyval.tparlist = yyvsp[0].tparlist; ;
    break;}
case 35:
#line 239 "xi-grammar.y"
{ yyval.tparlist = 0; ;
    break;}
case 36:
#line 241 "xi-grammar.y"
{ yyval.tparlist = yyvsp[-1].tparlist; ;
    break;}
case 37:
#line 245 "xi-grammar.y"
{ yyval.type = new BuiltinType("int"); ;
    break;}
case 38:
#line 247 "xi-grammar.y"
{ yyval.type = new BuiltinType("long"); ;
    break;}
case 39:
#line 249 "xi-grammar.y"
{ yyval.type = new BuiltinType("short"); ;
    break;}
case 40:
#line 251 "xi-grammar.y"
{ yyval.type = new BuiltinType("char"); ;
    break;}
case 41:
#line 253 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned int"); ;
    break;}
case 42:
#line 255 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned long"); ;
    break;}
case 43:
#line 257 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned long"); ;
    break;}
case 44:
#line 259 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned long long"); ;
    break;}
case 45:
#line 261 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned short"); ;
    break;}
case 46:
#line 263 "xi-grammar.y"
{ yyval.type = new BuiltinType("unsigned char"); ;
    break;}
case 47:
#line 265 "xi-grammar.y"
{ yyval.type = new BuiltinType("long long"); ;
    break;}
case 48:
#line 267 "xi-grammar.y"
{ yyval.type = new BuiltinType("float"); ;
    break;}
case 49:
#line 269 "xi-grammar.y"
{ yyval.type = new BuiltinType("double"); ;
    break;}
case 50:
#line 271 "xi-grammar.y"
{ yyval.type = new BuiltinType("long double"); ;
    break;}
case 51:
#line 273 "xi-grammar.y"
{ yyval.type = new BuiltinType("void"); ;
    break;}
case 52:
#line 276 "xi-grammar.y"
{ yyval.ntype = new NamedType(yyvsp[-1].strval,yyvsp[0].tparlist); ;
    break;}
case 53:
#line 277 "xi-grammar.y"
{ yyval.ntype = new NamedType(yyvsp[-1].strval,yyvsp[0].tparlist); ;
    break;}
case 54:
#line 280 "xi-grammar.y"
{ yyval.type = yyvsp[0].type; ;
    break;}
case 55:
#line 282 "xi-grammar.y"
{ yyval.type = yyvsp[0].ntype; ;
    break;}
case 56:
#line 286 "xi-grammar.y"
{ yyval.ptype = new PtrType(yyvsp[-1].type); ;
    break;}
case 57:
#line 290 "xi-grammar.y"
{ yyvsp[-1].ptype->indirect(); yyval.ptype = yyvsp[-1].ptype; ;
    break;}
case 58:
#line 292 "xi-grammar.y"
{ yyvsp[-1].ptype->indirect(); yyval.ptype = yyvsp[-1].ptype; ;
    break;}
case 59:
#line 296 "xi-grammar.y"
{ yyval.ftype = new FuncType(yyvsp[-7].type, yyvsp[-4].strval, yyvsp[-1].plist); ;
    break;}
case 60:
#line 300 "xi-grammar.y"
{ yyval.type = yyvsp[0].type; ;
    break;}
case 61:
#line 302 "xi-grammar.y"
{ yyval.type = yyvsp[0].ptype; ;
    break;}
case 62:
#line 304 "xi-grammar.y"
{ yyval.type = yyvsp[0].ptype; ;
    break;}
case 63:
#line 306 "xi-grammar.y"
{ yyval.type = yyvsp[0].ftype; ;
    break;}
case 64:
#line 309 "xi-grammar.y"
{ yyval.type = yyvsp[0].type; ;
    break;}
case 65:
#line 311 "xi-grammar.y"
{ yyval.type = yyvsp[-1].type; ;
    break;}
case 66:
#line 315 "xi-grammar.y"
{ yyval.type = new ReferenceType(yyvsp[-1].type); ;
    break;}
case 67:
#line 317 "xi-grammar.y"
{ yyval.type = yyvsp[0].type; ;
    break;}
case 68:
#line 321 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 69:
#line 323 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 70:
#line 327 "xi-grammar.y"
{ yyval.val = yyvsp[-1].val; ;
    break;}
case 71:
#line 331 "xi-grammar.y"
{ yyval.vallist = 0; ;
    break;}
case 72:
#line 333 "xi-grammar.y"
{ yyval.vallist = new ValueList(yyvsp[-1].val, yyvsp[0].vallist); ;
    break;}
case 73:
#line 337 "xi-grammar.y"
{ yyval.readonly = new Readonly(lineno, yyvsp[-2].type, yyvsp[-1].strval, yyvsp[0].vallist); ;
    break;}
case 74:
#line 341 "xi-grammar.y"
{ yyval.readonly = new Readonly(lineno, yyvsp[-2].type, yyvsp[0].strval, 0, 1); ;
    break;}
case 75:
#line 345 "xi-grammar.y"
{ yyval.intval = 0;;
    break;}
case 76:
#line 347 "xi-grammar.y"
{ yyval.intval = 0;;
    break;}
case 77:
#line 351 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 78:
#line 353 "xi-grammar.y"
{ 
		  /*
		  printf("Warning: Message attributes are being phased out.\n");
		  printf("Warning: Please remove them from interface files.\n");
		  */
		  yyval.intval = yyvsp[-1].intval; 
		;
    break;}
case 79:
#line 363 "xi-grammar.y"
{ yyval.intval = yyvsp[0].intval; ;
    break;}
case 80:
#line 365 "xi-grammar.y"
{ yyval.intval = yyvsp[-2].intval | yyvsp[0].intval; ;
    break;}
case 81:
#line 369 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 82:
#line 371 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 83:
#line 375 "xi-grammar.y"
{ yyval.cattr = 0; ;
    break;}
case 84:
#line 377 "xi-grammar.y"
{ yyval.cattr = yyvsp[-1].cattr; ;
    break;}
case 85:
#line 381 "xi-grammar.y"
{ yyval.cattr = yyvsp[0].cattr; ;
    break;}
case 86:
#line 383 "xi-grammar.y"
{ yyval.cattr = yyvsp[-2].cattr | yyvsp[0].cattr; ;
    break;}
case 87:
#line 387 "xi-grammar.y"
{ python_doc = NULL; yyval.intval = 0; ;
    break;}
case 88:
#line 389 "xi-grammar.y"
{ python_doc = yyvsp[0].strval; yyval.intval = 0; ;
    break;}
case 89:
#line 393 "xi-grammar.y"
{ yyval.cattr = Chare::CPYTHON; ;
    break;}
case 90:
#line 397 "xi-grammar.y"
{ yyval.cattr = 0; ;
    break;}
case 91:
#line 399 "xi-grammar.y"
{ yyval.cattr = yyvsp[-1].cattr; ;
    break;}
case 92:
#line 403 "xi-grammar.y"
{ yyval.cattr = yyvsp[0].cattr; ;
    break;}
case 93:
#line 405 "xi-grammar.y"
{ yyval.cattr = yyvsp[-2].cattr | yyvsp[0].cattr; ;
    break;}
case 94:
#line 409 "xi-grammar.y"
{ yyval.cattr = Chare::CMIGRATABLE; ;
    break;}
case 95:
#line 411 "xi-grammar.y"
{ yyval.cattr = Chare::CPYTHON; ;
    break;}
case 96:
#line 415 "xi-grammar.y"
{ yyval.mv = new MsgVar(yyvsp[-4].type, yyvsp[-3].strval); ;
    break;}
case 97:
#line 419 "xi-grammar.y"
{ yyval.mvlist = new MsgVarList(yyvsp[0].mv); ;
    break;}
case 98:
#line 421 "xi-grammar.y"
{ yyval.mvlist = new MsgVarList(yyvsp[-1].mv, yyvsp[0].mvlist); ;
    break;}
case 99:
#line 425 "xi-grammar.y"
{ yyval.message = new Message(lineno, yyvsp[0].ntype); ;
    break;}
case 100:
#line 427 "xi-grammar.y"
{ yyval.message = new Message(lineno, yyvsp[-3].ntype, yyvsp[-1].mvlist); ;
    break;}
case 101:
#line 431 "xi-grammar.y"
{ yyval.typelist = 0; ;
    break;}
case 102:
#line 433 "xi-grammar.y"
{ yyval.typelist = yyvsp[0].typelist; ;
    break;}
case 103:
#line 437 "xi-grammar.y"
{ yyval.typelist = new TypeList(yyvsp[0].ntype); ;
    break;}
case 104:
#line 439 "xi-grammar.y"
{ yyval.typelist = new TypeList(yyvsp[-2].ntype, yyvsp[0].typelist); ;
    break;}
case 105:
#line 443 "xi-grammar.y"
{ yyval.chare = new Chare(lineno, yyvsp[-3].cattr, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 106:
#line 445 "xi-grammar.y"
{ yyval.chare = new MainChare(lineno, yyvsp[-3].cattr, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 107:
#line 449 "xi-grammar.y"
{ yyval.chare = new Group(lineno, yyvsp[-3].cattr, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 108:
#line 453 "xi-grammar.y"
{ yyval.chare = new NodeGroup(lineno, yyvsp[-3].cattr, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 109:
#line 457 "xi-grammar.y"
{/*Stupid special case for [1D] indices*/
			char *buf=new char[40];
			sprintf(buf,"%sD",yyvsp[-2].strval);
			yyval.ntype = new NamedType(buf); 
		;
    break;}
case 110:
#line 463 "xi-grammar.y"
{ yyval.ntype = new NamedType(yyvsp[-1].strval); ;
    break;}
case 111:
#line 467 "xi-grammar.y"
{  yyval.chare = new Array(lineno, yyvsp[-4].cattr, yyvsp[-3].ntype, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 112:
#line 469 "xi-grammar.y"
{  yyval.chare = new Array(lineno, yyvsp[-3].cattr, yyvsp[-4].ntype, yyvsp[-2].ntype, yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 113:
#line 473 "xi-grammar.y"
{ yyval.chare = new Chare(lineno, yyvsp[-3].cattr, new NamedType(yyvsp[-2].strval), yyvsp[-1].typelist, yyvsp[0].mbrlist);;
    break;}
case 114:
#line 475 "xi-grammar.y"
{ yyval.chare = new MainChare(lineno, yyvsp[-3].cattr, new NamedType(yyvsp[-2].strval), yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 115:
#line 479 "xi-grammar.y"
{ yyval.chare = new Group(lineno, yyvsp[-3].cattr, new NamedType(yyvsp[-2].strval), yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 116:
#line 483 "xi-grammar.y"
{ yyval.chare = new NodeGroup( lineno, yyvsp[-3].cattr, new NamedType(yyvsp[-2].strval), yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 117:
#line 487 "xi-grammar.y"
{ yyval.chare = new Array( lineno, 0, yyvsp[-3].ntype, new NamedType(yyvsp[-2].strval), yyvsp[-1].typelist, yyvsp[0].mbrlist); ;
    break;}
case 118:
#line 491 "xi-grammar.y"
{ yyval.message = new Message(lineno, new NamedType(yyvsp[-1].strval)); ;
    break;}
case 119:
#line 493 "xi-grammar.y"
{ yyval.message = new Message(lineno, new NamedType(yyvsp[-4].strval), yyvsp[-2].mvlist); ;
    break;}
case 120:
#line 497 "xi-grammar.y"
{ yyval.type = 0; ;
    break;}
case 121:
#line 499 "xi-grammar.y"
{ yyval.type = yyvsp[0].type; ;
    break;}
case 122:
#line 503 "xi-grammar.y"
{ yyval.strval = 0; ;
    break;}
case 123:
#line 505 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 124:
#line 507 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 125:
#line 511 "xi-grammar.y"
{ yyval.tvar = new TType(new NamedType(yyvsp[-1].strval), yyvsp[0].type); ;
    break;}
case 126:
#line 513 "xi-grammar.y"
{ yyval.tvar = new TFunc(yyvsp[-1].ftype, yyvsp[0].strval); ;
    break;}
case 127:
#line 515 "xi-grammar.y"
{ yyval.tvar = new TName(yyvsp[-2].type, yyvsp[-1].strval, yyvsp[0].strval); ;
    break;}
case 128:
#line 519 "xi-grammar.y"
{ yyval.tvarlist = new TVarList(yyvsp[0].tvar); ;
    break;}
case 129:
#line 521 "xi-grammar.y"
{ yyval.tvarlist = new TVarList(yyvsp[-2].tvar, yyvsp[0].tvarlist); ;
    break;}
case 130:
#line 525 "xi-grammar.y"
{ yyval.tvarlist = yyvsp[-1].tvarlist; ;
    break;}
case 131:
#line 529 "xi-grammar.y"
{ yyval.templat = new Template(yyvsp[-1].tvarlist, yyvsp[0].chare); yyvsp[0].chare->setTemplate(yyval.templat); ;
    break;}
case 132:
#line 531 "xi-grammar.y"
{ yyval.templat = new Template(yyvsp[-1].tvarlist, yyvsp[0].chare); yyvsp[0].chare->setTemplate(yyval.templat); ;
    break;}
case 133:
#line 533 "xi-grammar.y"
{ yyval.templat = new Template(yyvsp[-1].tvarlist, yyvsp[0].chare); yyvsp[0].chare->setTemplate(yyval.templat); ;
    break;}
case 134:
#line 535 "xi-grammar.y"
{ yyval.templat = new Template(yyvsp[-1].tvarlist, yyvsp[0].chare); yyvsp[0].chare->setTemplate(yyval.templat); ;
    break;}
case 135:
#line 537 "xi-grammar.y"
{ yyval.templat = new Template(yyvsp[-1].tvarlist, yyvsp[0].message); yyvsp[0].message->setTemplate(yyval.templat); ;
    break;}
case 136:
#line 541 "xi-grammar.y"
{ yyval.mbrlist = 0; ;
    break;}
case 137:
#line 543 "xi-grammar.y"
{ yyval.mbrlist = yyvsp[-2].mbrlist; ;
    break;}
case 138:
#line 547 "xi-grammar.y"
{ 
		  Entry *tempEntry;
		  if (!connectEntries->empty()) {
		    tempEntry = connectEntries->begin();
		    MemberList *ml;
		    ml = new MemberList(tempEntry, 0);
		    tempEntry = connectEntries->next();
		    for(; !connectEntries->end(); tempEntry = connectEntries->next()) {
                      ml->appendMember(tempEntry); 
		    }
		    while (!connectEntries->empty())
		      connectEntries->pop();
                    yyval.mbrlist = ml; 
		  }
		  else {
		    yyval.mbrlist = 0; 
                  }
		;
    break;}
case 139:
#line 566 "xi-grammar.y"
{ yyval.mbrlist = new MemberList(yyvsp[-1].member, yyvsp[0].mbrlist); ;
    break;}
case 140:
#line 570 "xi-grammar.y"
{ yyval.member = yyvsp[-1].readonly; ;
    break;}
case 141:
#line 572 "xi-grammar.y"
{ yyval.member = yyvsp[-1].readonly; ;
    break;}
case 143:
#line 575 "xi-grammar.y"
{ yyval.member = yyvsp[-1].member; ;
    break;}
case 144:
#line 577 "xi-grammar.y"
{ yyval.member = yyvsp[-1].pupable; ;
    break;}
case 145:
#line 579 "xi-grammar.y"
{ yyval.member = yyvsp[-1].includeFile; ;
    break;}
case 146:
#line 581 "xi-grammar.y"
{ yyval.member = new ClassDeclaration(lineno,yyvsp[-1].strval); ;
    break;}
case 147:
#line 585 "xi-grammar.y"
{ yyval.member = new InitCall(lineno, yyvsp[0].strval, 1); ;
    break;}
case 148:
#line 587 "xi-grammar.y"
{ yyval.member = new InitCall(lineno, yyvsp[-3].strval, 1); ;
    break;}
case 149:
#line 589 "xi-grammar.y"
{ printf("Warning: deprecated use of initcall. Use initnode or initproc instead.\n"); 
		  yyval.member = new InitCall(lineno, yyvsp[0].strval, 1); ;
    break;}
case 150:
#line 592 "xi-grammar.y"
{ printf("Warning: deprecated use of initcall. Use initnode or initproc instead.\n");
		  yyval.member = new InitCall(lineno, yyvsp[-3].strval, 1); ;
    break;}
case 151:
#line 597 "xi-grammar.y"
{ yyval.member = new InitCall(lineno, yyvsp[0].strval, 0); ;
    break;}
case 152:
#line 599 "xi-grammar.y"
{ yyval.member = new InitCall(lineno, yyvsp[-3].strval, 0); ;
    break;}
case 153:
#line 603 "xi-grammar.y"
{ yyval.pupable = new PUPableClass(lineno,yyvsp[0].strval,0); ;
    break;}
case 154:
#line 605 "xi-grammar.y"
{ yyval.pupable = new PUPableClass(lineno,yyvsp[-2].strval,yyvsp[0].pupable); ;
    break;}
case 155:
#line 609 "xi-grammar.y"
{ yyval.includeFile = new IncludeFile(lineno,yyvsp[0].strval); ;
    break;}
case 156:
#line 613 "xi-grammar.y"
{ yyval.member = yyvsp[-1].entry; ;
    break;}
case 157:
#line 615 "xi-grammar.y"
{ yyval.member = yyvsp[0].member; ;
    break;}
case 158:
#line 619 "xi-grammar.y"
{ 
		  if (yyvsp[0].sc != 0) { 
		    yyvsp[0].sc->con1 = new SdagConstruct(SIDENT, yyvsp[-3].strval);
  		    if (yyvsp[-2].plist != 0)
                      yyvsp[0].sc->param = new ParamList(yyvsp[-2].plist);
 		    else 
 	 	      yyvsp[0].sc->param = new ParamList(new Parameter(0, new BuiltinType("void")));
                  }
		  yyval.entry = new Entry(lineno, yyvsp[-5].intval, yyvsp[-4].type, yyvsp[-3].strval, yyvsp[-2].plist, yyvsp[-1].val, yyvsp[0].sc, 0, 0); 
		;
    break;}
case 159:
#line 630 "xi-grammar.y"
{ 
		  if (yyvsp[0].sc != 0) {
		    yyvsp[0].sc->con1 = new SdagConstruct(SIDENT, yyvsp[-2].strval);
		    if (yyvsp[-1].plist != 0)
                      yyvsp[0].sc->param = new ParamList(yyvsp[-1].plist);
		    else
                      yyvsp[0].sc->param = new ParamList(new Parameter(0, new BuiltinType("void")));
                  }
		  yyval.entry = new Entry(lineno, yyvsp[-3].intval,     0, yyvsp[-2].strval, yyvsp[-1].plist,  0, yyvsp[0].sc, 0, 0); 
		;
    break;}
case 160:
#line 643 "xi-grammar.y"
{ yyval.type = new BuiltinType("void"); ;
    break;}
case 161:
#line 645 "xi-grammar.y"
{ yyval.type = yyvsp[0].ptype; ;
    break;}
case 162:
#line 649 "xi-grammar.y"
{ yyval.intval = 0; ;
    break;}
case 163:
#line 651 "xi-grammar.y"
{ yyval.intval = yyvsp[-1].intval; ;
    break;}
case 164:
#line 655 "xi-grammar.y"
{ yyval.intval = yyvsp[0].intval; ;
    break;}
case 165:
#line 657 "xi-grammar.y"
{ yyval.intval = yyvsp[-2].intval | yyvsp[0].intval; ;
    break;}
case 166:
#line 661 "xi-grammar.y"
{ yyval.intval = STHREADED; ;
    break;}
case 167:
#line 663 "xi-grammar.y"
{ yyval.intval = SSYNC; ;
    break;}
case 168:
#line 665 "xi-grammar.y"
{ yyval.intval = SIGET; ;
    break;}
case 169:
#line 667 "xi-grammar.y"
{ yyval.intval = SLOCKED; ;
    break;}
case 170:
#line 669 "xi-grammar.y"
{ yyval.intval = SCREATEHERE; ;
    break;}
case 171:
#line 671 "xi-grammar.y"
{ yyval.intval = SCREATEHOME; ;
    break;}
case 172:
#line 673 "xi-grammar.y"
{ yyval.intval = SNOKEEP; ;
    break;}
case 173:
#line 675 "xi-grammar.y"
{ yyval.intval = SNOTRACE; ;
    break;}
case 174:
#line 677 "xi-grammar.y"
{ yyval.intval = SIMMEDIATE; ;
    break;}
case 175:
#line 679 "xi-grammar.y"
{ yyval.intval = SSKIPSCHED; ;
    break;}
case 176:
#line 681 "xi-grammar.y"
{ yyval.intval = SINLINE; ;
    break;}
case 177:
#line 683 "xi-grammar.y"
{ yyval.intval = SLOCAL; ;
    break;}
case 178:
#line 685 "xi-grammar.y"
{ yyval.intval = SPYTHON; ;
    break;}
case 179:
#line 689 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 180:
#line 691 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 181:
#line 693 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 182:
#line 697 "xi-grammar.y"
{ yyval.strval = ""; ;
    break;}
case 183:
#line 699 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 184:
#line 701 "xi-grammar.y"
{  /*Returned only when in_bracket*/
			char *tmp = new char[strlen(yyvsp[-2].strval)+strlen(yyvsp[0].strval)+3];
			sprintf(tmp,"%s, %s", yyvsp[-2].strval, yyvsp[0].strval);
			yyval.strval = tmp;
		;
    break;}
case 185:
#line 709 "xi-grammar.y"
{ yyval.strval = ""; ;
    break;}
case 186:
#line 711 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 187:
#line 713 "xi-grammar.y"
{  /*Returned only when in_bracket*/
			char *tmp = new char[strlen(yyvsp[-4].strval)+strlen(yyvsp[-2].strval)+strlen(yyvsp[0].strval)+3];
			sprintf(tmp,"%s[%s]%s", yyvsp[-4].strval, yyvsp[-2].strval, yyvsp[0].strval);
			yyval.strval = tmp;
		;
    break;}
case 188:
#line 719 "xi-grammar.y"
{ /*Returned only when in_braces*/
			char *tmp = new char[strlen(yyvsp[-4].strval)+strlen(yyvsp[-2].strval)+strlen(yyvsp[0].strval)+3];
			sprintf(tmp,"%s{%s}%s", yyvsp[-4].strval, yyvsp[-2].strval, yyvsp[0].strval);
			yyval.strval = tmp;
		;
    break;}
case 189:
#line 725 "xi-grammar.y"
{ /*Returned only when in_braces*/
			char *tmp = new char[strlen(yyvsp[-4].strval)+strlen(yyvsp[-2].strval)+strlen(yyvsp[0].strval)+3];
			sprintf(tmp,"%s(%s)%s", yyvsp[-4].strval, yyvsp[-2].strval, yyvsp[0].strval);
			yyval.strval = tmp;
		;
    break;}
case 190:
#line 731 "xi-grammar.y"
{ /*Returned only when in_braces*/
			char *tmp = new char[strlen(yyvsp[-2].strval)+strlen(yyvsp[0].strval)+3];
			sprintf(tmp,"(%s)%s", yyvsp[-2].strval, yyvsp[0].strval);
			yyval.strval = tmp;
		;
    break;}
case 191:
#line 739 "xi-grammar.y"
{  /*Start grabbing CPROGRAM segments*/
			in_bracket=1;
			yyval.pname = new Parameter(lineno, yyvsp[-2].type,yyvsp[-1].strval);
		;
    break;}
case 192:
#line 746 "xi-grammar.y"
{ 
                   /*Start grabbing CPROGRAM segments*/
			in_braces=1;
			yyval.intval = 0;
		;
    break;}
case 193:
#line 754 "xi-grammar.y"
{ 
			in_braces=0;
			yyval.intval = 0;
		;
    break;}
case 194:
#line 761 "xi-grammar.y"
{ yyval.pname = new Parameter(lineno, yyvsp[0].type);;
    break;}
case 195:
#line 763 "xi-grammar.y"
{ yyval.pname = new Parameter(lineno, yyvsp[-1].type,yyvsp[0].strval);;
    break;}
case 196:
#line 765 "xi-grammar.y"
{ yyval.pname = new Parameter(lineno, yyvsp[-3].type,yyvsp[-2].strval,0,yyvsp[0].val);;
    break;}
case 197:
#line 767 "xi-grammar.y"
{ /*Stop grabbing CPROGRAM segments*/
			in_bracket=0;
			yyval.pname = new Parameter(lineno, yyvsp[-2].pname->getType(), yyvsp[-2].pname->getName() ,yyvsp[-1].strval);
		;
    break;}
case 198:
#line 774 "xi-grammar.y"
{ yyval.plist = new ParamList(yyvsp[0].pname); ;
    break;}
case 199:
#line 776 "xi-grammar.y"
{ yyval.plist = new ParamList(yyvsp[-2].pname,yyvsp[0].plist); ;
    break;}
case 200:
#line 780 "xi-grammar.y"
{ yyval.plist = yyvsp[-1].plist; ;
    break;}
case 201:
#line 782 "xi-grammar.y"
{ yyval.plist = 0; ;
    break;}
case 202:
#line 786 "xi-grammar.y"
{ yyval.val = 0; ;
    break;}
case 203:
#line 788 "xi-grammar.y"
{ yyval.val = new Value(yyvsp[0].strval); ;
    break;}
case 204:
#line 792 "xi-grammar.y"
{ yyval.sc = 0; ;
    break;}
case 205:
#line 794 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SSDAGENTRY, yyvsp[0].sc); ;
    break;}
case 206:
#line 796 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SSDAGENTRY, yyvsp[-1].sc); ;
    break;}
case 207:
#line 800 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SSLIST, yyvsp[0].sc); ;
    break;}
case 208:
#line 802 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SSLIST, yyvsp[-1].sc, yyvsp[0].sc);  ;
    break;}
case 209:
#line 806 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SOLIST, yyvsp[0].sc); ;
    break;}
case 210:
#line 808 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SOLIST, yyvsp[-1].sc, yyvsp[0].sc); ;
    break;}
case 211:
#line 812 "xi-grammar.y"
{ yyval.sc = 0; ;
    break;}
case 212:
#line 814 "xi-grammar.y"
{ yyval.sc = yyvsp[-1].sc; ;
    break;}
case 213:
#line 818 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SPUBLISHES, new SdagConstruct(SIDENT, yyvsp[0].strval)); ;
    break;}
case 214:
#line 820 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SPUBLISHES, new SdagConstruct(SIDENT, yyvsp[-2].strval), yyvsp[0].sc);  ;
    break;}
case 215:
#line 824 "xi-grammar.y"
{ yyval.strval = yyvsp[0].strval; ;
    break;}
case 216:
#line 826 "xi-grammar.y"
{ yyval.strval = 0; ;
    break;}
case 217:
#line 830 "xi-grammar.y"
{ RemoveSdagComments(yyvsp[-2].strval);
		   yyval.sc = new SdagConstruct(SATOMIC, new XStr(yyvsp[-2].strval), yyvsp[0].sc, 0,0,0,0, 0 ); 
		   if (yyvsp[-4].strval) { yyvsp[-4].strval[strlen(yyvsp[-4].strval)-1]=0; yyval.sc->traceName = new XStr(yyvsp[-4].strval+1); }
		 ;
    break;}
case 218:
#line 835 "xi-grammar.y"
{  
		   in_braces = 0;
		   if ((yyvsp[-4].plist->isVoid() == 0) && (yyvsp[-4].plist->isMessage() == 0))
                   {
		      connectEntries->append(new Entry(0, 0, new BuiltinType("void"), yyvsp[-5].strval, 
	 	 			new ParamList(new Parameter(lineno, new PtrType( 
                                        new NamedType("CkMarshallMsg")), "_msg")), 0, 0, 0, 1, yyvsp[-4].plist));
		   }
		   else  {
		      connectEntries->append(new Entry(0, 0, new BuiltinType("void"), yyvsp[-5].strval, yyvsp[-4].plist, 0, 0, 0, 1, yyvsp[-4].plist));
                   }
                   yyval.sc = new SdagConstruct(SCONNECT, yyvsp[-5].strval, yyvsp[-1].strval, yyvsp[-4].plist);
		;
    break;}
case 219:
#line 849 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SWHEN, 0, 0,0,0,0,0,yyvsp[-2].entrylist); ;
    break;}
case 220:
#line 851 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SWHEN, 0, 0, 0,0,0, yyvsp[0].sc, yyvsp[-1].entrylist); ;
    break;}
case 221:
#line 853 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SWHEN, 0, 0, 0,0,0, yyvsp[-1].sc, yyvsp[-3].entrylist); ;
    break;}
case 222:
#line 855 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SOVERLAP,0, 0,0,0,0,yyvsp[-1].sc, 0); ;
    break;}
case 223:
#line 857 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFOR, 0, new SdagConstruct(SINT_EXPR, yyvsp[-8].strval), new SdagConstruct(SINT_EXPR, yyvsp[-6].strval),
		             new SdagConstruct(SINT_EXPR, yyvsp[-4].strval), 0, yyvsp[-1].sc, 0); ;
    break;}
case 224:
#line 860 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFOR, 0, new SdagConstruct(SINT_EXPR, yyvsp[-6].strval), new SdagConstruct(SINT_EXPR, yyvsp[-4].strval), 
		         new SdagConstruct(SINT_EXPR, yyvsp[-2].strval), 0, yyvsp[0].sc, 0); ;
    break;}
case 225:
#line 863 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFORALL, 0, new SdagConstruct(SIDENT, yyvsp[-9].strval), new SdagConstruct(SINT_EXPR, yyvsp[-6].strval), 
		             new SdagConstruct(SINT_EXPR, yyvsp[-4].strval), new SdagConstruct(SINT_EXPR, yyvsp[-2].strval), yyvsp[0].sc, 0); ;
    break;}
case 226:
#line 866 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFORALL, 0, new SdagConstruct(SIDENT, yyvsp[-11].strval), new SdagConstruct(SINT_EXPR, yyvsp[-8].strval), 
		                 new SdagConstruct(SINT_EXPR, yyvsp[-6].strval), new SdagConstruct(SINT_EXPR, yyvsp[-4].strval), yyvsp[-1].sc, 0); ;
    break;}
case 227:
#line 869 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SIF, 0, new SdagConstruct(SINT_EXPR, yyvsp[-3].strval), yyvsp[0].sc,0,0,yyvsp[-1].sc,0); ;
    break;}
case 228:
#line 871 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SIF, 0, new SdagConstruct(SINT_EXPR, yyvsp[-5].strval), yyvsp[0].sc,0,0,yyvsp[-2].sc,0); ;
    break;}
case 229:
#line 873 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SIF, 0, new SdagConstruct(SINT_EXPR, yyvsp[-2].strval), 0,0,0,yyvsp[0].sc,0); ;
    break;}
case 230:
#line 875 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SWHILE, 0, new SdagConstruct(SINT_EXPR, yyvsp[-4].strval), 0,0,0,yyvsp[-1].sc,0); ;
    break;}
case 231:
#line 877 "xi-grammar.y"
{ yyval.sc = yyvsp[-1].sc; ;
    break;}
case 232:
#line 879 "xi-grammar.y"
{ RemoveSdagComments(yyvsp[-1].strval);
                   yyval.sc = new SdagConstruct(SATOMIC, new XStr(yyvsp[-1].strval), NULL, 0,0,0,0, 0 );
                 ;
    break;}
case 233:
#line 885 "xi-grammar.y"
{ yyval.sc = 0; ;
    break;}
case 234:
#line 887 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SELSE, 0,0,0,0,0, yyvsp[0].sc,0); ;
    break;}
case 235:
#line 889 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SELSE, 0,0,0,0,0, yyvsp[-1].sc,0); ;
    break;}
case 236:
#line 892 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFORWARD, new SdagConstruct(SIDENT, yyvsp[0].strval)); ;
    break;}
case 237:
#line 894 "xi-grammar.y"
{ yyval.sc = new SdagConstruct(SFORWARD, new SdagConstruct(SIDENT, yyvsp[-2].strval), yyvsp[0].sc);  ;
    break;}
case 238:
#line 898 "xi-grammar.y"
{ in_int_expr = 0; yyval.intval = 0; ;
    break;}
case 239:
#line 902 "xi-grammar.y"
{ in_int_expr = 1; yyval.intval = 0; ;
    break;}
case 240:
#line 906 "xi-grammar.y"
{ 
		  if (yyvsp[0].plist != 0)
		     yyval.entry = new Entry(lineno, 0, 0, yyvsp[-1].strval, yyvsp[0].plist, 0, 0, 0, 0); 
		  else
		     yyval.entry = new Entry(lineno, 0, 0, yyvsp[-1].strval, 
				new ParamList(new Parameter(0, new BuiltinType("void"))), 0, 0, 0, 0); 
		;
    break;}
case 241:
#line 914 "xi-grammar.y"
{ if (yyvsp[0].plist != 0)
		    yyval.entry = new Entry(lineno, 0, 0, yyvsp[-4].strval, yyvsp[0].plist, 0, 0, yyvsp[-2].strval, 0); 
		  else
		    yyval.entry = new Entry(lineno, 0, 0, yyvsp[-4].strval, new ParamList(new Parameter(0, new BuiltinType("void"))), 0, 0, yyvsp[-2].strval, 0); 
		;
    break;}
case 242:
#line 922 "xi-grammar.y"
{ yyval.entrylist = new EntryList(yyvsp[0].entry); ;
    break;}
case 243:
#line 924 "xi-grammar.y"
{ yyval.entrylist = new EntryList(yyvsp[-2].entry,yyvsp[0].entrylist); ;
    break;}
case 244:
#line 928 "xi-grammar.y"
{ in_bracket=1; ;
    break;}
case 245:
#line 931 "xi-grammar.y"
{ in_bracket=0; ;
    break;}
case 246:
#line 935 "xi-grammar.y"
{ if (!macroDefined(yyvsp[0].strval, 1)) in_comment = 1; ;
    break;}
case 247:
#line 939 "xi-grammar.y"
{ if (!macroDefined(yyvsp[0].strval, 0)) in_comment = 1; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 942 "xi-grammar.y"

void yyerror(const char *mesg)
{
  cout << cur_file<<":"<<lineno<<": Charmxi syntax error> " << mesg << endl;
  // return 0;
}
