
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 18
#define YY_END_OF_BUFFER 19
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[383] =
    {   0,
        1,    2,    3,    1,    2,    3,   19,    1,    2,    3,
       17,   18,    1,    2,    3,   12,   17,   18,    1,    2,
        3,   13,   18,    1,    2,    3,    5,   17,   18,    1,
        2,    3,   17,   18,    1,    2,    3,   17,   18,    1,
        2,    3,   17,   18,    1,    2,   17,   18,    1,    2,
        3,   17,   18,    1,    2,    3,   17,   18,    1,    2,
        3,   17,   18,    1,    2,    3,   17,   18,    1,    2,
        3,   14,   15,   17,   18,    1,    2,   17,   18,    1,
        2,    3,   16,   17,   18,    2,    3,   17,   18,    1,
        3,   17,   18,    1,    2,    3,    1,    2,    2,    3,

        1,    3,    1,    2,    3,   12,    1,    2,    3,    1,
        2,    3,   15,    1,    2,    2,    3,    1,    3,    1,
        2,    3,    1,    2,    3,    1,    2,    3,    1,    2,
        3,   15,    1,    2,    2,    3,    1,    3,    2,    1,
        1,    2,    3,    7,    1,    2,    3,    1,    2,    3,
       14,   15,    1,    2,    3,   15,    1,    2,    3,    6,
        1,    2,    3,    4,    1,    2,    3,   15,    1,    2,
        3,    1,    2,    3,   14,   15,    1,    2,   11,    1,
        2,    3,   16,    3,    1,    2,    3,    1,    2,    3,
        1,    2,    3,    1,    2,   15,    2,    1,    2,    3,

       15,    3,    1,    3,   15,    1,    2,    3,    1,    2,
        3,    8,    1,    2,    3,    1,    2,    3,    1,    2,
        3,    1,    2,   15,    2,    1,    2,    3,   15,    3,
        1,    3,   15,    1,    2,    3,    1,    2,    3,    4,
        1,    2,    4,    2,    3,    4,    1,    3,    4,    1,
        2,    3,    1,    2,    3,   15,    1,    2,    3,    1,
        2,    2,    3,    1,    3,    1,    2,    1,    2,    1,
        2,    2,   15,    1,   15,    2,    3,    2,    3,    2,
        3,    3,   15,    1,    3,    1,    3,    1,    3,    1,
        2,    3,    1,    2,    3,    1,    2,    3,    1,    2,

        2,    3,    1,    3,    1,    2,    1,    2,    1,    2,
        2,   15,    1,   15,    2,    3,    2,    3,    2,    3,
        3,   15,    1,    3,    1,    3,    1,    3,    1,    2,
        3,    1,    2,    3,   15,    2,    4,    1,    4,    3,
        4,    2,    1,    3,    2,    2,    2,   15,    1,    1,
        1,    3,    3,    3,    1,    2,    3,    1,    2,    3,
        2,    1,    3,    2,    2,    2,   15,    1,    1,    1,
        3,    3,    3,    4,    1,    2,    3,   10,    1,    2,
        3,    9
    } ;

static yyconst flex_int16_t yy_accept[161] =
    {   0,
        1,    4,    7,    8,   13,   19,   24,   30,   35,   40,
       45,   49,   54,   59,   64,   69,   76,   80,   86,   90,
       94,   97,   99,  101,  103,  107,  110,  114,  116,  118,
      120,  123,  126,  129,  133,  135,  137,  139,  140,  141,
      145,  148,  153,  157,  161,  165,  169,  172,  177,  180,
      184,  185,  188,  191,  194,  197,  198,  199,  202,  203,
      206,  209,  213,  216,  219,  222,  225,  226,  227,  230,
      231,  234,  237,  241,  244,  247,  250,  253,  257,  260,
      262,  264,  266,  268,  270,  272,  274,  274,  276,  278,
      280,  282,  284,  286,  288,  290,  293,  296,  299,  301,

      303,  305,  307,  309,  311,  313,  313,  315,  317,  319,
      321,  323,  325,  327,  329,  332,  336,  338,  340,  342,
      343,  344,  345,  346,  347,  348,  349,  350,  351,  352,
      353,  354,  355,  358,  361,  362,  363,  364,  365,  366,
      367,  368,  369,  370,  371,  372,  373,  374,  375,  375,
      375,  375,  375,  379,  383,  383,  383,  383,  383,  383
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    8,
        8,    9,   10,    8,   10,   11,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,    8,    1,
        1,    1,    1,    1,   15,   15,   15,   15,   16,   15,
       15,   15,   15,   15,   17,   15,   17,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       18,    1,   18,    1,   19,    1,   15,   15,   15,   20,

       21,   22,   15,   15,   23,   15,   17,   15,   17,   24,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   25,    1,   25,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[26] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5
    } ;

static yyconst flex_int16_t yy_base[207] =
    {   0,
        0,    0,  266,   18,   42,  261,  259,   65,   25,   88,
       10,   27,   29,   28,   43,  112,   33,  132,   49,   51,
      243,   36,   63,   58,    0,  154,   79,  177,  200,  223,
       51,   76,  239,   31,  262,  285,  308,    0,    0,  233,
       84,    0,  325,  225,  344,   76,   90,  220,   76,    0,
        0,  102,  106,  367,  391,  107,  112,  415,  438,  451,
       60,  116,  117,  119,  467,  491,  135,  128,  497,  502,
      515,  148,  520,  160,  543,  566,  114,  162,  582,  605,
      628,  651,    0,    0,  667,  138,  201,  164,    0,    0,
      690,  168,    0,    0,  713,   62,  163,  729,  752,  775,

      798,  815,  821,  826,  174,  190,  184,  850,  856,  861,
      186,  885,  891,  896,  181,  188,  171,  189,  196,  195,
      206,  912,  210,  214,  218,  227,  231,  246,  249,  253,
      257,  924,  216,  248,  265,  268,  936,  237,  271,  276,
      274,  282,  293,  291,  300,  310,  948,    0,  139,  303,
      316,  134,  135,   97,   42,  321,  327,   30, 1197,  962,
      967,  972,  977,  982,  987,  992,  997, 1002, 1007, 1012,
     1017, 1022, 1026, 1031, 1036, 1041, 1046, 1051, 1056, 1061,
     1066, 1071, 1076, 1081, 1086, 1091, 1096, 1101, 1106, 1111,
     1116, 1121, 1126, 1131, 1136, 1141, 1146, 1151, 1156, 1161,

     1166, 1171, 1176, 1181, 1186, 1191
    } ;

static yyconst flex_int16_t yy_def[207] =
    {   0,
      159,    1,  159,  160,  160,    5,    5,  161,    5,  162,
      163,    5,    5,    5,    5,    5,  163,    5,  164,  165,
        5,  163,  164,  165,    5,  161,    5,  166,  167,  168,
        5,    5,  162,    5,  169,  170,  171,  172,  173,    5,
        5,   16,    5,    5,  174,   16,    5,    5,  163,   18,
      175,    5,    5,  176,  163,  177,  178,  164,  179,  165,
        5,    5,    5,    5,  180,   55,  181,  182,   58,  183,
       60,    5,  174,  184,  185,  186,    5,    5,  176,  187,
      188,  189,   55,   55,  187,  172,  190,  173,   58,   58,
      188,  175,   60,   60,  189,    5,    5,  180,  191,  192,

      193,   55,   55,  191,  172,  194,  173,   58,   58,  192,
      175,   60,   60,  193,    5,    5,  195,  196,  197,  198,
      199,  200,  172,  172,  198,  159,  173,  173,  199,  175,
      175,  200,    5,    5,  201,  202,  203,  172,  172,  201,
      159,  173,  173,  202,  175,  175,  203,  204,  205,  159,
      159,  205,    5,    5,  206,  159,  159,  206,    0,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159
    } ;

static yyconst flex_int16_t yy_nxt[1223] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   18,   19,   18,   18,
       18,   18,   18,   18,   20,   22,   21,   38,   21,   21,
       21,   22,   63,   64,   39,   23,  141,   65,   40,   41,
       43,   42,   24,   25,   21,   31,   49,   32,  141,   22,
       38,   44,   21,   38,   45,   22,   38,   39,   39,   23,
       39,   21,   38,   21,   39,   39,   24,   21,   51,   27,
       38,   39,   28,   51,   61,   51,   38,   21,   28,   96,
       52,   53,   29,   54,  133,   21,   21,   51,   43,   30,
       21,   21,   21,   38,   34,   35,   43,   62,   21,   77,

       39,   35,   78,   52,   53,   36,   54,   52,   53,   38,
       54,   86,   37,   21,   39,   21,   88,   21,   63,   64,
       63,   64,   46,   65,   42,   65,   78,   47,   48,   87,
       39,   87,   47,   21,  107,   97,   21,   38,  126,  123,
      124,  105,  125,  126,   50,  106,   50,   50,   50,   21,
       50,   50,   50,   50,   50,   50,   21,  115,   27,  106,
      116,   28,   22,   21,   21,  127,  128,   28,  129,  130,
      131,   29,  132,   38,   78,  138,  139,  117,   30,   22,
      140,   55,   21,  134,  118,  142,  143,  145,  146,   21,
      144,   39,  147,  116,   56,  148,  141,   38,   51,   86,

      116,   57,   23,  148,   58,  126,  148,   56,   39,  148,
       88,  123,  124,   56,  125,  123,  124,   21,  125,  149,
       38,   21,   86,  149,   59,   24,   21,   60,  150,  151,
       57,  152,  127,  128,   21,  129,   57,  153,  138,  139,
       59,   21,  149,  140,   21,   34,   35,  127,  128,   21,
      129,   39,   35,   88,  130,  131,   36,  132,  130,  131,
       21,  132,   21,   37,   22,  159,  149,   38,   66,  154,
       39,  105,  138,  139,  107,  156,  157,  140,   38,   67,
      158,  159,  105,  142,  143,  155,   68,   23,  144,  155,
      159,   69,   67,   39,  142,  143,  159,  107,   67,  144,

      155,  145,  146,  159,  150,  151,  147,  152,  155,   70,
       24,  145,  146,  159,   71,   68,  147,  150,  151,  159,
      152,   68,  156,  157,  159,   70,   21,  158,  156,  157,
      159,  159,  159,  158,  159,  159,  159,   43,  159,  159,
       72,  159,  159,  159,  159,   72,   21,  159,  159,  159,
      159,   74,  159,  159,  159,  159,  159,   74,  159,  159,
      159,   75,  159,  159,  159,  159,  159,  159,   76,   21,
      159,   27,  159,  159,   80,  159,  159,  159,  159,  159,
       80,  159,  159,  159,   81,  159,  159,  159,  159,  159,
      159,   82,   83,   84,  159,   85,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  159,   38,  159,
      159,  159,  159,  159,  159,   39,   89,   90,  159,   91,
      159,  159,   38,  159,  159,  159,  159,  159,   38,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,   51,
       51,  159,   92,  159,  159,   87,  159,  159,  159,  159,
      159,   87,   93,   94,  159,   95,  159,  159,   39,  159,
      159,  159,  159,  159,   39,  159,  159,  159,   51,   21,
      159,  159,  159,   34,   99,  159,  159,  159,  159,  159,
       99,  159,  159,  159,  100,  159,  159,  159,  159,  159,
      159,  101,  102,  103,  159,   22,  159,  104,  108,  109,

      159,   23,  159,  110,   51,  159,  159,  159,  111,  106,
      159,  159,  159,  159,  159,  106,  112,  113,  159,   24,
      159,  114,   21,  159,  159,  159,  159,   74,  159,  159,
      159,  159,  159,   74,  159,  159,  159,   75,  159,  159,
      159,  159,  159,  159,   76,   23,  159,  159,  159,  159,
      117,  159,  159,  159,  159,  159,  117,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  119,   24,  159,
      159,  159,  159,  118,  159,  159,  159,  159,  159,  118,
      159,  159,  159,  119,   21,  159,   27,  159,  159,   80,
      159,  159,  159,  159,  159,   80,  159,  159,  159,   81,

      159,  159,  159,  159,  159,  159,   82,   22,  159,   55,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  120,  159,  159,  159,  159,  159,  159,  121,
       23,  159,   58,  159,  159,  120,  159,  159,  159,  159,
      159,  120,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  122,   24,  159,   60,  159,  159,  121,  159,
      159,  159,  159,  159,  121,  159,  159,  159,  122,   22,
      159,   55,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  120,  159,  159,  159,  159,  159,
      159,  121,   23,  159,   58,  159,  159,  120,  159,  159,

      159,  159,  159,  120,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  122,   24,  159,   60,  159,  159,
      121,  159,  159,  159,  159,  159,  121,  159,  159,  159,
      122,   21,  159,  159,  159,   34,   99,  159,  159,  159,
      159,  159,   99,  159,  159,  159,  100,  159,  159,  159,
      159,  159,  159,  101,   22,  159,  159,  159,   66,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  135,
      159,  159,  159,  159,  159,  159,  136,   23,  159,  159,
      159,   69,  135,  159,  159,  159,  159,  159,  135,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  137,

       24,  159,  159,  159,   71,  136,  159,  159,  159,  159,
      159,  136,  159,  159,  159,  137,  102,  103,  159,   22,
      159,  104,  102,  103,  159,   22,  159,  104,   22,  159,
      159,  159,   66,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  135,  159,  159,  159,  159,  159,  159,
      136,  108,  109,  159,   23,  159,  110,  108,  109,  159,
       23,  159,  110,   23,  159,  159,  159,   69,  135,  159,
      159,  159,  159,  159,  135,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  137,  112,  113,  159,   24,
      159,  114,  112,  113,  159,   24,  159,  114,   24,  159,

      159,  159,   71,  136,  159,  159,  159,  159,  159,  136,
      159,  159,  159,  137,   51,  159,   92,  159,  159,  149,
      159,  159,  159,  159,  159,  149,   51,  159,   92,  159,
      159,  149,  159,  159,  159,  159,  159,  149,   51,  159,
      159,  159,  111,  155,  159,  159,  159,  159,  159,  155,
       51,  159,  159,  159,  111,  155,  159,  159,  159,  159,
      159,  155,   21,   21,   21,   21,   21,   26,   26,   26,
       26,   26,   33,   33,   33,   33,   33,   22,   22,   22,
       22,   22,   23,   23,   23,   23,   23,   24,   24,   24,
       24,   24,   28,   28,   28,   28,   28,   29,   29,   29,

       29,   29,   30,   30,   30,   30,   30,   35,   35,   35,
       35,   35,   36,   36,   36,   36,   36,   37,   37,   37,
       37,   37,   38,   38,   38,   38,   39,   39,   39,  159,
       39,   73,   73,   73,   73,   73,   51,   51,  159,   51,
       51,   79,   79,   79,   79,   79,   56,   56,   56,   56,
       56,   57,   57,   57,   57,   57,   59,   59,   59,   59,
       59,   98,   98,   98,   98,   98,   67,   67,   67,   67,
       67,   68,   68,   68,   68,   68,   70,   70,   70,   70,
       70,   74,   74,   74,   74,   74,   75,   75,   75,   75,
       75,   76,   76,   76,   76,   76,   80,   80,   80,   80,

       80,   81,   81,   81,   81,   81,   82,   82,   82,   82,
       82,   87,  159,   87,   87,   87,   99,   99,   99,   99,
       99,  100,  100,  100,  100,  100,  101,  101,  101,  101,
      101,  106,  159,  106,  106,  106,  117,  117,  117,  117,
      117,  118,  118,  118,  118,  118,  119,  119,  119,  119,
      119,  120,  120,  120,  120,  120,  121,  121,  121,  121,
      121,  122,  122,  122,  122,  122,  135,  135,  135,  135,
      135,  136,  136,  136,  136,  136,  137,  137,  137,  137,
      137,  148,  159,  148,  148,  148,  149,  159,  149,  149,
      149,  155,  159,  155,  155,  155,    3,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159
    } ;

static yyconst flex_int16_t yy_chk[1223] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    9,   11,   12,   14,
       13,    4,   34,   34,   11,    4,  158,   34,   12,   13,
       14,   13,    4,    5,   15,    9,   17,    9,  155,    5,
       17,   15,   31,   22,   15,    5,   19,   17,   20,    5,
       22,   61,   19,   96,   20,   24,    5,    8,   20,    8,
       23,   24,    8,   19,   31,   24,   23,   32,    8,   61,
       27,   27,    8,   27,   96,   41,   46,   23,   46,    8,
       10,   47,   46,   49,   10,   10,   41,   32,  154,   47,

       49,   10,   47,   52,   52,   10,   52,   53,   53,   56,
       53,   56,   10,   16,   57,   77,   57,   62,   63,   63,
       64,   64,   16,   63,   16,   64,   77,   16,   16,   57,
       68,   56,   16,   18,   68,   62,  153,   67,  152,   86,
       86,   67,   86,  149,   18,   68,   18,   18,   18,   72,
       18,   18,   18,   18,   18,   18,   26,   72,   26,   67,
       72,   26,   74,   78,   97,   88,   88,   26,   88,   92,
       92,   26,   92,  117,   78,  105,  105,   74,   26,   28,
      105,   28,  115,   97,   74,  107,  107,  111,  111,  116,
      107,  118,  111,  115,   28,  117,  106,  120,  119,  120,

      116,   28,   29,  119,   29,   87,  118,   29,  121,  119,
      121,  123,  123,   29,  123,  124,  124,  133,  124,  120,
      125,   48,  125,  121,   29,   30,   44,   30,  126,  126,
       30,  126,  127,  127,   40,  127,   30,  133,  138,  138,
       30,   33,  125,  138,   21,   33,   33,  128,  128,  134,
      128,  129,   33,  129,  130,  130,   33,  130,  131,  131,
        7,  131,    6,   33,   35,    3,  129,  135,   35,  134,
      136,  135,  139,  139,  136,  141,  141,  139,  140,   35,
      141,    0,  140,  142,  142,  136,   35,   36,  142,  135,
        0,   36,   36,  144,  143,  143,    0,  144,   36,  143,

      140,  145,  145,    0,  150,  150,  145,  150,  144,   36,
       37,  146,  146,    0,   37,   37,  146,  151,  151,    0,
      151,   37,  156,  156,    0,   37,   43,  156,  157,  157,
        0,    0,    0,  157,    0,    0,    0,   43,    0,    0,
       43,    0,    0,    0,    0,   43,   45,    0,    0,    0,
        0,   45,    0,    0,    0,    0,    0,   45,    0,    0,
        0,   45,    0,    0,    0,    0,    0,    0,   45,   54,
        0,   54,    0,    0,   54,    0,    0,    0,    0,    0,
       54,    0,    0,    0,   54,    0,    0,    0,    0,    0,
        0,   54,   55,   55,    0,   55,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   55,    0,
        0,    0,    0,    0,    0,   55,   58,   58,    0,   58,
        0,    0,   58,    0,    0,    0,    0,    0,   58,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   58,
       59,    0,   59,    0,    0,   59,    0,    0,    0,    0,
        0,   59,   60,   60,    0,   60,    0,    0,   60,    0,
        0,    0,    0,    0,   60,    0,    0,    0,   60,   65,
        0,    0,    0,   65,   65,    0,    0,    0,    0,    0,
       65,    0,    0,    0,   65,    0,    0,    0,    0,    0,
        0,   65,   66,   66,    0,   66,    0,   66,   69,   69,

        0,   69,    0,   69,   70,    0,    0,    0,   70,   70,
        0,    0,    0,    0,    0,   70,   71,   71,    0,   71,
        0,   71,   73,    0,    0,    0,    0,   73,    0,    0,
        0,    0,    0,   73,    0,    0,    0,   73,    0,    0,
        0,    0,    0,    0,   73,   75,    0,    0,    0,    0,
       75,    0,    0,    0,    0,    0,   75,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   75,   76,    0,
        0,    0,    0,   76,    0,    0,    0,    0,    0,   76,
        0,    0,    0,   76,   79,    0,   79,    0,    0,   79,
        0,    0,    0,    0,    0,   79,    0,    0,    0,   79,

        0,    0,    0,    0,    0,    0,   79,   80,    0,   80,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   80,    0,    0,    0,    0,    0,    0,   80,
       81,    0,   81,    0,    0,   81,    0,    0,    0,    0,
        0,   81,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   81,   82,    0,   82,    0,    0,   82,    0,
        0,    0,    0,    0,   82,    0,    0,    0,   82,   85,
        0,   85,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   85,    0,    0,    0,    0,    0,
        0,   85,   91,    0,   91,    0,    0,   91,    0,    0,

        0,    0,    0,   91,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   91,   95,    0,   95,    0,    0,
       95,    0,    0,    0,    0,    0,   95,    0,    0,    0,
       95,   98,    0,    0,    0,   98,   98,    0,    0,    0,
        0,    0,   98,    0,    0,    0,   98,    0,    0,    0,
        0,    0,    0,   98,   99,    0,    0,    0,   99,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   99,
        0,    0,    0,    0,    0,    0,   99,  100,    0,    0,
        0,  100,  100,    0,    0,    0,    0,    0,  100,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  100,

      101,    0,    0,    0,  101,  101,    0,    0,    0,    0,
        0,  101,    0,    0,    0,  101,  102,  102,    0,  102,
        0,  102,  103,  103,    0,  103,    0,  103,  104,    0,
        0,    0,  104,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  104,    0,    0,    0,    0,    0,    0,
      104,  108,  108,    0,  108,    0,  108,  109,  109,    0,
      109,    0,  109,  110,    0,    0,    0,  110,  110,    0,
        0,    0,    0,    0,  110,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  110,  112,  112,    0,  112,
        0,  112,  113,  113,    0,  113,    0,  113,  114,    0,

        0,    0,  114,  114,    0,    0,    0,    0,    0,  114,
        0,    0,    0,  114,  122,    0,  122,    0,    0,  122,
        0,    0,    0,    0,    0,  122,  132,    0,  132,    0,
        0,  132,    0,    0,    0,    0,    0,  132,  137,    0,
        0,    0,  137,  137,    0,    0,    0,    0,    0,  137,
      147,    0,    0,    0,  147,  147,    0,    0,    0,    0,
        0,  147,  160,  160,  160,  160,  160,  161,  161,  161,
      161,  161,  162,  162,  162,  162,  162,  163,  163,  163,
      163,  163,  164,  164,  164,  164,  164,  165,  165,  165,
      165,  165,  166,  166,  166,  166,  166,  167,  167,  167,

      167,  167,  168,  168,  168,  168,  168,  169,  169,  169,
      169,  169,  170,  170,  170,  170,  170,  171,  171,  171,
      171,  171,  172,  172,  172,  172,  173,  173,  173,    0,
      173,  174,  174,  174,  174,  174,  175,  175,    0,  175,
      175,  176,  176,  176,  176,  176,  177,  177,  177,  177,
      177,  178,  178,  178,  178,  178,  179,  179,  179,  179,
      179,  180,  180,  180,  180,  180,  181,  181,  181,  181,
      181,  182,  182,  182,  182,  182,  183,  183,  183,  183,
      183,  184,  184,  184,  184,  184,  185,  185,  185,  185,
      185,  186,  186,  186,  186,  186,  187,  187,  187,  187,

      187,  188,  188,  188,  188,  188,  189,  189,  189,  189,
      189,  190,    0,  190,  190,  190,  191,  191,  191,  191,
      191,  192,  192,  192,  192,  192,  193,  193,  193,  193,
      193,  194,    0,  194,  194,  194,  195,  195,  195,  195,
      195,  196,  196,  196,  196,  196,  197,  197,  197,  197,
      197,  198,  198,  198,  198,  198,  199,  199,  199,  199,
      199,  200,  200,  200,  200,  200,  201,  201,  201,  201,
      201,  202,  202,  202,  202,  202,  203,  203,  203,  203,
      203,  204,    0,  204,  204,  204,  205,    0,  205,  205,
      205,  206,    0,  206,  206,  206,  159,  159,  159,  159,

      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  159,  159,  159,  159,  159,
      159,  159
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "xi-scan.l"
#line 2 "xi-scan.l"
#include <string.h>
#include "xi-symbol.h"
#include "xi-grammar.tab.h"
#include "CList.h"
#include <ctype.h>

/* Global Variables and Functions - used in grammar.y */
unsigned int lineno = 1;
int in_bracket=0; /*Horrific hack to get "array length" code snippets (between []'s)*/
int in_braces=0; /*Horrific hack to get SDAG entry code snippets (between {}'s)*/
int in_int_expr=0;
TList<Entry *> *connectEntries = new TList<Entry *>();
/* Local to file */
unsigned char in_comment=0;
int search(char *s);

/* We return Tokens only when not in a comment. */
#define Return if (!in_comment) return
#define	Token(x) x
#define Yval yylval.strval = strcpy(new char[yyleng+1], yytext)

#ifdef yywrap
#undef yywrap
#endif

#line 859 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 56 "xi-scan.l"

#line 1014 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 160 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1197 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 57 "xi-scan.l"
{ if (in_bracket) {Yval;return Token(CPROGRAM);} else REJECT;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 58 "xi-scan.l"
{ if (in_braces) {Yval;return Token(CPROGRAM);} else REJECT;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "xi-scan.l"
{ if (in_int_expr) {Yval;return Token(CPROGRAM);} else REJECT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "xi-scan.l"
{ /* ignore single line comments */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "xi-scan.l"
{ /* ignore ^M characters for dos-unix compat */ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "xi-scan.l"
{ in_comment = 1; /* Single line C-style comments */ }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "xi-scan.l"
{ in_comment = 0; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "xi-scan.l"
{ Return Token(HASHIF); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "xi-scan.l"
{ Return Token(HASHIFDEF); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "xi-scan.l"
{ in_comment = 0; /* comments */ }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "xi-scan.l"
{ Return Token(SCOPE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "xi-scan.l"
{ /* ignore white space */ }
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 69 "xi-scan.l"
{ lineno++;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "xi-scan.l"
{ Yval; Return Token(NUMBER); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 71 "xi-scan.l"
{ Yval; Return Token(LITERAL); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "xi-scan.l"
{ Return Token(search(yytext)); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "xi-scan.l"
{ Return Token(yytext[0]); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "xi-scan.l"
ECHO;
	YY_BREAK
#line 1199 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 160 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 160 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 159);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 74 "xi-scan.l"



struct rwtable {
  const char *res;	int tok;
};

/* Reserved word table */
struct rwtable rwtable[] = {
  "module",	MODULE,
  "mainmodule",	MAINMODULE,
  "chare",	CHARE,
  "group",	GROUP,
  "nodegroup",  NODEGROUP,
  "array",	ARRAY,
  "message",	MESSAGE,
  "conditional",CONDITIONAL,
  "extern",	EXTERN,
  "initcall",	INITCALL,
  "initnode",	INITNODE,
  "initproc",	INITPROC,
  "readonly",	READONLY,
  "stacksize",	STACKSIZE,
  "threaded",	THREADED,
  "migratable",	MIGRATABLE,
  "PUPable",	PUPABLE,
  "pupable",	PUPABLE,
  "createhere",	CREATEHERE,
  "createhome",	CREATEHOME,
  "nokeep",	NOKEEP,
  "notrace",	NOTRACE,
  "template",	TEMPLATE,
  "class",	CLASS,
  "include",	INCLUDE,
  "sync",	SYNC,
  "iget",       IGET,
  "exclusive",	EXCLUSIVE,
  "immediate",  IMMEDIATE,
  "expedited",  SKIPSCHED,
  "inline",  	INLINE,
  "local",      LOCAL,
  "virtual",    VIRTUAL,
  "mainchare",	MAINCHARE,
  "packed",     PACKED,
  "varsize",    VARSIZE,
  "entry",      ENTRY,
  "int",        INT,
  "short",      SHORT,
  "long",       LONG,
  "char",       CHAR,
  "float",      FLOAT,
  "double",     DOUBLE,
  "unsigned",   UNSIGNED,
  "void",	VOID,
  "const",	CONST,
  "atomic", 	ATOMIC,
  "forward", 	FORWARD,
  "when", 	WHEN, 
  "while", 	WHILE,
  "for",	FOR,
  "forall", 	FORALL, 
  "if", 	IF, 
  "else", 	ELSE,
  "overlap", 	OVERLAP,
  "connect",    CONNECT,
  "publishes",  PUBLISHES,
  "python",     PYTHON,
  "",		0
};

int search(char *s)
{
  int i;
  for(i=0; rwtable[i].tok != 0; i++) {
    if(strcmp(rwtable[i].res, s) == 0)
      return(rwtable[i].tok);
  }
  yylval.strval = strcpy(new char[yyleng+1], s);
  return IDENT;
}

int yywrap() { return 1; }

