CMK_DEFS="$CMK_DEFS -D_REENTRANT -m32"
CMK_FDEFS="$CMK_FDEFS -m32"

. $CHARMINC/cc-gcc.sh

CMK_XIOPTS=''
CMK_LIBS="-lpthread $CMK_LIBS"

CMK_QT='generic64-light'

CMK_MULTICORE='1'
CMK_SMP='1'
CMK_NO_PARTITIONS="1"
