. $CHARMINC/cc-gcc.sh

CMK_DEFS="$CMK_DEFS -D_REENTRANT -m32"

CMK_XIOPTS=''
CMK_LIBS="-lpthread $CMK_LIBS"

CMK_QT='generic64-light'

CMK_MULTICORE='1'
CMK_SMP='1'
CMK_NO_PARTITIONS="1"

CMK_CF77="$CMK_CF77 -m32"
CMK_CF90="$CMK_CF90 -m32"
CMK_CF90_FIXED="$CMK_CF90_FIXED -m32"
