CMK_CPP_CHARM='/usr/lib/cpp'
CMK_CPP_C='xlc -E'
CMK_CC='xlc'
CMK_CXX='xlC -qstaticinline'
CMK_CXXPP='xlC -E'
CMK_CF77='f77'
CMK_CF90='f90'
CMK_RANLIB='ranlib'
CMK_LIBS='-lckqt'
CMK_SEQ_CXX='xlC -D_H_UNISTD -DYY_NEVER_INTERACTIVE=1 -qstaticinline '
CMK_SEQ_LDXX='xlC'
CMK_QT='aix32-xlc'
CMK_XIOPTS=''
