# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex
DEST=charisma
LATEX2HTML=$(L2H) -split 4
DOCTITLE='Charisma Manual'
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/orch">Charisma Homepage</a><br>'

include ../Makefile.common

index.tex:
	touch index.tex
