#include "converse.h"

#if CMK_USE_HP_MAIN_FIX
void _main(argc,argv)
int argc;
char *argv[];
{
}
#endif

void CPlus_ChareExit()
{
}


void CPlus_GetAccMsgPtr()
{}

void CPlus_CallMonoInit()
{}

void CPlus_SetAccId()
{}

void CPlus_SetMonoId()
{}

void CPlus_CallCombineFn()
{}

void CPlus_CallAccInit()
{}

void CPlus_GetMonoMsgPtr()
{}

void CPlus_CallUpdateFn()
{}


void CPlus_SetMainChareID()
{}

/* projections.c calls this. For Charm++ files it is generated by translator*/
void _CKmain_DumpNames() 
{}

void futuresModuleInit()
{}

void futuresCreateBOC()
{}
