VMI_DIR="/usr/local/vmi-2.1.0-1-gcc"
#
VMI_INCDIR="-I$VMI_DIR/include"
VMI_LIBDIR="-L$VMI_DIR/lib"
#
CMK_CPP_C="icc -E $CMK_INCDIR $VMI_INCDIR "
CMK_CC="icc $CMK_INCDIR $VMI_INCDIR "
CMK_CC_RELIABLE="icc $CMK_INCDIR $VMI_INCDIR "
CMK_CC_FASTEST="icc $CMK_INCDIR $VMI_INCDIR "
CMK_CXX="icpc $CMK_INCDIR $VMI_INCDIR "
CMK_CXXPP="icpc -E $CMK_INCDIR $VMI_INCDIR "
CMK_LD="icc -rdynamic -pthread $VMI_LIBDIR "
CMK_LDXX="icpc -rdynamic -pthread $VMI_LIBDIR "
CMK_LD_LIBRARY_PATH="-Wl,-rpath,$CHARMLIBSO/"
CMK_NATIVE_CC="icc $CMK_INCDIR $VMI_INCDIR "
CMK_NATIVE_LD="icc $CMK_INCDIR $VMI_INCDIR "
CMK_NATIVE_CXX="icpc $CMK_INCDIR $VMI_INCDIR "
CMK_NATIVE_LDXX="icpc $CMK_INCDIR $VMI_INCDIR "

