BUILD_GPU_MANAGER=$(shell CHARMINC=.; if test -f ./conv-config.sh; then . ./conv-config.sh; echo $$BUILD_CUDA; fi )

ifeq "$(BUILD_GPU_MANAGER)" "1"
hybridAPI: 
	   cd hybridAPI && make install

charm++: hybridAPI

.PHONY: hybridAPI
endif

$(L)/libconv-cplus-n.a: machine.h machine.c machine-common-core.c machine-broadcast.c machine-lrts.h machine-pxshm.c machine-xpmem.c machine-persistent.c machine-commthd-util.c machine-smp.c pcqueue.h

