$(L)/libconv-cplus-n.a: machine.h machine.c machine-common-core.c machine-broadcast.c machine-lrts.h machine-pxshm.c machine-xpmem.c machine-persistent.c machine-commthd-util.c machine-smp.c pcqueue.h  $(L)/cray_tlbhack.o

$(L)/cray_tlbhack.o: cray_tlbhack.c
	$(CHARMC) -o $@ cray_tlbhack.c

