CMK_DEFS=' -D_REENTRANT '
CMK_CPP_CHARM="/usr/ccs/lib/cpp $CMK_DEFS"
CMK_CPP_C="cc +w -E $CMK_DEFS"
CMK_CC="cc +w $CMK_DEFS"
CMK_CC_RELIABLE="cc +w $CMK_DEFS "
CMK_CC_FASTEST="cc +w $CMK_DEFS "
CMK_CXX="CC +w $CMK_DEFS "
CMK_CXXPP="CC +w -E $CMK_DEFS "
CMK_CF77='f77'
CMK_CF90='f90'
CMK_C_DEBUG='-g'
CMK_C_OPTIMIZE='-fast'
CMK_CXX_DEBUG='-g'
CMK_CXX_OPTIMIZE='-fast'
CMK_LD="cc -xildoff $CMK_DEFS "
CMK_LDXX="CC -xildoff $CMK_DEFS "
CMK_LD77=''
CMK_M4='m4'
CMK_SUF='o'
CMK_AR='ar q'
CMK_RANLIB='true'
CMK_LIBS=' -lthread -lnsl -lsocket -lckqt'
CMK_SEQ_LIBS=' -lnsl -lsocket'
CMK_SEQ_CC='cc +w '
CMK_SEQ_LD='cc '
CMK_SEQ_CXX='CC +w '
CMK_SEQ_LDXX='CC '
CMK_CPP_SUFFIX="cc"
CMK_XLATPP='charmxlat++ -w -p '
CMK_QT='solaris-cc'
CMK_XIOPTS=''
