#! /bin/sh

args=""
QUIET=0

while [ $# -gt 0 ]
do
        case $1 in
	+p|+ppn)     args=$args" "$1" "$2
                shift;
		shift
		;;
        ++ppn)  echo please use +ppn instead of ++ppn
                exit 1
                ;;
	++quiet)
		QUIET=1
		args=$args" "$1
		shift
		;;
	++local)
		# consume and ignore, local-mode is all that multicore supports
		shift
		;;
        +*)
                args=$args" "$1
                shift
                ;;
        *)
		break;
		;;
	esac
done

test $QUIET -eq 0 && echo Running command: $* $args
test $QUIET -eq 0 && echo

exec $* $args
