# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex 

DEST=f90charm
LATEX2HTML=$(L2H) -split 5
DOCTITLE='Fortran90 Bingings for Charm++'

include ../Makefile.common

index.tex:
	touch index.tex
