#PROPAGATE_DEFS = $(. ./conv-config.sh)
#
#propagate_defs:
#	$(PROPAGATE_DEFS)

#export CHARMINC=../include

BUILD_GPU_MANAGER=$(shell CHARMINC=.; if test -f ./conv-config.sh; then . ./conv-config.sh; echo $$BUILD_CUDA; fi )

ifeq "$(BUILD_GPU_MANAGER)" "1"
hybridAPI: 
	   cd hybridAPI && make install

charm++: hybridAPI

.PHONY: hybridAPI
endif