# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex
DEST=ampi
LATEX2HTML=$(L2H) -split 4
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/ampi">AMPI Homepage</a><br>'

include ../Makefile.common
