CMK_CPP_CHARM='/usr/ccs/lib/cpp '
CMK_CPP_C='cc -E '
CMK_CC='cc -Kpic '
CMK_CC_RELIABLE='cc '
CMK_CC_FASTEST='cc '
CMK_CXX='CC -Kpic -library=Cstd'
CMK_CXXPP='CC -E '
CMK_CF77='f77'
CMK_CF90='f90'
CMK_C_DEBUG='-g'
CMK_C_OPTIMIZE='-fast'
CMK_CXX_DEBUG='-g'
CMK_CXX_OPTIMIZE='-fast'
CMK_LD='cc '
CMK_LDXX='CC -library=Cstd'
CMK_LD77=''
CMK_M4='m4'
CMK_SUF='o'
CMK_AR='CC -xar -o'
CMK_RANLIB='true'
CMK_LIBS='-lnsl -lsocket -lckqt'
CMK_SEQ_LIBS='-lnsl -lsocket'
CMK_SEQ_CC='cc'
CMK_SEQ_LD='cc'
CMK_SEQ_CXX='CC -library=Cstd'
CMK_SEQ_LDXX='CC -library=Cstd'
CMK_CPP_SUFFIX="cc"
CMK_XLATPP='charmxlat++ -w -p '
CMK_QT='solaris-cc'
CMK_XIOPTS=''
CMK_F90LIBS='-lfsu -lsunmath -lfsumai -lfminvai -lfmaxvai -lfui'
