# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex barrier.tex ddt.tex intro.tex irecv.tex liveviz.tex tempo.tex

DEST=charm++
LATEX2HTML=$(L2H) -split 5

include ../Makefile.common

index.tex:
	touch index.tex
