# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex barrier.tex ddt.tex intro.tex irecv.tex liveviz.tex tempo.tex fftlib.tex

DEST=libraries
LATEX2HTML=$(L2H) -split 5
DOCTITLE='C<SMALL>ONVERSE</SMALL> and C<SMALL>HARM++</SMALL> Libraries Manual'

include ../Makefile.common

index.tex:
	touch index.tex
