# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex intro.tex liveviz.tex fftlib.tex gpumanager.tex

DEST=libraries
LATEX2HTML=$(L2H) -split 5
DOCTITLE='Converse and Charm++ Libraries Manual'

include ../Makefile.common

index.tex:
	touch index.tex
