CMK_DEFS=' -D_REENTRANT -D_THREAD_SAFE -qtls=local-exec'
CMK_CPP_C="$CMK_CPP_C $CMK_DEFS"
CMK_CC="$CMK_CC $CMK_DEFS"
CMK_CC_RELIABLE="$CMK_CC_RELIABLE $CMK_DEFS "
CMK_CC_FASTEST="$CMK_CC_FASTEST $CMK_DEFS "
CMK_CXX="$CMK_CXX  $CMK_DEFS "
CMK_CXXPP="$CMK_CXXPP $CMK_DEFS "
CMK_LD="$CMK_LD $CMK_DEFS "
CMK_LDXX="$CMK_LDXX $CMK_DEFS "

if test $isAIX = true
then
CMK_PTHREAD_LIB="-lpthreads"
else
CMK_PTHREAD_LIB="-lpthread"
fi
CMK_LIBS=" $CMK_PTHREAD_LIB $CMK_LIBS "

CMK_SEQ_CC="$CMK_SEQ_CC -qtls=local-exec"
CMK_SEQ_CXX="$CMK_SEQ_CXX -qtls=local-exec"
