# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex index.tex
DEST=ifem
LATEX2HTML=$(L2H) -split 4
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/fem">FEM Homepage</a><br>'

include ../Makefile.common
