#line 2 "conv-cpm.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#ifdef WIN32
#include <stdlib.h>
#endif


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 16
#define YY_END_OF_BUFFER 17
static yyconst short int yy_accept[106] =
    {   0,
        0,    0,   17,   15,   13,   14,   15,   15,   15,    9,
        8,    4,    4,   13,    0,   11,    0,    0,    0,    6,
        5,    9,    0,    0,    9,    9,    0,    8,    8,    8,
        4,    4,    0,    0,   12,    0,    0,    0,    6,    5,
        0,    5,    0,    7,    9,    9,   10,    8,    8,    4,
        0,    0,    0,    0,    0,    6,    0,    5,    7,   10,
       10,    4,    4,    0,    0,    0,    0,   10,   10,    4,
        4,    0,    0,    4,    4,    0,    0,    4,    4,    0,
        0,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    3,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    2,    1,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    6,    1,    6,    7,    1,    8,    9,   10,
       10,   10,   10,   10,   10,   11,   11,    1,    1,    1,
        1,    1,   12,    1,   13,   13,   14,   15,   16,   17,
       18,   18,   19,   18,   18,   20,   18,   18,   18,   21,
       18,   18,   22,   18,   23,   18,   18,   24,   18,   18,
        1,   25,    1,    1,   18,    1,   26,   27,   28,   13,

       29,   30,   18,   18,   31,   18,   32,   33,   34,   35,
       36,   37,   18,   38,   18,   39,   23,   40,   18,   24,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[41] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    5,    5,    5,
        6,    4,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    8,    4,    5,    5,    6,    6,    5,
        7,    7,    7,    7,    8,    7,    7,    8,    8,    8
    } ;

static yyconst short int yy_base[115] =
    {   0,
        0,   25,  226,  415,  223,  415,   13,  198,   10,   44,
       71,    0,  185,  217,   18,  415,   32,   19,   37,   97,
      123,  189,  150,   87,  189,   29,    0,    0,  187,   37,
        0,  173,  111,    0,  415,  137,    0,  159,  415,    0,
      165,  415,   75,  172,  415,  415,   43,  415,  415,   50,
      186,   85,  189,   98,  140,  207,  176,  233,  415,  183,
       38,  175,  168,   86,  263,   99,  290,  415,  415,  173,
      151,  184,  196,  145,  141,  313,  336,  146,  132,  112,
      138,  117,  128,  115,  111,   53,  102,   93,   97,   96,
       87,   78,    0,   66,   62,   53,   55,   43,   30,   10,

        6,    4,    0,    0,  415,  366,  374,  382,  386,  393,
      400,  404,  406,  408
    } ;

static yyconst short int yy_def[115] =
    {   0,
      106,  106,  105,  105,  105,  105,  107,  108,  105,  105,
      105,  109,  109,  105,  107,  105,  110,  108,  111,  105,
      105,   10,  105,  105,  105,  105,  112,   11,  105,  105,
      109,  109,  107,  113,  105,  108,  114,  105,  105,   21,
      105,  105,  105,  105,  105,  105,  112,  105,  105,  109,
      107,  107,  108,  108,  105,  105,  105,  105,  105,  105,
      105,  109,  109,  107,  107,  108,  108,  105,  105,  109,
      109,  107,  108,  109,  109,   65,   67,  109,  109,  107,
      108,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      109,  109,  109,  109,    0,  105,  105,  105,  105,  105,
      105,  105,  105,  105
    } ;

static yyconst short int yy_nxt[456] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   11,
       11,    4,  104,   13,  103,  105,   16,   20,   20,   20,
       20,   16,   35,  105,    4,    4,    5,    6,    7,    8,
        4,    9,   10,   11,   11,   11,    4,   17,   13,   33,
       33,   33,   17,   19,   36,   36,   36,  102,   46,    4,
       21,   22,   22,   22,   23,   34,   49,   69,  101,   24,
       37,   46,   60,   25,   62,   61,   26,   27,   63,   49,
       69,  100,   24,   88,   89,   60,   25,   21,   28,   28,
       28,   28,   44,   44,   44,   44,   24,   99,   16,   16,
       29,   98,   43,   30,   44,   44,   44,   44,   97,   24,

       96,   35,   35,   29,   20,   20,   20,   20,   65,   17,
       17,   95,   38,   39,   16,   16,   39,   94,   51,   51,
       51,   67,   19,   19,   93,   38,   39,   92,   91,   39,
       40,   40,   40,   40,   90,   17,   17,   87,   41,   42,
       35,   35,   42,   86,   53,   53,   53,   56,   56,   56,
       56,   41,   42,   85,   84,   42,   21,   23,   23,   23,
       23,   19,   19,   83,   55,   24,   56,   56,   56,   56,
       57,   82,   58,   58,   58,   58,   79,   78,   24,   44,
       44,   44,   44,   58,   58,   58,   58,   16,   59,   16,
       75,   59,   35,   64,   64,   64,   66,   66,   66,   35,

       74,   59,   71,   70,   59,   68,   50,   76,   17,   48,
       17,   45,  105,   19,   56,   56,   56,   56,   14,   77,
       19,   32,   19,   39,   14,  105,   39,  105,  105,  105,
      105,  105,  105,  105,  105,  105,   39,  105,  105,   39,
       58,   58,   58,   58,  105,  105,  105,  105,  105,   42,
      105,  105,   42,  105,  105,  105,  105,  105,  105,  105,
      105,  105,   42,  105,  105,   42,   16,  105,  105,  105,
       72,   72,   72,   72,  105,   72,   72,   72,   72,   72,
      105,  105,  105,  105,  105,  105,  105,   17,   72,   72,
       72,   72,   72,   35,  105,  105,  105,   73,   73,   73,

       73,  105,   73,   73,   73,   73,   73,  105,  105,  105,
      105,  105,  105,  105,   19,   73,   73,   73,   73,   73,
       80,   80,   80,   80,  105,   80,   80,   80,   80,   80,
      105,  105,  105,  105,  105,  105,  105,  105,   80,   80,
       80,   80,   80,   81,   81,   81,   81,  105,   81,   81,
       81,   81,   81,  105,  105,  105,  105,  105,  105,  105,
      105,   81,   81,   81,   81,   81,   12,   12,   12,   12,
       12,   12,   12,   12,   15,  105,   15,   15,   15,   15,
       15,   15,   18,  105,  105,   18,   18,   18,   18,   18,
       31,   31,   31,   31,   15,   15,   15,   15,  105,  105,

       15,   18,   18,   18,   18,  105,  105,   18,   47,   47,
       52,   52,   54,   54,    3,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105
    } ;

static yyconst short int yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,  102,    1,  101,    0,    7,    9,    9,    9,
        9,   15,   18,    0,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    7,    2,   17,
       17,   17,   15,   18,   19,   19,   19,  100,   26,    2,
       10,   10,   10,   10,   10,   17,   30,   61,   99,   10,
       19,   26,   47,   10,   50,   47,   10,   10,   50,   30,
       61,   98,   10,   86,   86,   47,   10,   11,   11,   11,
       11,   11,   43,   43,   43,   43,   11,   97,   52,   64,
       11,   96,   24,   11,   24,   24,   24,   24,   95,   11,

       94,   54,   66,   11,   20,   20,   20,   20,   52,   52,
       64,   92,   20,   20,   33,   80,   20,   91,   33,   33,
       33,   54,   54,   66,   90,   20,   20,   89,   88,   20,
       21,   21,   21,   21,   87,   33,   80,   85,   21,   21,
       36,   81,   21,   84,   36,   36,   36,   55,   55,   55,
       55,   21,   21,   83,   82,   21,   23,   23,   23,   23,
       23,   36,   81,   79,   38,   23,   38,   38,   38,   38,
       41,   78,   41,   41,   41,   41,   75,   74,   23,   44,
       44,   44,   44,   57,   57,   57,   57,   72,   44,   51,
       71,   44,   53,   51,   51,   51,   53,   53,   53,   73,

       70,   44,   63,   62,   44,   60,   32,   72,   72,   29,
       51,   25,   22,   53,   56,   56,   56,   56,   14,   73,
       73,   13,    8,   56,    5,    3,   56,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   56,    0,    0,   56,
       58,   58,   58,   58,    0,    0,    0,    0,    0,   58,
        0,    0,   58,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   58,    0,    0,   58,   65,    0,    0,    0,
       65,   65,   65,   65,    0,   65,   65,   65,   65,   65,
        0,    0,    0,    0,    0,    0,    0,   65,   65,   65,
       65,   65,   65,   67,    0,    0,    0,   67,   67,   67,

       67,    0,   67,   67,   67,   67,   67,    0,    0,    0,
        0,    0,    0,    0,   67,   67,   67,   67,   67,   67,
       76,   76,   76,   76,    0,   76,   76,   76,   76,   76,
        0,    0,    0,    0,    0,    0,    0,    0,   76,   76,
       76,   76,   76,   77,   77,   77,   77,    0,   77,   77,
       77,   77,   77,    0,    0,    0,    0,    0,    0,    0,
        0,   77,   77,   77,   77,   77,  106,  106,  106,  106,
      106,  106,  106,  106,  107,    0,  107,  107,  107,  107,
      107,  107,  108,    0,    0,  108,  108,  108,  108,  108,
      109,  109,  109,  109,  110,  110,  110,  110,    0,    0,

      110,  111,  111,  111,  111,    0,    0,  111,  112,  112,
      113,  113,  114,  114,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "conv-cpm.flex"
#define INITIAL 0
#line 2 "conv-cpm.flex"
#include <stdio.h>
#include <string.h>
int tok_lineno = 0;
int yytoktype;

/******************************************************************************
 *
 * Files
 *
 *****************************************************************************/

FILE *file_src;
FILE *file_cpm;

/******************************************************************************
 *
 * Lexical Analyzer
 *
 *****************************************************************************/
#line 520 "conv-cpm.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 32 "conv-cpm.flex"


#line 674 "conv-cpm.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 106 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 415 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "conv-cpm.flex"
{ return 'P'; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "conv-cpm.flex"
{ return 'S'; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "conv-cpm.flex"
{ return 'I'; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "conv-cpm.flex"
{ return 'i'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "conv-cpm.flex"
{ return '0'; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "conv-cpm.flex"
{ return '"'; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "conv-cpm.flex"
{ return 'c'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "conv-cpm.flex"
{ }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "conv-cpm.flex"
{ tok_lineno++; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "conv-cpm.flex"
{ return yytext[0]; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "conv-cpm.flex"
ECHO;
	YY_BREAK
#line 837 "conv-cpm.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 106 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 106 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 105);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;
	static int _xpg = -1;

	if (_xpg == -1)
		{
			char *_xpgenv = getenv("_XPG");
			if (_xpgenv == NULL)
				_xpg = 0;
			else
				{
				_xpg = atoi(_xpgenv);
				if (_xpg < 0)
					_xpg = 0;
				}
		}

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					if (_xpg)
						return 0;
					else
						{
						if ( yywrap() )
							return 0;

						if ( ! yy_did_buffer_switch_on_eof )
							YY_NEW_FILE;
#ifdef __cplusplus
						return yyinput();
#else
						return input();
#endif
						}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 50 "conv-cpm.flex"



#ifdef yywrap
#undef yywrap
#endif
yywrap(){ return(1); }

void yytokget()
{
  yytoktype=yylex();
}

void yychkword(char *s)
{
  if (strcmp(yytext, s)) {
    fprintf(stderr,"%s expected\n", s);
    exit(1);
  }
}

void yychktype(char c)
{
  if (yytoktype == c) return;
  if (c=='i') {
    fprintf(stderr,"identifier expected\n");
    exit(1);
  } else {
    fprintf(stderr,"%c expected\n",c);
    exit(1);
  }
}

/******************************************************************************
 *
 * The 'symbol table', such as it is.
 *
 *****************************************************************************/

char *mod_funcs[1000];
int   mod_len;

char *type_name[1000];
int   type_kind[1000];
int   type_count;

char *func_name;
char *func_args[1000];
int   func_array[1000];
int   func_pointer[1000];
int   func_len;
int   func_static;

int type_simple(char *type)
{
  int i;
  for (i=0; i<type_count; i++) {
    if (strcmp(type, type_name[i])==0)
      return (type_kind[i]=='S') ? 1:0;
  }
  fprintf(stderr,"Unknown type %s\n", type);
  exit(1); return 0;
}

void type_declare(char *type, int kind)
{
  if (type_count==1000) {
    fprintf(stderr,"error: type table overflow.\n");
    exit(1);
  }
  type_name[type_count] = strdup(type);
  type_kind[type_count] = kind;
  type_count++;
}

/******************************************************************************
 *
 * Code Generation
 *
 *****************************************************************************/

void gen_actual_args(FILE *f)
{
  int i;
  fprintf(f, "(");
  if (func_len) {
    fprintf(f, "CpmA0");
    for (i=1; i<func_len; i++) {
      fprintf(f, ",CpmA%d", i);
    }
  }
  fprintf(f,");\n");
}

void gen_dimension_required()
{
  fprintf(stderr,"CpmDim required before array.\n");
  exit(1);
}

void gen_func_struct()
{
  int i;
  fprintf(file_cpm, "struct CpmSt_%s\n", func_name);
  fprintf(file_cpm, "{\n");
  fprintf(file_cpm, "char convcore[CmiMsgHeaderSizeBytes];\n");
  fprintf(file_cpm, "unsigned int envpos;\n");
  for (i=0; i<func_len; i++) {
    if ((func_pointer[i]==0) && (func_array[i]==0)) {
      fprintf(file_cpm, "%s f%d;\n",func_args[i],i);
    } else {
      fprintf(file_cpm, "int f%d;\n",i);
    }
  }
  fprintf(file_cpm, "};\n");
}

void gen_func_recv()
{
  int i;
  fprintf(file_cpm, "static void CpmRecv_%s(char *CpmM)\n", func_name);
  fprintf(file_cpm, "{\n");
  fprintf(file_cpm, "struct CpmSt_%s *CpmS=(struct CpmSt_%s *)CpmM;\n",
	  func_name, func_name);
  fprintf(file_cpm, "char *CpmX = (char *)CpmS;\n");
  fprintf(file_cpm, "int i;\n");
  for (i=0; i<func_len; i++) {
    fprintf(file_cpm, "%s %sCpmA%d;\n", func_args[i], func_array[i]?"*":"", i);
  }
  for (i=0; i<func_len; i++) {
    int mode = (func_pointer[i] ? 2 : 0) + (func_array[i] ? 1 : 0);
    switch(mode) {
    case 0: /* simple */
      fprintf(file_cpm, "CpmA%d = CpmS->f%d;\n", i, i);
      fprintf(file_cpm, "CpmUnpack_%s(CpmA%d);\n", func_args[i], i);
      break;
    case 1: /* array of simple */
      if ((i==0)||(func_array[i-1])||(strcmp(func_args[i-1],"CpmDim")))
	gen_dimension_required();
      fprintf(file_cpm, "CpmA%d = (%s *)(CpmX+(CpmS->f%d));\n", i, func_args[i], i);
      fprintf(file_cpm, "for (i=0; i<CpmA%d; i++)\n", i-1);
      fprintf(file_cpm, "  CpmUnpack_%s(CpmA%d[i]);\n", func_args[i], i);
      break;
    case 2: /* pointer */
      fprintf(file_cpm, "CpmA%d = (%s)(CpmX+(CpmS->f%d));\n", i, func_args[i], i);
      fprintf(file_cpm, "CpmPtrUnpack_%s(CpmA%d);\n", func_args[i], i);
      break;
    case 3: /* array of pointer */
      if ((i==0)||(func_array[i-1])||(strcmp(func_args[i-1],"CpmDim")))
	gen_dimension_required();
      fprintf(file_cpm, "CpmA%d = (%s *)(CpmX+(CpmS->f%d));\n", i, func_args[i], i);
      fprintf(file_cpm, "for (i=0; i<CpmA%d; i++) {\n", i-1);
      fprintf(file_cpm, "  CpmA%d[i] = CpmM + (size_t)(CpmA%d[i]);\n", i, i);
      fprintf(file_cpm, "  CpmPtrUnpack_%s(CpmA%d[i]);\n", func_args[i], i);
      fprintf(file_cpm, "}\n");
      break;
    }
  }
  fprintf(file_cpm,"%s", func_name);
  gen_actual_args(file_cpm);
  fprintf(file_cpm,"CmiFree(CpmM);\n");
  fprintf(file_cpm, "}\n");
}

void gen_func_send()
{
  int i;
  if (func_static) fprintf(file_cpm, "static ");

  fprintf(file_cpm,"void *Cpm_%s(CpmDestination ctrl",func_name);
  for (i=0; i<func_len; i++) {
    fprintf(file_cpm, ",%s %sa%d", func_args[i], func_array[i]?"*":"", i);
  }
  fprintf(file_cpm, ")\n");
  fprintf(file_cpm, "{\n");
  fprintf(file_cpm, "struct CpmSt_%s *msg;\n",func_name);
  fprintf(file_cpm, "char *data; int size, i, envpos; void *result;\n");
  fprintf(file_cpm, "int offs = CpmAlign(sizeof(struct CpmSt_%s), double);\n",func_name);
  for (i=0; i<func_len; i++) {
    if (func_array[i])
      fprintf(file_cpm, "int aoffs%d;\n",i);
    if (func_pointer[i]) {
      if (func_array[i]) {
	fprintf(file_cpm, "size_t *poffs%d = (size_t *)malloc(a%d*sizeof(size_t));\n",i,i-1);
      } else {
	fprintf(file_cpm, "int poffs%d;\n",i);
      }
    }
  }
  fprintf(file_cpm, "envpos=offs; offs=CpmAlign(offs+(ctrl->envsize),double);\n");
  for (i=0; i<func_len; i++) {
    if (func_array[i]) {
      fprintf(file_cpm, "size=a%d*sizeof(%s);\n",i-1,func_args[i]);
      fprintf(file_cpm, "aoffs%d=offs; offs=CpmAlign(offs+size,double);\n",i);
    }
  }
  for (i=0; i<func_len; i++) {
    if (func_pointer[i]) {
      if (func_array[i]) {
	fprintf(file_cpm, "for (i=0; i<a%d; i++) {\n",i-1) ;
	fprintf(file_cpm, "  size = CpmPtrSize_%s(a%d[i]);\n",func_args[i],i);
	fprintf(file_cpm, "  poffs%d[i]=offs; offs=CpmAlign(offs+size,double);\n",i);
	fprintf(file_cpm, "}\n");
      } else {
	fprintf(file_cpm, "size = CpmPtrSize_%s(a%d);\n",func_args[i],i);
	fprintf(file_cpm, "poffs%d=offs; offs=CpmAlign(offs+size, double);\n",i);
      }
    }
  }
  fprintf(file_cpm, "data = (char *)CmiAlloc(offs);\n");
  fprintf(file_cpm, "msg = (struct CpmSt_%s *)data;\n",func_name);
  fprintf(file_cpm, "msg->envpos = envpos;\n");
  for (i=0; i<func_len; i++) {
    int mode = (func_array[i]?2:0) | (func_pointer[i]?1:0);
    switch(mode) {
    case 0: /* one simple */
      fprintf(file_cpm, "CpmPack_%s(a%d);\n",func_args[i],i);
      fprintf(file_cpm, "msg->f%d = a%d;\n",i,i);
      break;
    case 1: /* one pointer */
      fprintf(file_cpm, "msg->f%d = poffs%d;\n",i,i);
      fprintf(file_cpm, "CpmPtrPack_%s(((%s)(data+poffs%d)), a%d);\n",
	      func_args[i],func_args[i],i,i);
      break;
    case 2: /* array simple */
      fprintf(file_cpm, "msg->f%d = aoffs%d;\n",i,i);
      fprintf(file_cpm, "memcpy(data+aoffs%d, a%d, a%d*sizeof(%s));\n",
	      i,i,i-1,func_args[i]);
      fprintf(file_cpm, "for(i=0; i<a%d; i++)\n",i-1);
      fprintf(file_cpm, "  CpmPack_%s(((%s *)(data+aoffs%d))[i]);\n",
	      func_args[i],func_args[i],i);
      break;
    case 3: /* array pointer */
      fprintf(file_cpm, "msg->f%d = aoffs%d;\n",i,i);
      fprintf(file_cpm, "memcpy(data+aoffs%d, poffs%d, a%d*sizeof(size_t));\n",
	      i,i,i-1);
      fprintf(file_cpm, "for(i=0; i<a%d; i++)\n",i-1);
      fprintf(file_cpm, "  CpmPtrPack_%s(((%s)(data+(poffs%d[i]))), a%d[i]);\n",
	      func_args[i],func_args[i], i,i);
      break;
    }
  }
  fprintf(file_cpm,"CmiSetHandler(msg, CpvAccess(CpmIndex_%s));\n",func_name);
  fprintf(file_cpm,"result = (ctrl->sendfn)(ctrl, offs, msg);\n");
  for (i=0; i<func_len; i++)
    if ((func_pointer[i])&&(func_array[i]))
      fprintf(file_cpm, "free(poffs%d);\n", i);
  fprintf(file_cpm,"return result;\n");
  fprintf(file_cpm,"}\n");
}

void gen_func_protos()
{
  int i;

  fprintf(file_cpm, "CpvStaticDeclare(int, CpmIndex_%s);\n", func_name);

  fprintf(file_cpm,"void %s(",func_name);
  if (func_len) {
    fprintf(file_cpm, "%s %s", func_args[0], func_array[0]?"*":"");
    for (i=1; i<func_len; i++)
      fprintf(file_cpm, ",%s %s", func_args[i], func_array[i]?"*":"");
  }
  fprintf(file_cpm,");\n");
}

void gen_func_c()
{
  gen_func_protos();
  gen_func_struct();
  gen_func_recv();
  gen_func_send();
}

void gen_mod_head()
{
  fprintf(file_cpm, "CpvStaticDeclare(int, CpmIPRIO);\n");
}

void gen_mod_tail()
{
  int i;
  fprintf(file_cpm, "static void CpmInitializeThisModule()\n");
  fprintf(file_cpm, "{\n");
  fprintf(file_cpm, "CpvInitialize(int, CpmIPRIO);\n");
  for (i=0; i<mod_len; i++) {
    fprintf(file_cpm, "CpvInitialize(int, CpmIndex_%s);\n", mod_funcs[i]);
    fprintf(file_cpm, "CpvAccess(CpmIndex_%s) = CmiRegisterHandler((CmiHandler)CpmRecv_%s);\n",
	  mod_funcs[i], mod_funcs[i]);
  }
  fprintf(file_cpm, "}\n");
}

/******************************************************************************
 *
 * The Parser
 *
 *****************************************************************************/

void parse_type()
{
  int kind = yytoktype;
  yytokget();
  if (strncmp(yytext,"CpmType_",8)==0) {
    type_declare(yytext+8, kind);
  }
  yytokget();
}

void parse_list()
{
  int level=1;
  yychktype('{');
  yytokget();
  while (level) {
    if (yytoktype == '{') level++;
    if (yytoktype == '}') level--;
    if (yytoktype==0) return;
    yytokget();
  }
}

void parse_func()
{
  yychkword("CpmInvokable");
  yytokget();
  if (yytoktype==';')
    return;
  func_len=0;
  func_static=0;
  if (strcmp(yytext,"static")==0) {
    func_static=1;
    yytokget();
  }
  yychktype('i');
  func_name = strdup(yytext);
  yytokget();
  yychktype('(');
  yytokget();
  if (yytoktype != ')') {
    while (1) {
      yychktype('i');
      func_args[func_len] = strdup(yytext);
      func_array[func_len] = 0;
      yytokget();
      if (yytoktype == '*') {
	yytokget();
	func_array[func_len] = 1;
      }
      func_pointer[func_len] = !type_simple(func_args[func_len]);
      func_len++;
      yychktype('i');
      yytokget();
      if (yytoktype == ')') break;
      yychktype(',');
      yytokget();
    }
  }
  yytokget();
  mod_funcs[mod_len++] = func_name;
  gen_func_c();
}

void parse_all()
{  
  yyin = file_src;
  yytokget();
  gen_mod_head();
  top:
  switch (yytoktype) {
  case 0: break;
  case 'P': parse_type(); goto top;
  case 'S': parse_type(); goto top;
  case 'I': parse_func(); goto top;
  case '{': parse_list(); goto top;
  default: yytokget(); goto top; 
  }
  gen_mod_tail();
}

/******************************************************************************
 *
 * Setup
 *
 *****************************************************************************/

void usage()
{
  fprintf(stderr,"usage: cpm <modulename>\n");
  exit(1);
}

FILE *fopen_nofail(char *path, char *mode)
{
  FILE *res = fopen(path, mode);
  if (res==0) {
    fprintf(stderr,"Couldn't open %s with mode %s\n",path,mode);
    exit(1);
  }
  return res;
}

void disclaim(FILE *f, char *src)
{
  fprintf(f,"/* WARNING: This file generated by Converse */\n");
  fprintf(f,"/* Marshalling System from source-file %s. */\n",src);
  fprintf(f,"\n");
}

main(int argc, char **argv)
{
  if (argc != 3) usage();
  file_src = fopen_nofail(argv[1], "r");
  file_cpm = fopen_nofail(argv[2], "w");
  disclaim(file_cpm, argv[1]);
  parse_all();
  exit(0);
}
