. $CHARMINC/cc-gcc.sh

CMK_CPP_C_FLAGS="$CMK_CPP_C_FLAGS -m32"
CMK_CC_FLAGS="$CMK_CC_FLAGS -m32"
CMK_CXX_FLAGS="$CMK_CXX_FLAGS -m32"
CMK_LD="$CMK_CC "
CMK_LDXX="$CMK_CXX "
CMK_LD_FLAGS="$CMK_CC_FLAGS "
CMK_LDXX_FLAGS="$CMK_CXX_FLAGS "
CMK_XIOPTS=''
CMK_QT='i386-gcc'

CMK_CF77="$CMK_CF77 -m32"
CMK_CF90="$CMK_CF90 -m32"
CMK_CF90_FIXED="$CMK_CF90_FIXED -m32"
