# Stub makefile for LaTeX PPL manual
FILE=manual
TEX=$(FILE).tex
DEST=mblock
LATEX2HTML=$(L2H) -split 4
DOCTITLE='Multiblock Framework Manual'
PROJECT_LINK='<a href="http://charm.cs.uiuc.edu/research/mblock">MBlock Homepage</a><br>'

include ../Makefile.common
